### PR TITLE
Test and edit Your First Dapp tutorial

### PR DESCRIPTION
**Pull request by clay-aptos**
### Description

Walked through the tutorial line by line
Ran the example and updated output to match
Edited the text throughout

### Test Plan

Edit ans test doc in browser

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5106)

### CODE REVIEW

**Comment by davidiw** [comment]
shall we wrap this one up?

**Comment by clay-aptos** [comment]
> shall we wrap this one up?

Makes sense to me. All of these tutorials should be revisited. Please approve when you are ready. Thanks!

**Comment by davidiw** [comment]
Haha, you left this as draft

**Review by davidiw — APPROVED** [review]

**Comment by clay-aptos** [comment]
> Haha, you left this as draft

Only because I wasn't done. :-)

**Pull request merged**
