### PR TITLE
fix: updates tutorial to use authkey to fund accounts

### PR DESCRIPTION
**Pull request by gupnik**
## Motivation

I was going through the tutorials and realized that "Your First Move" doesn't work anymore.  

## Test Plan

Using authkey similar to "first_transaction.ts" fixes the issue.

### CODE REVIEW

**Review by davidiw — COMMENTED** [review]
Thank you! A better fix would be to update the entirety of the code to use .address() and address= in the faucet. Could you provide that?

Also could you provide a signed CLA (e-sign is okay!): https://github.com/aptos-labs/aptos-core/blob/main/documentation/contributing/individual-cla.pdf

**Comment by gupnik** [comment]
Thanks @davidiw. Just sent the cla via mail and updated the PR.

**Review by davidiw — COMMENTED** [review]
line 208 in first_transaction.ts should go from auth_key to address. Please test and verify.

**Comment by gupnik** [comment]
Added the change and verified that it runs successfully.

**Review by davidiw — APPROVED** [review]
awesome thank you!

**Pull request closed without merging**
