### PR TITLE
[api] Fix documentation around start field for account transactions

### PR DESCRIPTION
**Pull request by gregnazario**
### Description
Fixes the documentation related to the input variables

Closes https://github.com/aptos-labs/aptos-core/issues/4710

### CODE REVIEW

**Review by 0xmaayan — APPROVED** [review]
I assume we should also fix it here?
https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/aptos_client.ts#L483

**Comment by gregnazario** [comment]
> I assume we should also fix it here? https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/aptos_client.ts#L483

I didn't even realize this was commented here and not autogenerated.  Will fix.

**Review by bowenyang007 — APPROVED** [review]

**Comment by davidiw** [comment]
seems buggy

**Comment by gregnazario** [comment]
> seems buggy

Apparently, we put manual fixes into the generated code, I need to modify this commit

**Pull request merged**
