### PR TITLE
update rust to 1.62.1 and fix lint error

### PR DESCRIPTION
**Pull request by uvd**
### Description
update rust to 1.62.1 and fix lint error
### Test Plan

- [x] i'm upgrade rust 1.62  lint error get ,I will move macro_rules! monitor from     aptos-metrics-core  to consensus
```shell
macro_rules! monitor {
    ( $name:literal, $fn:expr ) => {{
        use crate::counters::OP_COUNTERS;
        let _timer = OP_COUNTERS.timer($name);
        let gauge = OP_COUNTERS.gauge(concat!($name, "_running"));
        gauge.inc();
        let result = $fn;
        gauge.dec();
        result
    }};
}


 crate::counters::OP_COUNTERS;
   |             ^^^^^ help: to reference the macro definition's crate, use: $crate
i‘m fix it  and get more err 



--> consensus/src/commitnotifier.rs:52:25
   |
52 |           if let Err(e) = monitor!(
   |  __^
53 | |             "notify_commit",
54 | |             timeout(
55 | |                 Duration::from_millis(self.quorum_store_commit_timeoutms),
...  |
58 | |             .await
59 | |         ) {
   | |__^ could not find counters in $crate
   |
   = note: this error originates in the macro monitor (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import $crate::counters
   --> consensus/src/epoch_manager.rs:363:9
    |
363 |         monitor!("reconfig", self.await_reconfig_notification().await);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find counters in $crate 
```

 

- [x]  and Another mistake is  this is may lint bug  ,Insertable and AsChangeset  You can't actually remove it because it's used, and i will fix add  #![allow(clippy::extra_unused_lifetimes)]

```shell
error: this lifetime isn't used in the impl
 --> ecosystem/indexer/src/models/collection.rs:7:45
  |
7 | #[derive(Associations, Debug, Identifiable, Insertable, Queryable, Serialize, Clone)]
  |                                             ^^^^^^^^^^
  |
  = note: `-D clippy::extra-unused-lifetimes` implied by `-D warnings`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes
  = note: this error originates in the derive macro `Insertable` (in Nightly builds, run with -Z macro-backtrace for more info)

error: this lifetime isn't used in the impl
 --> ecosystem/indexer/src/models/events.rs:8:45
  |
8 | #[derive(Associations, Debug, Identifiable, Insertable, Queryable, Serialize)]


error: this lifetime isn't used in the impl
 --> ecosystem/indexer/src/models/processor_statuses.rs:9:10
  |
9 | #[derive(AsChangeset, Debug, Insertable, Queryable)]
  |          ^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes
  = note: this error originates in the derive macro `AsChangeset` (in Nightly builds, run with -Z macro-backtrace for more info)
```

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2306)

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
thanks

**Review by davidiw — APPROVED** [review]

**Comment by davidiw** [comment]
@geekflyer "permission-check" isn't making progress and no visible reason why. I suspect it is because uvd doesn't have write permissions. Is there anything we can do here besides commandeering the change?

**Comment by bowenyang007** [comment]
Hey @uvd @davidiw so a bunch of generated files in aptos-protos got manually edited but this is not sustainable b/c every time we regenerate those protobuf this `Eq` addition will be wiped. Is there a better solution for this?

**Comment by uvd** [comment]
>i'm so sorry for it，You can turn off the Lint validation and then upgrade the generator program

**Comment by bowenyang007** [comment]
OK actually I just removed the package from the workspace and that did the trick :) https://github.com/aptos-labs/aptos-core/pull/3780

**Pull request merged**
