### PR TITLE
[Documentation] Added how to execute tests

### PR DESCRIPTION
**Pull request by magnum6actual**
The tutorial talks about tests here - but doesn't give any information on how to actually run the tests.

## Motivation

Just here to help.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yep.

## Test Plan

Read.

### CODE REVIEW

**Comment by magnum6actual** [comment]
Although, given the structure of the files and the fact that the Move CLI may or may not be installed as part of the standard dev package, more appropriate for the change to be simply:
```
cargo test
```
I would note that running `cargo test` after having run `cargo run sources` results in all kinds of errors related to CoreFramework and AptosFramework for reasons that I haven't taken the time to investigate.

**Comment by zekun000** [comment]
move-cli is good enough to run pure move unit tests, if the modules depend on the aptos-framework or core-framework, the tests may need to run like this https://github.com/aptos-labs/aptos-core/blob/b1601d23fb157fee4c4932cd093d3809be8094a4/aptos-move/framework/tests/move_unit_test.rs#L35 to plugin necessary native functions.

we probably should provide a aptos-move-cli for better developer experience.

**Comment by magnum6actual** [comment]
The run_tests_for_pkg has a dependency for move-cli, so that puts us back in the same situation on it not being part of the Aptos dev install. 

But 100% - an aptos-move-cli is essential.

**Comment by zekun000** [comment]
`run_tests_for_pkg` dependency is resolved via cargo, it doesn't require install of move-cli. cargo will automatically pull the dependency and build the tests.

**Pull request closed without merging**
