### PR TITLE
[GHA] Use versioned actions/checkout instead of pinning a commit

### PR DESCRIPTION
**Pull request by sionescu**
### Description

Trying to get rid of annoying warnings that "The `save-state` command is deprecated and will be disabled soon."

### CODE REVIEW

**Comment by banool** [comment]
Coming full circle hahah. So we pinned these in the first place to mitigate the risk of upstream security vulnerabilities coming from this actions. Could we just upgrade the pinned version?

**Comment by sionescu** [comment]
The upstreams here are Github, Google, Docker and NPM so I think it's safe to say that they have good security practices and we don't need to worry about vulnerabilities.
For marocchino/sticky-pull-request-comment, I can update the pin.

**Review by rustielin — APPROVED** [review]
I wonder what @gedigi thinks about it, so leaving one review. I'm ok with unpinning the commit hashes for "trusted" GH orgs like you said above ^ 

Do you know which actions are actually upgraded in this process btw @sionescu ?

**Review by gedigi — APPROVED** [review]

**Comment by gedigi** [comment]
I think that using hash values vs version numbers doesn't make us necessarily more secure, but possibly less secure. While it's true that there's a supply chain risk with bad code being pushed to a newer version of an action, it is more likely that a vulnerability is discovered in released code, and with a hash-based pin we wouldn't be automatically patched.

So for me +1 on this change.

**Comment by sionescu** [comment]
Then I'll go ahead and merge this. Each "unpin" is in its own commit so if something breaks we can revert only the offending change.

**Pull request merged**
