### PR TITLE
[documentation] fix MD link issue (#10870)

### LINKED ISSUE #10870: [Bug][Docgen] Anchors not working in the generated Aptos Framework documentation
# 🐛 Bug

The anchors in the generated Aptos Framework documentation don't work properly. 

## To reproduce

https://aptos.dev/reference/move/?branch=mainnet&branch=mainnet&page=aptos-framework/doc/account.md#0x1_account_increment_sequence_number

The link above leads to the page for the module `0x1::account`, but does not give a focus to the function `increment_sequence_number`. 

This makes it very hard to navigate the implementations (Move code) in the documentation through the links.

## Expected Behavior

The section for the function `increment_sequence_number` gets focused when clicking the link.

### PR DESCRIPTION
**Pull request by aalok-t**
### Description

Anchors in the markdown use anchor head of the form tag with the name attribute which has been deprecated. They have been replaced with `id`. This fixes #10870. 

### Test

Open the generated MD files locally on Firefox, Safari, and Chrome, and test the anchor.

### CODE REVIEW

**Review by rahxephon89 — APPROVED** [review]
LGTM, thanks @aalok-t . Btw, how do you verify your changes?

**Review by junkil-park — APPROVED** [review]
Nice!

**Comment by aalok-t** [comment]
> LGTM, thanks @aalok-t . Btw, how do you verify your changes?

I opened some of the generated MD files locally on Firefox, Safari, and Chrome and tested that the anchor worked. Not sure what else I could do to test/verify.

**Comment by rahxephon89** [comment]
> > LGTM, thanks @aalok-t . Btw, how do you verify your changes?
> 
> I opened some of the generated MD files locally on Firefox, Safari, and Chrome and tested that the anchor worked. Not sure what else I could do to test/verify.

That sounds good. Maybe you could add this to your PR description.

**Pull request merged**
