### PR TITLE
Full node tutorial docker update

### PR DESCRIPTION
**Pull request by fontm2**
## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

nothing

## Related PRs

nothing

## If targeting a release branch, please fill the below out as well

nothing

### CODE REVIEW

**Comment by sherry-x** [comment]
@fontm2 Thank you for submitting the improvement! Could you please sign the CLA doc? https://github.com/aptos-labs/aptos-core/blob/main/documentation/contributing/individual-cla.pdf

**Comment by fontm2** [comment]
Here is the document.

Thank you for providing the community with the astonishing move language
within the aptos framework!

Am Sa., 2. Apr. 2022 um 00:27 Uhr schrieb Sherry Xiao <
***@***.***>:

**Comment by sherry-x** [comment]
@fontm2 could you please email the sighed CLA doc to cla@aptoslabs.com? thanks!

**Review by sherry-x — APPROVED** [review]
Thank you!

**Pull request merged**
