### PR TITLE
[aptos-api-types] Allow Event to be forwards and backwards compatible

### PR DESCRIPTION
**Pull request by gregnazario**
### Description
This should allow Events to be parsed forwards and backwards.  Note we'll need to deprecate the original event key

### Test Plan
Unit tests, and ran the validator checker

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4170)

### CODE REVIEW

**Review by banool — APPROVED** [review]
itrustyoudog, but I'm not sure E2E tests is sufficient for this, since it got through CI in the first place. Have you done manual testing?

**Comment by gregnazario** [comment]
> itrustyoudog, but I'm not sure E2E tests is sufficient for this, since it got through CI in the first place. Have you done manual testing?

I'll make a test, just was in a bunch of meetings

**Review by igor-aptos — APPROVED** [review]

**Comment by igor-aptos** [comment]
If you want to check if this works, you can also call:

cargo run -p aptos -- node analyze-validator-performance --analyze-mode=all --url=https://ait3.aptosdev.com  --start-epoch=190 --end-epoch=195

this doesn't work on trunk now, but should work with your PR

**Comment by gregnazario** [comment]
> If you want to check if this works, you can also call:
> 
> cargo run -p aptos -- node analyze-validator-performance --analyze-mode=all --url=https://ait3.aptosdev.com --start-epoch=190 --end-epoch=195
> 
> this doesn't work on trunk now, but should work with your PR

Good callout, missed versioned events as well

**Pull request merged**
