### PR TITLE
[Docs] fix typos

### PR DESCRIPTION
**Pull request by vuittont60**

### CODE REVIEW

**Review by wrwg — APPROVED** [review]
Nice

**Review by davidiw — COMMENTED** [review]
Thanks for the PR. Unfortunately you're modifying generated files, you need to modify the original move file and then regenerate these files -- easy enough by running `cargo xclippy` in the root directory.

**Comment by wrwg** [comment]
> Thanks for the PR. Unfortunately you're modifying generated files, you need to modify the original move file and then regenerate these files -- easy enough by running `cargo xclippy` in the root directory.

The best way to ensure all things pass and all files are generated is `./scripts/rust_lint.sh`. Clippy alone does not do it. You would not have been able to pass the workflows without this.

**Comment by vuittont60** [comment]
@davidiw @wrwg Thank you for your reviews. 

When I run `cargo xclippy` or `./scripts/rust_lint.sh`, got the error:
   Compiling quote v1.0.29
error: linking with `cc` failed: exit status: 1
  = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.

How to resolve it?

**Comment by vuittont60** [comment]
I have modified the original move file. Please help me to review again. Thank you very much.

**Comment by wrwg** [comment]
> @davidiw @wrwg Thank you for your reviews.
> 
> When I run `cargo xclippy` or `./scripts/rust_lint.sh`, got the error: Compiling quote v1.0.29 error: linking with `cc` failed: exit status: 1 = note: collect2: fatal error: cannot find 'ld' compilation terminated.
> 
> How to resolve it?

This is a generic Rust question. I don't know your specific Rust setup but something seems to be broken. Rinstall Rust? Google for the error?

**Comment by davidiw** [comment]
You probably need to install the pre-reqs, have you seen this guide: https://aptos.dev/guides/building-from-source

**Comment by banool** [comment]
Looks good now, let's land it.

**Review by banool — APPROVED** [review]

**Review by davidiw — APPROVED** [review]

**Pull request merged**
