### PR TITLE
[storage] add cron job for backup compaction

### PR DESCRIPTION
**Pull request by areshand**
### Test Plan

locally test the command successfully finished

`aptos-db-tool backup-maintenance compact --state-snapshot-file-compact-factor 100 --transaction-file-compact-factor 100 --epoch-ending-file-compact-factor 100 --command-adapter-config ~/Downloads/s3-public.yaml
`

### CODE REVIEW

**Review by perryjrandall — APPROVED** [review]
Test plan?

Is there a way to create this from a cli instead of a helm template?

**Comment by areshand** [comment]
> Test plan?
> 
> Is there a way to create this from a cli instead of a helm template?
we locally tested the command
we plan to apply the change to GCP testnet first and confirm the deployment works as expected before rolling out.

**Comment by perryjrandall** [comment]
> > Test plan?
> > 
> > Is there a way to create this from a cli instead of a helm template?
> we locally tested the command
> we plan to apply the change to GCP testnet first and confirm the deployment works as expected before rolling out.

Can you please include the command you're running to test this locally?

**Comment by perryjrandall** [comment]
> > Test plan?
> > Is there a way to create this from a cli instead of a helm template?
> 
> we locally tested the command we plan to apply the change to GCP testnet first and confirm the deployment works as expected before rolling out.
> 
> This is a new chrons job. would be great if there is a way to do it through cli.

I see so you're not tested on testnet yet, best case for this is to helm apply to cluster

In future, its actually very easy to write csript to generate the script, then kubectl apply that

**Comment by rustielin** [comment]
I usually do some e2e test like deploy to a local (KinD) cluster. You can also do a template dry-run locally like this:

```
# pwd: terraform/helm/fullnode
$ helm template -s templates/backup-compaction.yaml . --debug 
```

**Review by rustielin — APPROVED** [review]

**Pull request merged**
