### PR TITLE
Update deprecated dependencies

### PR DESCRIPTION
**Pull request by gregnazario**
### Description
This removes the move cli `info` command, that prints out the dependency tree.  We don't really support the move CLI.

Additionally, updates some more dependencies so there's no longer a warning about deprecation in a future version.

### Test Plan
```
cargo build -p aptos
```

### CODE REVIEW

**Comment by davidiw** [comment]
Why are we removing the dependency graph generator? I couldn't follow the logic in the commit about being blocked by a future Rust update.

**Comment by gregnazario** [comment]
> Why are we removing the dependency graph generator? I couldn't follow the logic in the commit about being blocked by a future Rust update.

As far as I could tell it was not used anywhere.

We need to have a replacement for ptree because the author hasn't responded to the request for update prior.

We could fork the dependency and create our own branch for it as well.

**Review by davidiw — APPROVED** [review]
ptree is not actively maintained... approving

**Review by wrwg — CHANGES_REQUESTED** [review]
Unless there is a pressing reason, I suggest to lets have a discussion first about aptos-cli and move-cli relation. There are multiple options -- ranging from removing the move CLI, or moving some functionality from aptos CLI into move CLI (invisible to the user), so that aptos-move becomes an independent component (in third_party).

**Review by wrwg — APPROVED** [review]
See the point with `ptree`, but lets continue to discuss.

**Pull request merged**
