### PR TITLE
[CLI] Add support for running postgres in a container to the local testnet + rest of PRs in stack

### PR DESCRIPTION
**Pull request by banool**
## Stack
- Previous in stack: https://github.com/aptos-labs/aptos-core/pull/10252
- Next in stack: https://github.com/aptos-labs/aptos-core/pull/10254

## Description
This PR adds support for:
- Spinning up postgres in a container.
- Using postgres already running in the host system.

This is required to run indexer processors.

I still need to double check that this works on a fresh system, I have a suspicion that if postgres isn't installed things will fail with some error to the effect of "postgres shared library missing".

I also need to make sure I'm not reintroducing the OpenSSL dep.

This depends on https://github.com/aptos-labs/aptos-indexer-processors/pull/146.

Note: To avoid using undesired diesel features in the CLI I had to move the feature declarations from the workspace level to the crate level. Crate level feature declarations are additive, they don't replace the features used at the workspace level.

### Postgres in a container
```
cargo run -p aptos -- node run-local-testnet --assume-yes --force-restart --with-indexer-api --postgres-user dport
```
```
Node API is ready. Endpoint: http://0.0.0.0:8080/
Postgres is ready. Endpoint: postgres://dport@127.0.0.1:5433/local_testnet
Transaction stream is ready. Endpoint: http://0.0.0.0:50051/
Faucet is ready. Endpoint: http://127.0.0.1:8081/
```
```
psql postgres://dport@127.0.0.1:5433/local_testnet
```
```
psql (14.9 (Homebrew))
Type "help" for help.

local_testnet=# \dn
List of schemas
  Name  | Owner
--------+-------
 public | dport
(1 row)
```

Once the CLI shuts down so does the postgres container.

### Host postgres
```
cargo run -p aptos -- node run-local-testnet --assume-yes --force-restart --with-indexer-api --postgres-user dport --use-host-postgres
```
```
Postgres is ready. Endpoint: postgres://dport@127.0.0.1:5432/local_testnet
```
```
psql postgres://dport@127.0.0.1:5433/local_testnet
```
```
psql (14.9 (Homebrew))
Type "help" for help.

local_testnet=# \dn
List of schemas
  Name  | Owner
--------+-------
 public | dport
(1 row)
```

## Further Testing
Now that I've rebased all the other PRs in the stack into this PR, I will do some additional testing. I'm using this invocation:
```
cargo run -p aptos -- node run-local-testnet --assume-yes --force-restart --with-indexer-api
```

Does it work on:
- ARM MacOS: Yes!!
- x86 Ubuntu 22: Yes!!
- x86 Windows (host system, NT, MSVC): Not working, but due to an unrelated error that occurs on main too: https://gist.github.com/banool/135ce49c0662832446778c6268b68d62.
- x86 Windows (Ubuntu 22 WSL): Yes!!
- CLI running inside container from x86 Linux tools image running on ARM MacOS: Yes!!

For the last of these, I ran it like this:
```
DOCKER_DEFAULT_PLATFORM=linux/amd64 docker run -it -v /var/run/docker.sock:/var/run/docker.sock --network host aptos-core/tools:from-local aptos node run-local-testnet --with-indexer-api
```

### CODE REVIEW

**Review by gregnazario — APPROVED** [review]
lgtm, comments on CLI commands may be a little long.

keep in mind that the first line will show in `-h` and the rest of the lines will show in `--help`, I don't know what the cutoff is.

**Comment by banool** [comment]
Turns out diesel relies on pq-sys, which wraps libpq. It isn't acceptable to add this as a dep for the CLI, we have no way to ensure users have it installed and even if we did, it feels like an unnecessary dep for users who aren't using the local testnet / this feature of the local testnet.

I'm investigating alternatives here: https://aptos-org.slack.com/archives/C04PRP1K1FZ/p1696019475810529. Ultimately we'd have to stop using diesel...

**Comment by banool** [comment]
I switched to tokio-postgres. This solves it for this PR but the processors still use the mainline diesel postgres library, which uses libpg internally. To address this, I will make use of this branch for now in that PR: https://github.com/aptos-labs/aptos-indexer-processors/pull/146. We'll discuss whether we want to actually adopt this PR or if I have to use an alternative, like implementing diesel::Connection on https://github.com/sfackler/rust-postgres and using that.

**Review by davidiw — COMMENTED** [review]
what happens if you don't have docker installed?

**Comment by banool** [comment]
It tells you you don't have Docker installed and fails fast: https://github.com/aptos-labs/aptos-core/pull/10271/files#diff-860697684f8880833202701e67e2738c3cabf0655aaf9e53ea163877119ae885R155.

**Review by 0xjinn — APPROVED** [review]

**Review by larry-aptos — APPROVED** [review]

**Comment by banool** [comment]
See the further testing section, I just confirmed that the new features work on all major systems we support. It doesn't work on Windows (NT) but that has nothing to do with this PR (I'll chase that issue up separately).

**Comment by banool** [comment]
Landing this is currently blocked: https://aptos-org.slack.com/archives/C03N83P7QUC/p1691767293160939. I need to update the version of serde we use but doing so breaks some kind of old codegen / format gen we have.

**Comment by banool** [comment]
This change to Bollard means we can keep using the version of serde we're using now: https://github.com/fussybeaver/bollard/pull/343.

**Comment by banool** [comment]
I ran this test plan again and it all still works nicely with the Bollard change: https://github.com/aptos-labs/aptos-core/pull/10333. We should be good to go if all the other tests pass.

**Comment by banool** [comment]
I tested that the Docker stuff still works with this fork of Bollard, let's land.

**Pull request merged**
