### PR TITLE
[Community] Add coin::unfreeze_coin_store function to coin module

### LINKED ISSUE #3850: Ways To Improve Aptos Coin Module
I read through the Coin Module today, and I had the following thoughts:

Shouldn't the `freeze_coin_store<CoinType>` function have a corresponding `unfreeze_coin_store` function? Or better yet; we could combine them into one function that accepts a bool determining whether or not we want a CoinStore frozen. I'd think that if an authority can freeze your coins, they SHOULD be able to unfreeze them later on as well.

Also for the CoinStore, we could add the 'store' ability, which would allow CoinStores to be stored (wrapped) inside of other resources if we wanted. Someone might find that useful I imagine? Would adding this ability introduce some sort of vulnerability or concern?

Finally, Coin only has a simple transfer ability. On the other hand, ERC-20 tokens on Ethereum have an 'approval' concept built-in, which was terribly designed and ended up causing millions of dollars to be stolen tbh, but the use-case itself was a good one; what if I want to grant someone else the permission to transfer my tokens on my behalf? Modules using Coin can define their own sort of delegation system using `move_from<Coin<CoinType>>`, but it might be nice to have some sort of delegation-transfer standard built right into the Coin module itself, so that all coins can use it. Or do you think that would be too much of an application-specific use-case and introduce too much complexity into a core module?

### PR DESCRIPTION
**Pull request by PaulFidika**
### Description
Coin can now be unfrozen. I preferred the term 'unfreeze' to 'thaw' (like on Solana) because I thought it was simpler, but either function name works for me.

### Test Plan
I added a unit test in the coin.move module.

closes #3850

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4065)

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
thanks!

**Comment by davidiw** [comment]
@PaulFidika please run pre-commit or look at the lint issues: 


```
diff --git a/aptos-move/framework/aptos-framework/sources/coin.move b/aptos-move/framework/aptos-framework/sources/coin.move
index ec34d9c..ff016a9 100644
--- a/aptos-move/framework/aptos-framework/sources/coin.move
+++ b/aptos-move/framework/aptos-framework/sources/coin.move
@@ -810,7 +810,7 @@ module aptos_framework::coin {
         let account_addr = signer::address_of(&account);
         account::create_account_for_test(account_addr);
         let (burn_cap, freeze_cap, mint_cap) = initialize_and_register_fake_money(&account, 18, true);
-        
+
         let coins_minted = mint<FakeMoney>(100, &mint_cap);
         freeze_coin_store(account_addr, &freeze_cap);
         unfreeze_coin_store(account_addr, &freeze_cap);
diff --git a/aptos-move/framework/aptos-framework/sources/reconfiguration.move b/aptos-move/framework/aptos-framework/sources/reconfiguration.move
index 41502bd..aa38[96](https://github.com/aptos-labs/aptos-core/runs/8286835606?check_suite_focus=true#step:5:101)2 [100](https://github.com/aptos-labs/aptos-core/runs/8286835606?check_suite_focus=true#step:5:105)644
--- a/aptos-move/framework/aptos-framework/sources/reconfiguration.move
+++ b/aptos-move/framework/aptos-framework/sources/reconfiguration.move
@@ -36,7 +36,7 @@ module aptos_framework::reconfiguration {
         events: event::EventHandle<NewEpochEvent>,
     }
 
-    /// Reconfiguration will be disabled if this resource is published under the 
+    /// Reconfiguration will be disabled if this resource is published under the
     /// aptos_framework system address
     struct DisableReconfiguration has key {}
     ```

**Comment by PaulFidika** [comment]
> @PaulFidika please run pre-commit or look at the lint issues:
> 
> ```
> diff --git a/aptos-move/framework/aptos-framework/sources/coin.move b/aptos-move/framework/aptos-framework/sources/coin.move
> index ec34d9c..ff016a9 100644
> --- a/aptos-move/framework/aptos-framework/sources/coin.move
> +++ b/aptos-move/framework/aptos-framework/sources/coin.move
> @@ -810,7 +810,7 @@ module aptos_framework::coin {
>          let account_addr = signer::address_of(&account);
>          account::create_account_for_test(account_addr);
>          let (burn_cap, freeze_cap, mint_cap) = initialize_and_register_fake_money(&account, 18, true);
> -        
> +
>          let coins_minted = mint<FakeMoney>(100, &mint_cap);
>          freeze_coin_store(account_addr, &freeze_cap);
>          unfreeze_coin_store(account_addr, &freeze_cap);
> diff --git a/aptos-move/framework/aptos-framework/sources/reconfiguration.move b/aptos-move/framework/aptos-framework/sources/reconfiguration.move
> index 41502bd..aa38[96](https://github.com/aptos-labs/aptos-core/runs/8286835606?check_suite_focus=true#step:5:101)2 [100](https://github.com/aptos-labs/aptos-core/runs/8286835606?check_suite_focus=true#step:5:105)644
> --- a/aptos-move/framework/aptos-framework/sources/reconfiguration.move
> +++ b/aptos-move/framework/aptos-framework/sources/reconfiguration.move
> @@ -36,7 +36,7 @@ module aptos_framework::reconfiguration {
>          events: event::EventHandle<NewEpochEvent>,
>      }
>  
> -    /// Reconfiguration will be disabled if this resource is published under the 
> +    /// Reconfiguration will be disabled if this resource is published under the
>      /// aptos_framework system address
>      struct DisableReconfiguration has key {}
>      ```
> ```

How do I do that? Sorry; I'm new here. So the issue is that my code is formatted correctly?

**Comment by davidiw** [comment]
install `pre-commit` and run it?

**Review by areshand — APPROVED** [review]

**Comment by davidiw** [comment]
do you have plans to return to this? otherwise I can pass it off to someone else to wrap up.

**Comment by PaulFidika** [comment]
> do you have plans to return to this? otherwise I can pass it off to someone else to wrap up.

sorry for not getting back to this sooner. I installed pre-commit and ran it. Did that work correctly? Thanks; I'll make this a standard workflow in the future.

**Comment by davidiw** [comment]
@PaulFidika issue persists...

**Comment by PaulFidika** [comment]
Okay now it's fixed!

**Pull request merged**
