### PR TITLE
[Indexer][API] avoid table item panics

### PR DESCRIPTION
**Pull request by bowenyang007**
### Description
Context: https://github.com/aptos-labs/aptos-core/pull/6245
This PR is part 2 / 2 that fixes the indexer

### Test Plan
Tested in local indexer
```cargo run -p aptos-node --features "indexer" --release -- -f ./fullnode_token.yaml | grep -E _processor```

### CODE REVIEW

**Review by msmouse — APPROVED** [review]
LGTM

**Review by davidiw — COMMENTED** [review]
where's the error logging?

**Comment by bowenyang007** [comment]
> where's the error logging?
Previous PR. We don't need logging in the table b/c we'll see it plain as day.

**Review by perryjrandall — APPROVED** [review]

**Comment by bowenyang007** [comment]
This is probably not needed anymore.

**Pull request closed without merging**
