### PR TITLE
[Community External Resource] Add Aptos Node monitoring tool

### PR DESCRIPTION
**Pull request by dylanschultzie**
### Description
We've open sourced our Aptos monitoring solution, utilizing [Rhino Stake's](https://github.com/RhinoStake/aptos_monitoring)'s Grafana dashboard.

Our monitoring and alert solution utilizes docker containers with [Prometheus](https://prometheus.io/), [Grafana](http://grafana.org/), [cAdvisor](https://github.com/google/cadvisor), [NodeExporter](https://github.com/prometheus/node_exporter), and alerting with [AlertManager](https://github.com/prometheus/alertmanager). Once you've added your nodes to the prometheus config, simply doing `docker compose up` will setup the full monitoring suite, and create 2 alarms that can notify via Discord, Slack, or Pagerduty.

The alarms check for 2 things:
- each node's node version is increasing
- the nodes themselves are reachable.

https://github.com/LavenderFive/aptos-monitoring

### CODE REVIEW

**Comment by dylanschultzie** [comment]
Screenshot 2023-03-10 at 9 21 19 AM

**Review by clay-aptos — APPROVED** [review]
Thanks, Dylan! This LGTM with some small changes I made in a direct commit here. I am adding Michelle for review and asking her and our experts to also take a look before I approve. Thanks!

**Comment by dylanschultzie** [comment]
@clay-aptos thanks! Those contributions weren't ours, but I appreciate the fixes regardless. 😅

**Review by michelle-aptos — APPROVED** [review]

**Review by clay-aptos — APPROVED** [review]
Thanks for your contribution!

**Review by saharct — APPROVED** [review]

**Pull request merged**
