### PR TITLE
[Mempool] Increase the maximum concurrent task for bounded executor

### PR DESCRIPTION
**Pull request by sitalkedia**
### Description

While running transaction emitter in AIT2, one thing we observed is that the REST APIs become the major bottleneck in transaction submission. Per REST endpoint, we are not able to submit more than ~250 transaction per second. Digging into it, figured that the reason for this is we limit the maximum outstanding transaction processing task to be 2 and given each transaction validation takes ~8 ms, we can only process ~250 TPS. Bumping up the max concurrent transaction processing backlog for mempool to 24. This change will hopefully help us achieve a higher TPS for upcoming AIT3.  This along with other changes I have in flight for the transaction emitter can help bump up the TPS for forge as well to 6.5K (https://github.com/aptos-labs/aptos-core/pull/2375).

### Test Plan

Ran forge with this change and can bump up the TPS to 6.5k (https://github.com/aptos-labs/aptos-core/pull/2375).

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2390)

### CODE REVIEW

**Review by zekun000 — COMMENTED** [review]
each validation takes 8ms seems way off to me, most likely in initiating new vm. we probably should support batch requests or reuse the vm. it can exhaust the cpu as well but hopefully only in fullnodes

**Review by zekun000 — COMMENTED** [review]
bump it beyond 16 (num of threads used in forge) should make big difference? since validation is blocking task

**Comment by bchocho** [comment]
Ah, this is really interesting. Do you have a before/after dashboard for the processing times?

**Comment by sitalkedia** [comment]
> each validation takes 8ms seems way off to me, most likely in initiating new vm. we probably should support batch requests or reuse the vm. it can exhaust the cpu as well but hopefully only in fullnodes

Each validation takes ~7ms - tinyurl.com/24mrpx97  and VM validation is half of it - tinyurl.com/29xdvlkw.  What do you mean by reusing the VM? I see that we are reusing the VM across validations - https://github.com/aptos-labs/aptos-core/blob/ed152f4d7da9a74395f5125966ce260821772569/vm-validator/src/vm_validator.rs#L75.

**Comment by sitalkedia** [comment]
> Ah, this is really interesting. Do you have a before/after dashboard for the processing times?

I didn't find any counter for this but my log lines shows around 100x improvement in txn submission latency.

**Comment by zekun000** [comment]
validation a transaction shouldn't take 8ms, it's way off than what we expected. executing a transaction takes <1ms after first txn.

we do have counters for the processing time http://mon.devnet.aptoslabs.com/grafana/d/mempool/mempool?orgId=1&var-Datasource=Prometheus&var-namespace=default&var-chain_name=&var-kubernetes_pod_name=All&var-role=All&var-interval=$__auto_interval_interval&viewPanel=52

**Comment by zekun000** [comment]
took a closer look, so it's the broadcasted transaction batch takes 8ms to validate, not individual transaction sent by clients

**Comment by sitalkedia** [comment]
@zekun000 - Updated the concurrency to be 4 as default as discussed offline - we can increase this separately for FNs to bump up the transaction submission rate for AIT3 if needed.

**Review by zekun000 — APPROVED** [review]

**Pull request merged**
