### PR TITLE
Add definitions for popular terms to Aptos Glossary

### PR DESCRIPTION
**Pull request by Love01**
Glossary of terms in Aptos. It defines and explains the acronyms and terms used in the Aptos blockchain and its ecosystem.

### CODE REVIEW

**Comment by clay-aptos** [comment]
Thank you so much! Will review shortly.

**Review by davidiw — COMMENTED** [review]
I'll leave this to @clay-aptos to facilitate, but I might suggest merging with the doc site glossary: https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/docs/reference/glossary.md

If it makes sense, we could link to it from https://github.com/aptos-labs/aptos-core/blob/main/README.md

**Comment by Love01** [comment]
My pleasure. Glad to have. I've now merged the entries into the existing glossary.

**Review by clay-aptos — CHANGES_REQUESTED** [review]
Thanks so much for this contribution. This LGTM with some changes I made directly. Please also remove the redundant Glossary.md file in the root of the repo too. Thanks again!

**Comment by Love01** [comment]
Done. Thank you!

**Comment by clay-aptos** [comment]
> Thanks so much for this contribution. This LGTM with some changes I made directly. Please also remove the redundant Glossary.md file in the root of the repo too. Thanks again!



> Done. Thank you!

Hmm, I still see the file. You can remove it at the command line with:

```
cd aptos-core
git rm 

```

> Done. Thank you!

Hmm I still see it. You can delete it with:


```
cd aptos-core 
git rm Glossary.md
git commit 
git push
```

Let me know if you need help. Thanks!

**Review by clay-aptos — APPROVED** [review]
I believe this is all set to go. Asking Greg to take another look. Thanks again, Love!

**Comment by clay-aptos** [comment]
> I'll leave this to @clay-aptos to facilitate, but I might suggest merging with the doc site glossary: https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/docs/reference/glossary.md
> 
> If it makes sense, we could link to it from https://github.com/aptos-labs/aptos-core/blob/main/README.md

This is now done.

**Review by saharct — APPROVED** [review]

**Comment by gregnazario** [comment]
Looks good to me, we might have to add some of these words to spellcheck.  If @saharct can you help with this?

**Comment by clay-aptos** [comment]
> Looks good to me, we might have to add some of these words to spellcheck. If @saharct can you help with this?

I am taking care of this in:
https://github.com/aptos-labs/aptos-core/pull/7526

Please take a look. Thanks @gregnazario !

**Pull request merged**
