### PR TITLE
[indexer-docs] Add custom indexer processor tutorial + some minor edits

### PR DESCRIPTION
**Pull request by banool**
Addresses part of https://github.com/aptos-labs/aptos-core/issues/9758.

### CODE REVIEW

**Comment by banool** [comment]
This PR is on hold. When we release the Python custom processor stuff as its own package we'll revisit this. More info: https://aptos-org.slack.com/archives/C057CMMRLKT/p1692877496467279.

**Comment by davidiw** [comment]
I think this is dupes?

**Comment by banool** [comment]
Nah this one is fresh and novel and unique and special.

**Comment by banool** [comment]
Given that we still don't have an custom processor SDK I think we should just land this doc. It's possible that it is out of date now though, so @0xjinn has generously offered to run through this guide and find any issues with it.

**Review by 0xjinn — APPROVED** [review]

**Comment by banool** [comment]
Docs PR, I'm just merging.

**Pull request merged**
