### PR TITLE
Updated instructions

### PR DESCRIPTION
**Pull request by sirouk**
I added the Chrome Web Store extension page, instructions for installation, and also a note about restoring an existing Aptos wallet account.

### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3252)

### CODE REVIEW

**Comment by sirouk** [comment]
@banool

**Comment by sirouk** [comment]
@kent-white

**Review by gregnazario — APPROVED** [review]
Thanks for doing this!  Looks like it should help others :)

**Comment by kent-white** [comment]
@sirouk I will land this once the latest chrome build updates. Thanks a ton for this!

**Pull request merged**
