### PR TITLE
Update TestCoin.move

### PR DESCRIPTION
**Pull request by magnum6actual**
No reason for 'transfer' to own the 'from' signer. Should be &signer.  

## Motivation

Any function calling transfer loses ownership of the signer, inhibiting further uses.  One call call 'withdraw' and then a subsequent 'deposit' with only a reference to the signer - no reason not to just have a reference in transfer.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Transfer unit test was updated to reflect proposed change.

### CODE REVIEW

**Comment by magnum6actual** [comment]
One other thing on this - I don't know if there is other code that calls TestCoin::transfer, but I suspect this could be a breaking change.

**Comment by sitalkedia** [comment]
@magnum6actual - Thanks for the PR.

**Comment by sitalkedia** [comment]
@magnum6actual  - There are few test failures. Can you take a look at fixing them?

**Comment by magnum6actual** [comment]
Fixed the test issue in the last commit. Added a 'transfer_internal' so transfer can be called from script or from a move module by reference to the signer.

**Comment by zekun000** [comment]
need to update the build artifacts by running `cargo run -- --package aptos-framework` in aptos-move/framework

**Comment by davidiw** [comment]
Awesome PR, please merge the commits into a single commit and run the command as @zekun000 suggested. We're gonna do a branch cut soon. Let me know if you'd like me to throw this together really quickly for that.

**Comment by davidiw** [comment]
@magnum6actual , I had thought you had already submitted a PR and gone through our CLA: https://github.com/aptos-labs/aptos-core/blob/main/documentation/contributing/individual-cla.pdf

Could you fill that out and send it over? You can use an electronic signature app if you like. Then let's get this landed!

**Comment by magnum6actual** [comment]
CLA complete and emailed.

**Comment by davidiw** [comment]
Ugh, conflicts, you know, I think this PR will need to be rebased once this lands: https://github.com/aptos-labs/aptos-core/pull/352
and then we may even need to update the goldens.

`cd aptos-core/api &&  env REGENERATE_GOLDENFILES=1 cargo test`
I can poke this PR one that lands.

I really wish github gave us the ability to amend PRs to help funnel them through.

**Comment by magnum6actual** [comment]
Yeah, I really have no idea what I'm doing at this point (and you guys thought I was kidding when I said I wasn't really a developer). Git and I have never been friends.  May be easier to whack this one and let me submit a fresh PR.

**Comment by gregnazario** [comment]
@magnum6actual If you're having trouble with it I can help you rebase it

**Comment by magnum6actual** [comment]
> @magnum6actual If you're having trouble with it I can help you rebase it

Please do!

**Comment by gregnazario** [comment]
Closing this PR, replacing it with https://github.com/aptos-labs/aptos-core/pull/355

**Pull request closed without merging**
