### PR TITLE
[smart_vec] vector of big_vec is not necessary

### PR DESCRIPTION
**Pull request by lightmark**
### Description
I think I made a mistake that "`Option` cannot be used here".
Previously I used a `vector` with an invariant that the length is always 1 to to represent an option. But actually we can just use option here.
If possible I wanna cherry-pick v1.3... since it can preclude some potential bugs.

### Test Plan
ut

### CODE REVIEW

**Review by davidiw — CHANGES_REQUESTED** [review]
Agreed with the goal. Though this is a breaking change for something in the framework, please raise an issue in #gatekeepers in slack to make progress.

**Review by movekevin — COMMENTED** [review]
Please add more context/details in the PR's desc.

**Comment by lightmark** [comment]
> Please add more context/details in the PR's desc.

done

**Comment by gerben-stavenga** [comment]
using option means one extra level of indirection which cost more gas. Given that this is a foundational structure we could argue that we should be implementing this as low level as possible

**Comment by lightmark** [comment]
> using option means one extra level of indirection which cost more gas. Given that this is a foundational structure we could argue that we should be implementing this as low level as possible

I am sort of disagreeing with this because the execution gas is already 100x lower and the perf hit of this change is almost negligible. If the change causes significant gas or we are charging execution comparable to ethereum, I would agree with you. Also, `Option` is in std-lib and I believe it can be optimized later natively with the same interface. However, changing struct fields is not backwards compatible.

**Review by wrwg — APPROVED** [review]

**Review by zekun000 — APPROVED** [review]

**Comment by lightmark** [comment]
@davidiw please stamp this one and https://github.com/aptos-labs/aptos-core/pull/6987

**Comment by lightmark** [comment]
@davidiw @davidiw @davidiw @davidiw @davidiw @davidiw @davidiw @davidiw @davidiw @davidiw

**Review by davidiw — APPROVED** [review]
Let's make sure we uphold the expectations on pre-cut breaking changes 😉

**Pull request merged**
