### PR TITLE
[AIP-57] Fix recalibration from #11342

### PR DESCRIPTION
**Pull request by igor-aptos**
Fix recalibration from #11342

- fix event_ and table common_load_ recalibration being applied correctly
- adjust read ratio between per-item and per-byte
- separate intrinsic base and per-byte costs in calibration

Produced multipliers:
```
intrinsic_fixed * 1.8403997
intrinsic_size * 0.5791066
execution * 0.18386576
io_read_per_item * 0.377981465
io_read_per_byte * 1.51192586
io_write * 0.89568503
```

Produces significantly better calibration:
`max_after=13535, min_after=4901, ratio: 2.7616812895327483`

(compared to original:
```
max_before=64841, min_before=4253, ratio: 15.245944039501529
max_after=17755, min_after=3995, ratio: 4.444305381727159
```
)

with full comparison table:

```
name                                                                         before gas/s  optimized gas/s  before gas/txn  after gas/txn  
entry_point_Nop                                                              4449          8181             2               3              
entry_point_BytesMakeOrChange { data_length: Some(32) }                      6084          7712             3               4              
entry_point_StepDst                                                          9354          10065            4               5              
entry_point_Loop { loop_count: Some(100000), loop_type: NoOp }               64841         11990            2402            445            
entry_point_Loop { loop_count: Some(10000), loop_type: Arithmetic }          57795         10736            1314            244            
entry_point_CreateObjects { num_objects: 10, object_payload_size: 0 }        10365         5177             16              8             
entry_point_CreateObjects { num_objects: 10, object_payload_size: 10240 }    55053         11544            535             113            
entry_point_CreateObjects { num_objects: 100, object_payload_size: 0 }       13125         4901             142             53             
entry_point_CreateObjects { num_objects: 100, object_payload_size: 10240 }   38990         12140            907             283            
entry_point_InitializeVectorPicture { length: 40 }                           10848         7020             7               5              
entry_point_VectorPicture { length: 40 }                                     11869         13535            5               5              
entry_point_VectorPictureRead { length: 40 }                                 11792         13430            5               5              
entry_point_InitializeVectorPicture { length: 30720 }                        43554         8299             1452            277            
entry_point_VectorPicture { length: 30720 }                                  5375          6906             32              41             
entry_point_VectorPictureRead { length: 30720 }                              4253          6143             23              33             
entry_point_SmartTablePicture { length: 30720, num_points_per_txn: 200 }     35880         6716             1631            306            
entry_point_SmartTablePicture { length: 1048576, num_points_per_txn: 1024 }  35947         6646             11983           2216           
entry_point_TokenV1MintAndTransferFT                                         37832         13040            29              10            
entry_point_TokenV1MintAndTransferNFTSequential                              38219         10434            40              11             
Transfer                                                                     13039         10226            7               6              
CreateAccount                                                                10291         6243             7               4              
PublishModule                                                                9645          10104            70              74             

```

### CODE REVIEW

**Comment by igor-aptos** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11548?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #11345** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11345?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #11547** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11547?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #11548** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11548?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #11537** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11537?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #11240** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11240?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #11541** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11541?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #11542** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11542?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #11538** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11538?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #11438** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11438?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #11439** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11439?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #11312** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11312?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #11323** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11323?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #11340** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11340?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #11346** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11346?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11548?utm_source=stack-comment).

**Review by grao1991 — APPROVED** [review]

**Comment by msmouse** [comment]
Was there an actual issue with table read parameters overriding?

**Comment by vgao1996** [comment]
> Was there an actual issue with table read parameters overriding?

Not totally clear to me. For now, @igor-aptos can you manually check the values and make sure they are consistent?

**Comment by igor-aptos** [comment]
yes, I set the values to match

**Pull request merged**
