### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by Kabie**
I noticed there are many places have `25519` misspelled.

### CODE REVIEW

**Comment by davidiw** [comment]
haha, great find. I didn't see a signed cla, could you please do so and I'd be happy to land these: https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#contributor-license-agreement

you can use any e-signing software you like.

**Review by davidiw — APPROVED** [review]

**Comment by gregnazario** [comment]
@davidiw this PR was blocking up the CICD, we'll have to figure out why later.

**Comment by davidiw** [comment]
shall we try this again?

/land

**Pull request merged**
