### PR TITLE
[RestApi] supports querying resource groups by type

### PR DESCRIPTION
**Pull request by msmouse**

### CODE REVIEW

**Comment by runtian-zhou** [comment]
Thank you!

**Comment by msmouse** [comment]
@davidiw @gregnazario  @wrwg  are we good with this bcs only "back door" to expose the btreemap?

**Review by davidiw — COMMENTED** [review]
I'm "okay" with this and will follow if @gregnazario or @banool weigh in

**Review by wrwg — APPROVED** [review]

**Comment by msmouse** [comment]
sent this instead https://github.com/aptos-labs/aptos-core/pull/8142

**Pull request closed without merging**
