### PR TITLE
Make api::TransactionInfo fields right

### PR DESCRIPTION
**Pull request by msmouse**
### Description

* rename "state_root_hash" -> "state_change_hash"
* add "state_checkpoint_hash: Option<HashValue>"

### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3189)

### CODE REVIEW

**Comment by msmouse** [comment]
Sorry, now I think it's sorta nice to be able to confirm history summarizes to the same hash between nodes at any given version. And assuming it'll be in the end served from a dedicated API / Indexer service, performance implication doesn't seem concerning.

Will update accordingly.

**Comment by msmouse** [comment]
And done.

**Review by zekun000 — APPROVED** [review]

**Comment by msmouse** [comment]
@bowenyang007  kindly help me change the protos? ❤️

**Comment by msmouse** [comment]
Indexer tests work locally but not on CI, help @bowenyang007  @CapCap ?

**Pull request merged**
