### PR TITLE
[ecosystem] Update nft-nyc flow to actually mint the NFT.

### PR DESCRIPTION
**Pull request by zacharydenton**
### Description

https://user-images.githubusercontent.com/310773/173145942-60c9ec3f-83a2-4eca-85eb-a19c98ebf15b.mp4

### Test Plan
Manual

### CODE REVIEW

**Comment by CapCap** [comment]
image
^ should the the div around the logo be transparent here?

**Comment by zacharydenton** [comment]
Looks like your CSS is out of date. Are you running with `bin/dev` (which also starts the tailwind compiler)? It should look more like this:

localhost_3001_nft_offers_1

**Comment by zacharydenton** [comment]
PTAL

**Review by CapCap — APPROVED** [review]

**Pull request closed without merging**
