### PR TITLE
ChunkExecutor: skip checking transaction signatures

### PR DESCRIPTION
**Pull request by msmouse**
## Description

The transactions are already verified to be part of the chain by the proofs on the list.

## Type of Change
- [x] Refactoring

## Which Components or Systems Does This Change Impact?
- [x] Validator Node -- state sync

## How Has This Been Tested?

existing unit tests

### CODE REVIEW

**Review by grao1991 — APPROVED** [review]

**Comment by msmouse** [comment]
@JoshLind  @sitalkedia  do you have a concern skipping the sig checks here? The entire chunk is verified against validator signatures, I'm not sure it's necessary to check individual sigs on the transactions..

**Comment by sitalkedia** [comment]
I remember we had this conversation earlier in one of my PRs and @JoshLind had a concern around skipping the signature check in FNs - the idea was the FNs would want to validate the signature to detect cases where validators collude to commit invalid transactions on-chain. May be it makes sense to make it a configuration flag and disable signature check bydefault and paranoid FNs can still enable it.

**Comment by JoshLind** [comment]
Yeah, the original thinking was that it makes sense to keep this for folks who want to reverify as much of the blockchain history as possible. Perhaps a config (like @sitalkedia suggests) is the best option? Default to false, but folks can turn it back on if they want? 😄

**Comment by msmouse** [comment]
In that case checking them only in the execution mode seems proper (as is the case currently).

Making it configurable seems over-complication. I'd do it like today, or defer the "full verification" to other tooling (replay-verify).

**Pull request closed without merging**
