### PR TITLE
[Compiler-v2] run `move_pr.sh -2` in CI

### LINKED ISSUE #13750: [Feature Request] run third_party/move/scripts/move_pr.sh -ti2 for any compiler change
# 🚀 Feature Request

Add `third_party/move/scripts/move_pr.sh -ti2` to the script run after any compiler change.

## Motivation

This script catches more regressions, including those in Move Compiler v2.

We already see a case of this.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Description

This PR adds execution of the script `move_pr.sh -2` to CI. 

close #13750 

## Key Areas to Review

 1) need to check updated docs and exp files;
 2) whether the script execution is flaky.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [x] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Move Compiler
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by brmataptos — COMMENTED** [review]
I have some slight concerns that using both `-i` and `-2` in the same run leads to more limited exercise of framework compilation with `MOVE_COMPILER_V2` enabled, since we don't do a `cargo clean` between the two runs.  Just FYI.

**Review by brmataptos — APPROVED** [review]
Something is better than nothing.

**Comment by rahxephon89** [comment]
> I have some slight concerns that using both `-i` and `-2` in the same run leads to more limited exercise of framework compilation with `MOVE_COMPILER_V2` enabled, since we don't do a `cargo clean` between the two runs. Just FYI.

Any suggestion on how to set the flag, e.g, just using `-2`? @brmataptos

**Comment by brmataptos** [comment]
If I really want clean results,  I use 2 runs, one with `-i`,  one with `-2`.  We might change the script, e.g., to run `cargo clean -p aptos-framework`, in between the two steps.  Or maybe my fears are overblown and we can just leave it.  Just something to look out for.

**Comment by rahxephon89** [comment]
@vineethk @brmataptos I removed the flag `-i` since it is for testing compiler v1.

**Comment by brmataptos** [comment]
Assuming that we're testing move-compiler-v2 in some other script, sounds fine.

**Pull request merged**
