### PR TITLE
[sdk] Add RawTransaction to openapi schema

### PR DESCRIPTION
**Pull request by jjleng**
## Motivation

Add RawTransaction schema to openapi

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Previewed the the new schema in swagger viewer.
Screen Shot 2022-05-14 at 6 44 41 PM

### CODE REVIEW

**Review by davidiw — COMMENTED** [review]
It isn't clear to me why we need this API?

**Comment by jjleng** [comment]
That's actually my question :) https://github.com/aptos-labs/aptos-core/issues/884

**Comment by jjleng** [comment]
Don't you want to sign the raw transaction on the SDK side?

**Comment by davidiw** [comment]
> Don't you want to sign the raw transaction on the SDK side?

and generate it there too.

**Comment by davidiw** [comment]
Maybe you're just leveraging the openapi spec to help create an interface that won't actually be used by the rest endpoint?

**Comment by jjleng** [comment]
> Maybe you're just leveraging the openapi spec to help create an interface that won't actually be used by the rest endpoint?

Exactly. Only the type, no rest endpoint.

**Review by davidiw — COMMENTED** [review]
Let's think about the goals for sdks and code generation and circle back here. We also have the transaction-generator-builder.

**Comment by jjleng** [comment]
With Ethereum, people can generate ABI for smart contracts. There is a web3.js, which is akin to our sdk that interacts with web wallet and the generated ABI. 

We can discuss if we want to have the ABI type of code gen in SDK. But this openspec codegen for types is not necessary.

**Comment by davidiw** [comment]
Even if we add this here, this doesn't really help us generate the interfaces. We'll need a different tool, I'm in favor of closing this out and thinking about another tool.

**Comment by jjleng** [comment]
This is not needed

**Pull request closed without merging**
