### PR TITLE
[deps] Upgrade minor dependencies and make most consistent

### PR DESCRIPTION
**Pull request by gregnazario**
## Motivation

Our dependencies were really lagging and inconsistent, so I've updated them all to be the latest versions and consistent among all the many crates.

These are the ones that didn't require extra work to upgrade.  Those are:
* futures
* tokio
* digest
* sha-2

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Unit tests

### CODE REVIEW

**Comment by JoshLind** [comment]
Thanks @gregnazario! Looks pretty reasonable to me 😄 I'll wait for the build/tests to run. If they look good, we should be good to go. Only question: do we want to squash all the commits into a single one? I wonder how 50 individual commits would look in the git history? 😆

**Comment by gregnazario** [comment]
> Thanks @gregnazario! Looks pretty reasonable to me 😄 I'll wait for the build/tests to run. If they look good, we should be good to go. Only question: do we want to squash all the commits into a single one? I wonder how 50 individual commits would look in the git history? 😆

I mean I can squash them, I just didn't want them to be one giant commit, but that's personal preference.  Each one is atomic

**Review by JoshLind — APPROVED** [review]
LGTM!

**Pull request merged**
