### PR TITLE
[Documentation] Sidebar item titlecase fixes and a few other misc. fixes.

### PR DESCRIPTION
**Pull request by rajkaramchedu**
This PR makes the following changes:

1. "Application Tutorials" has inconsistent capitalization in many of the titles F or f for first.
2. Moved "Wallet Extension" to "Guides" (currently under "Application Tutorials").
3. Moved Node liveness criteria doc to Incentivized Testnet Docs
4. Changed the title "Local Testnet, Devnet and Incentivized Testnet" to "Aptos Blockchain Deployments"

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
/land

thank you!!!!

**Comment by davidiw** [comment]
I think @geekflyer added a `yarn lint` command and this PR failed that check. Please check this out.

**Comment by geekflyer** [comment]
yeah I've added some auto formatting for the docs code. You have to install nodejs and then run `yarn fmt` in the docs directory to get things auto-formatted. If you use VS Code to edit the code, I'd also recommend to install the `prettier` plugin which will take care of that for you.

If you don't have nodejs installed this command will take care of you:

```
brew install fnm && fnm install 16.14.0 && fnm default 16.14.0 && cd developer-docs-site && yarn fmt`
```

**Comment by rajkaramchedu** [comment]
Okay, ran the `yarn fmt` command and it fixed indenting issue with the `sidebars.js` file.

**Pull request closed without merging**
