### PR TITLE
add words for 4-fetch-data-from-chain.md

### LINKED ISSUE #6933: silence linter errors "4-fetch-data-from-chain.md"
## Status 

* linter signals errors

https://github.com/aptos-labs/aptos-core/actions/runs/4337586660/jobs/7573690857

```
Mispelled words in docs/tutorials/build-e2e-dapp/4-fetch-data-from-chain.md:
useEffect
fetchList
const
accountHasList
setAccountHasList
useState
```

## Expected

* silence the linter errors

## Reproduction

- #6931 
- #6932

### PR DESCRIPTION
**Pull request by abebeos**
closes #6933

### Test Plan

ci

### CODE REVIEW

**Comment by davidiw** [comment]
fixing here: https://github.com/aptos-labs/aptos-core/pull/6935

**Comment by abebeos** [comment]
@davidiw , i do not understand what happened here with the pr.

Additionally, i do not understand the commit message "pulled in an incomplete change " 

You additional modification to the md file looks unrelated to me.

(just need to understand the process here)

**Comment by davidiw** [comment]
There was a previous PR that made it through that had caused issues: https://github.com/aptos-labs/aptos-core/pull/6563

I cleaned them all up in an ensuing PR. Your proposed PR would only fix the spelling issues.

I appreciate the continued PRs from you!

**Comment by abebeos** [comment]
> (i can take a look at this,

@davidiw , quick lookup shows that "github markdown inline code coloring" is currently not possible.

**Comment by davidiw** [comment]
> > Your proposed PR would only fix the spelling issues.
> 
> I believe that this would be the way to go (dedicated issues is fixed by dedicated PR, preserving authorship and issue/PR workflow)
> 
> > I cleaned them all up in an ensuing PR.
> 
> Please note that your introduction-of/change-of the `` ```jsx `` inline code formatting tag does not work.
> 
> It renders as e.g.: `jsx import useEffect from "react"`
> 
> (i can take a look at this, i noticed that you are active on core-stuff/move, you should not distract yourself with annoying doc stuff)
> 
> ## Dev Process
> Why is the PR review not enforced here on this repo?

Thanks for the feedback. There was a single PR that had created other issues. Clearly even after the above PR, there are still issues due to inline markdown. Rather than leave the site in a bad state, the PR were sent to address that issue. Agree with the thoughts and process.

**Comment by clay-aptos** [comment]
> useEffect from

@abebeos , are you referring to this lines?

```
3. Next, we want to fetch the account’s TodoList resource.
   Begin by importing `useEffect` by using ```jsx import useEffect from "react"; ```
   Let’s add a `useEffect` hook to our file that would call a function to fetch the resource whenever our account address changes:
```

And you are saying that should read as:

```
3. Next, we want to fetch the account’s TodoList resource.
   Begin by importing `useEffect` by using `import useEffect from "react"; `
   Let’s add a `useEffect` hook to our file that would call a function to fetch the resource whenever our account address changes:
```

I don't see that diff in David's change though. Please help me understand what is going on. Thanks!

**Comment by abebeos** [comment]
> I don't see that diff in David's change though. Please help me understand what is going on. Thanks!

All good, it is corrected here https://github.com/aptos-labs/aptos-core/pull/6939/files

(the code coloring tags do not work inline, as one would expect...)

**Pull request closed without merging**
