### PR TITLE
[cleanup][indexer] Clean up unused protos and add new proto for grpc

### PR DESCRIPTION
**Pull request by larry-aptos**
### Description
* Cleaning up the streamingfast unused protos. 
* Adding/building a new proto for our upcoming work on indexer.

### CODE REVIEW

**Review by bowenyang007 — APPROVED** [review]

**Review by 0xmaayan — APPROVED** [review]

**Comment by larry-aptos** [comment]
> I can see this PR removes the `extractor.proto`. However, this is what we currently use in our Streaming fast indexer which utilises Firehose. Is there a documentation explaining the reasons behind this so we can determine what future holds for our indexer?

We'll add `extractor.proto` back soon. @bowenyang007 is working on this.

**Comment by ppoliani** [comment]
@bowenyang007 thank you for the clarification. Does it mean that [this](https://github.com/aptos-labs/aptos-core/blob/30b385bf38d3dc8c4e8ee0ff045bc5d0d2f67a85/config/src/config/firehose_streamer_config.rs#L8) config will also become obsolete?

I'm currently running this[ firehose-enabled node ](https://github.com/streamingfast/firehose-aptos). Should I expect that future versions of the Aptos node will not work with that code?

**Comment by YaroShkvorets** [comment]
So is `extractor.proto` coming back?

**Comment by bowenyang007** [comment]
> So is `extractor.proto` coming back?

Unfortunately it's not.

**Pull request merged**
