### PR TITLE
[forge] remove direct eks cluster scaling

### PR DESCRIPTION
**Pull request by rustielin**
Removes the EKS nodegroup scaling logic from Forge, instead relying on the autoscaling functionality of the cluster. This was introduced in #800 

From tests, the spin up time is roughly the same. We can also look into tuning the autoscaler params to bring up the cluster faster.

### CODE REVIEW

**Review by geekflyer — APPROVED** [review]

**Comment by davidiw** [comment]
Closing this out as it is over a month old. Kinda looks like it could still land 😭

**Comment by geekflyer** [comment]
@rustielin  can we still this land this? I like that it's deleting over 300 lines of (dead?) code and I might touch the very same code soon :-P

**Comment by rustielin** [comment]
@geekflyer i was hoping to spend more time to benchmark and tune the autoscaler configs. We could land it though we'd just need to keep an eye out on forge job time to see if there's regression

**Comment by geekflyer** [comment]
what exactly is there to tune? I'm fine just landing this and reverting it if we actually see a regression.
The github actions workers btw use the GKE k8s autoscaler and I haven't really seen any issues with regards to job time. The only thing that sometimes needs a bit tuning is the "when to scale down after the job has completed" question but that doesn't really affect job time in the case of forge and runs out of band.

**Comment by rustielin** [comment]
I'm mostly interested in the cluster scale down time. Exposed a few helm values to tune 

https://github.com/aptos-labs/aptos-core/blob/main/terraform/helm/k8s-metrics/values.yaml

But yea we can land this now and revert or tune as we see fit tbh

**Comment by geekflyer** [comment]
ok let's reopen and rebase this PR then

**Pull request closed without merging**
