### PR TITLE
[docs] Add Aptos CLI local testnet readme / guide

### PR DESCRIPTION
**Pull request by gregnazario**
### Description
Added a readme style guide for the local testnet.

TODO: Add a scenario based "I want to develop a module against a local testnet" guide.

### Test Plan
https://github.com/gregnazario/aptos-core/blob/cli-guides/developer-docs-site/docs/cli-tools/aptos-cli-tool/using-a-local-testnet.md
Docs docs docs

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2626)

### CODE REVIEW

**Review by rajkaramchedu — COMMENTED** [review]
Is this document a replacement for this existing document? https://aptos.dev/nodes/run-a-local-testnet or should we keep both to show two different ways of starting the local testnet?

**Review by wrwg — APPROVED** [review]
Awesome! Thank you

**Comment by wrwg** [comment]
> Is this document a replacement for this existing document? https://aptos.dev/nodes/run-a-local-testnet or should we keep both to show two different ways of starting the local testnet? Either way, the main utility of this doc is local testnet, we should move this out of the CLI section and put it in the Nodes section. I can take care of it. We should still decide on whether to keep only this document or keep both the docs. There is a story evolving here, start the local testnet and develop a module and test it in the local testnet. Ideal for system integrators guide.

Good point. I saw this doc first and it did not contain the info I was looking for (how to use the CLI to start and operate a local node). I think the documentation you are referring to should be updated and/or merged with the CLI doc.

IMHO, as the CLI is (and we will be more and more) the central hub for people interacting with Aptos and Move, we should make all docs use it more uniformly. This was indeed historically not possible as the CLI only incrementally evolves, and we needed docs before it was ready.

**Comment by rajkaramchedu** [comment]
> > Is this document a replacement for this existing document? https://aptos.dev/nodes/run-a-local-testnet or should we keep both to show two different ways of starting the local testnet? Either way, the main utility of this doc is local testnet, we should move this out of the CLI section and put it in the Nodes section. I can take care of it. We should still decide on whether to keep only this document or keep both the docs. There is a story evolving here, start the local testnet and develop a module and test it in the local testnet. Ideal for system integrators guide.
> 
> Good point. I saw this doc first and it did not contain the info I was looking for (how to use the CLI to start and operate a local node). I think the documentation you are referring to should be updated and/or merged with the CLI doc.
> 
> IMHO, as the CLI is (and will be more and more) the central hub for people interacting with Aptos and Move, we should make all docs use it more uniformly. This was indeed historically not possible as the CLI only incrementally evolves, and we needed docs before it was ready.

I agree. We should make the CLI as our swiss-army knife offering. I will wait for others to comment before merging the other doc into this CLI doc.

**Comment by gregnazario** [comment]
> > > Is this document a replacement for this existing document? https://aptos.dev/nodes/run-a-local-testnet or should we keep both to show two different ways of starting the local testnet? Either way, the main utility of this doc is local testnet, we should move this out of the CLI section and put it in the Nodes section. I can take care of it. We should still decide on whether to keep only this document or keep both the docs. There is a story evolving here, start the local testnet and develop a module and test it in the local testnet. Ideal for system integrators guide.
> > 
> > 
> > Good point. I saw this doc first and it did not contain the info I was looking for (how to use the CLI to start and operate a local node). I think the documentation you are referring to should be updated and/or merged with the CLI doc.
> > IMHO, as the CLI is (and will be more and more) the central hub for people interacting with Aptos and Move, we should make all docs use it more uniformly. This was indeed historically not possible as the CLI only incrementally evolves, and we needed docs before it was ready.
> 
> I agree. We should make the CLI as our swiss-army knife offering. I will wait for others to comment before merging the other doc into this CLI doc.

Yeah I rewrote it from scratch because it was about how you can also use the CLI to do tasks on the local testnet as well.  The docker version seems like it has added more confusion for people in general

**Comment by davidiw** [comment]
I think this is  good for now, but individual will not immediately head to the CLI and say let me understand the use cases. The guides and UX should be more about ... I have this goal and I want to solve it. Not I have this tool, what can I do with it. The former is better handled by dedicated CLI index. This isn't an easy problem.

**Pull request merged**
