### PR TITLE
[Parallel Execution] Fix module detection (again)

### PR DESCRIPTION
**Pull request by gelash**
Never write false, as that can overwrite a true value due to a concurrency race.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2916)

### CODE REVIEW

**Review by zekun000 — APPROVED** [review]

**Review by zekun000 — COMMENTED** [review]
how you’re going to test it?

**Comment by movekevin** [comment]
> how you’re going to test it?

Can we add an integration test for this in aptos-move/e2e-move-tests?

**Comment by gelash** [comment]
> how you’re going to test it?
I wish I knew, it gets progressively more difficult.

For the previous one, I want to add a fake executor test with configuration that'd caught the deadlock (as we talked about). And real executor block with real modules that you suggested.

For this one, it's actually super tricky (and scary), maybe the fake executor with proper combinatorial configuration would have caught it? But note to self to not rush to fix anything PE-related.

We had a lot of time to inspect the original PE code, that's why it's been pretty rock solid, and every next iteration we should be extra careful.

**Comment by gelash** [comment]
> > how you’re going to test it?
> 
> Can we add an integration test for this in aptos-move/e2e-move-tests?

We can also fix the Move-VM cache properly while we are at it.. not trying to be snarky, we should add those tests (and I'll think and add smt), but unfortunately it's pretty non-trivial to actually cause anything non-trivial to surface :( The best tool we have is the combinatorial fake executor which I should've done a better job to generate cases for module dependencies for the previous deadlock. This one, pretty hard to generate I'm afraid.
Fearless concurrency m* a** - it scares me every day.

**Comment by gelash** [comment]
@movekevin & @zekun000: we can have tests where we publish and read in consecutive txns, but some of which intersect and some of which don't (maybe most don't, or one intersection only), and check that we do fall back to sequential. This should catch the bad behavior here every once in a while - and we can run the test many times each time. For the deadlock need again 1 intersection somewhere far, overlapping with transactions with a lot of dependencies.

**Comment by gelash** [comment]
ask and we shall receive.
tests that catch both the deadlock, and the current problem in the deadlock fix 
https://github.com/aptos-labs/aptos-core/pull/2925

**Pull request merged**
