### PR TITLE
Announce Move tutorial, Multisig, and new External Resources

### PR DESCRIPTION
**Pull request by clay-aptos**
### Description

Also:
* Add Multisig to Community Highlights
* Rename ported tutorial as Move Primitives Tutorial
* Update link in Move Book to new tutorial

### Test Plan

Build and test at:
http://localhost:3000/

Or see the deploy preview link in check output:
https://deploy-preview-7308--aptos-developer-docs.netlify.app/whats-new-in-docs

### CODE REVIEW

**Comment by clay-aptos** [comment]
@alnoki , I am announcing your excellent multisig doc and adding it to the community highlights page here. Please let me know if you want me to also add a reference and link to Econia. Thanks!

**Comment by alnoki** [comment]
> @alnoki , I am announcing your excellent multisig doc and adding it to the community highlights page here. Please let me know if you want me to also add a reference and link to Econia. Thanks!

@clay-aptos Works for me, thanks! Feel free to link to econialabs.com

**Comment by clay-aptos** [comment]
> > @alnoki , I am announcing your excellent multisig doc and adding it to the community highlights page here. Please let me know if you want me to also add a reference and link to Econia. Thanks!
> 
> @clay-aptos Works for me, thanks! Feel free to link to econialabs.com

Done! I also incorporated your fixes from PR #7310 here. Thank you!

**Review by michelle-aptos — APPROVED** [review]

**Comment by saharct** [comment]
@clay-aptos I removed the multisig announcement from Community Highlights and See What's New based on [this comment by David](https://github.com/aptos-labs/aptos-core/pull/7297#issuecomment-1480640845). Let's add it to External Contributions once it's published in the Econia docs.

**Comment by alnoki** [comment]
> @clay-aptos I removed the multisig announcement from Community Highlights and See What's New based on [this comment by David](https://github.com/aptos-labs/aptos-core/pull/7297#issuecomment-1480640845). Let's add it to External Contributions once it's published in the Econia docs.

@saharct the multisig announcement is still valid as the "Your First Multisig" tutorial was bridged into main (https://aptos.dev/tutorials/your-first-multisig), just without the *additional* content in #7297

**Comment by saharct** [comment]
That's my mistake, @alnoki. I thought we had announced the original tutorial and the update was specifically linking to the additional content. I'll revert my changes @clay-aptos.

**Comment by alnoki** [comment]
> That's my mistake, @alnoki. I thought we had announced the original tutorial and the update was specifically linking to the additional content. I'll revert my changes @clay-aptos.

Would you mind reverting per [a629d84](https://github.com/aptos-labs/aptos-core/pull/7308/commits/a629d84ebc7b919a57bb19d11c0793b40c8bba54)?

**Comment by saharct** [comment]
Sure thing, @alnoki. Thank you again for your contribution!

**Comment by alnoki** [comment]
> Sure thing, @alnoki. Thank you again for your contribution!

@saharct thanks for updating this, and you're welcome!

**Pull request merged**
