### PR TITLE
[storage] cleanup aptossum/inspector

### PR DESCRIPTION
**Pull request by lightmark**
issue #650 

## Test Plan

cargo build

### CODE REVIEW

**Review by msmouse — APPROVED** [review]
so clean

**Comment by sitalkedia** [comment]
@lightmark - Can you provide context on why this tool is not useful anymore?

**Comment by lightmark** [comment]
> @lightmark - Can you provide context on why this tool is not useful anymore?

let's move to https://github.com/aptos-labs/aptos-core/issues/650. In a word, basically it is for debugging purpose but I think we have better tools now @msmouse

**Comment by msmouse** [comment]
@sitalkedia  Nobody ever used them any way. Using curl to query the rest API offers the same capabilities.

**Comment by sitalkedia** [comment]
Thanks for the context - wish we removed this a month ago - I spent a lot of time adding functionalities to this tool :D

**Comment by lightmark** [comment]
> Thanks for the context - wish we removed this a month ago - I spent a lot of time adding functionalities to this tool :D

Then it's not my fault lol. You know who should be blamed :)

**Pull request merged**
