### PR TITLE
[storage] gas: config

### PR DESCRIPTION
**Pull request by msmouse**
### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2727)

### CODE REVIEW

**Comment by vgao1996** [comment]
@msmouse I thought about this a bit more and I think we still want this module to only fetch the db size and store that on-chain, instead of trying to generate the final base and unit costs by itself. Here are the reasons:
1. We still want a fixed base_cost and a fixed unit_cost in the gas schedule that can be manually adjusted, along with other gas parameters. Conceptually you can think of this as having a way to specify the bottom line costs when no storage penalty kicks in.
2. Coupling "fetching the db size and storing it on-chain" and "calculating the costs for global operations" seems unnecessary and a leak abstraction to me. Right now you can find all gas formulae in the aptos-gas crate, barring the native function ones, and it would be messy if only borrow_global_mut and friends are special and managed somewhere else.

**Comment by msmouse** [comment]
@vgao1996  Works for me. 

Let's clarify though (according to my current understanding):
1. the curves parameters stay together with other gas related parameters. I have no issue with this.

2. StateStoreIntrinsics is managed by its own module, and we install an `on_epoch_beginning()` hook to load that to the state. I'll add a native extension and native function to expose db utilization to that hook.

3. I think here's where we need to clarify and align: I think we need to calculate an easy to understand group of "direct parameters" out of the relatively static curve parameters and the relatively dynamic db utilization, things like "cost_per_item_created", "cost_per_byte_written", etc. And I think we need to write these derived parameters down on-chain, because they are easy to observe and understand for the community . Originally, I think my module manages the curve configs and the dynamic utilization and feed the resulting "direct parameters" to your gas schedule, and only feed that when the result is meaningfully different. -- my module work on a formula based on the curve configs, and your gas schedule works on a straightforward formula based on the "direct parameters", much like all other size based operations.  Now you are saying you manage both the curve parameters and the "direct parameters" and both sets of formulas. -- I'm fine with that, just let's clarify the "direct parameters" will be written down. -- or otherwise convince me :D

**Comment by vgao1996** [comment]
(2) sounds reasonable to me.

Good job summarizing our previous discussions in (3).

> I'm fine with that, just let's clarify the "direct parameters" will be written down. -- or otherwise convince me :D

Yeah I'll have to say that I don't think it's worth the extra cost (both in terms of code complexity and storage) to write these down. IMO the "direct parameters" are essentially intermediate steps of calculating the gas costs. They are not really different from some other intermediate results required by, for example, some crypto native functions. Following your logic, shouldn't we also write those down on-chain?

I understand your desire to make it easier for clients to understand the gas formulae, but I feel like this is the wrong tool for it. Let's take a step back and think about what it means for a client to truly understand how an operation is charged in the general case: it needs to know the algorithm (a.k.a. the formula) and all the inputs (gas parameters). The algorithm is encoded in the rust code and the gas parameters are stored on-chain. By putting some intermediate results on-chain you could make this one formula look simpler, but it still doesn't solve the fundamental issue that the client needs a way to look these formulae up or at least get a grasp of how they would scale. As I mentioned above, some crypto natives' gas formulae are really complicated. It's just unavoidable that clients will need to do some work in order to fully understand how gas metering works. IMO the correct weapon to attack this is proper documentation/education and good client side tooling that would help one estimate the amount of gas required without the need to diving into the numbers.

**Comment by vgao1996** [comment]
Or I guess a simpler way to phrase my point is:
1. If a client wants to know the precise gas costs, then they have to look up the formula and do the calculation. In this case, `p*(a*x + b) where p = <some complex formula>` shouldn't present real difficulty to this (seemingly pro) client.
2. If a client just wants to have a rough idea about the gas cost, then a line like "the cost of move_to scales with the size of the data, but is also multiplied by a penalty factor determined by how close the storage is near is target capacity" is likely enough to build up good intuition.

**Comment by msmouse** [comment]
K. That works for me. Then the price changes every epoch, even though the change can be small.

**Comment by vgao1996** [comment]
> Then the price changes every epoch, even though the change can be small.

Good point, but I think this is fine.

**Comment by msmouse** [comment]
https://github.com/aptos-labs/aptos-core/pull/3021 implements what we talked about here.

**Pull request closed without merging**
