### PR TITLE
[compiler-v2] Updating status of v1-v2 test porting

### PR DESCRIPTION
**Pull request by vineethk**
### Description

In this PR:
- we add some remapping of v1-v2 test paths in the diff tool that checks v1-v2 test porting status
- update the v1-v2 test porting status based on a few previous PRs

As a result, 20 additional tests have been marked as ported from v1 to v2.

### Test Plan

No tests are added or removed, they have just been moved to allow for remapping. As a result, some tests have new file paths in error report strings.

### CODE REVIEW

**Comment by brmataptos** [comment]
Have you checked the .move files to make sure they are identical?  I don't think Wolfgang's tool does that.

**Comment by vineethk** [comment]
> Have you checked the .move files to make sure they are identical? I don't think Wolfgang's tool does that.

@brmataptos The diff tool does not check that. I was the one who copied these files over as I implemented the relevant features (in previous PRs), so *yes* to your question for these files (and also for the two loop-related files that you ported in a previous PR).

**Review by wrwg — APPROVED** [review]
Awesome

**Review by rahxephon89 — APPROVED** [review]
Thanks!

**Pull request merged**
