### PR TITLE
[docs] Update e2e dapp tutorial with new names

### PR DESCRIPTION
**Pull request by gregnazario**

### CODE REVIEW

**Review by clay-aptos — APPROVED** [review]
Nice. Thanks, Greg!

**Review by banool — COMMENTED** [review]
Personally I prefer myaddr for a tutorial bc it makes it super clear that this thing is your address, where you publish the module. It can help clear up confusion about where things live.

**Comment by gregnazario** [comment]
> Personally I prefer myaddr for a tutorial bc it makes it super clear that this thing is your address, where you publish the module. It can help clear up confusion about where things live.

We have to prevent people from getting in this mindset where they have repeated names.

With repeated names, it makes it harder for dependencies, because the dependencies now need to avoid that name space, which can be really hard

**Comment by 0xmaayan** [comment]
Thanks @gregnazario !

**Pull request merged**
