### PR TITLE
[Community External Resource] Add Ansible Playbook for node management (bare metal)

### PR DESCRIPTION
**Pull request by ericjohncarlson**
### Description

Ansible playbook for Aptos Validators, VFNs and PFNs to be delivered to bare metal servers. This playbook is intended for node runners who utilize bare metal servers and build the aptos binaries from source.  This playbook includes specific tweaks to get the best performance out of the aptos-node service.  🚀

### This repo allows the:

- Ability to initialize an aptos validator, vfn and pfn from source, including bootstrapping the node, moving keys and configuration files, etc.
- Ability to upgrade to a new hash when requested for planned upgrades.
- Ability to upgrade to a hotfix binary release when requested.
- Contains tweaks to process CPU prioritization and IO prioritization to ensure aptos-node runs as close to run-time as necessary (without impacting core linux services)
- This playbook does _not_ include core server setup, security, or power management components necessary for server security and performance.  These components are the responsibility of the operator.

### CODE REVIEW

**Review by clay-aptos — APPROVED** [review]
Thank you, Eric! LGTM.

**Review by michelle-aptos — APPROVED** [review]

**Review by gregnazario — APPROVED** [review]

**Comment by gregnazario** [comment]
Looks like some docs-lint issues @clay-aptos if you can help @ericjohncarlson with it :)

**Comment by clay-aptos** [comment]
Hi @ericjohncarlson , it looks like we have another merge conflict. Can you take a look and see if you can resolve it? I am not able to check out your branch. Thanks!

**Comment by ericjohncarlson** [comment]
> Hi @ericjohncarlson , it looks like we have another merge conflict. Can you take a look and see if you can resolve it? I am not able to check out your branch. Thanks!

I think we're good now, Clay.  Thanks!

**Review by saharct — APPROVED** [review]

**Comment by saharct** [comment]
@ericjohncarlson This one has been merged. Please take a look at the other one when you get a chance. Thanks!

**Pull request merged**
