### PR TITLE
Aptos CLI Homebrew and README.md

### PR DESCRIPTION
**Pull request by hariria**
### Description
With this you can now install the aptos-cli via

```
brew install aptos
```

Details on how to modify the code and get started are located in the README.md

Will probably need input from @clay-aptos on how to update the docs accordingly

## Test plan

(Formula is still updating on their website, but it works)

https://user-images.githubusercontent.com/31301117/211170806-370de772-089e-49c3-8a68-545f04d64586.mov

### CODE REVIEW

**Comment by banool** [comment]
Might wanna wait a hot sec for https://github.com/aptos-labs/aptos-core/pull/6111.

**Comment by hariria** [comment]
@banool it auto updates :)

**Comment by clay-aptos** [comment]
This is looking good, Andrew. Thanks so much! If alright with you, I will make small edits inline as a direct commit while reviewing. (Started already.)

As for docs, I think I should create a simple *Install Aptos CLI* index that links to each option (brew, binaries, source) and then update navigation to go to that page first. @gregnazario , wdyt?

**Review by clay-aptos — APPROVED** [review]
Thanks so much for enabling Homebrew installation of the CLI, Andrew! This LGTM with some edits I made directly in commits.

I will ping Greg on linking in from Aptos.dev in Slack. Thanks again!

**Review by gregnazario — APPROVED** [review]

**Pull request merged**
