### PR TITLE
[Terraform Configs] Remove unnecessary override.

### PR DESCRIPTION
**Pull request by JoshLind**
### Description
This PR removes the unnecessary state sync configs from the default terraform yaml file.

### Test Plan
None.

### CODE REVIEW

**Comment by sionescu** [comment]
Is it safe to remove this override ? It will affect all environments (devnet, testnet, mainnet, ...).

**Review by msmouse — APPROVED** [review]
stamping ahead..

**Comment by sherry-x** [comment]
docker compose also has those values https://github.com/aptos-labs/aptos-core/blob/main/docker/compose/aptos-node/validator.yaml

**Comment by JoshLind** [comment]
> docker compose also has those values https://github.com/aptos-labs/aptos-core/blob/main/docker/compose/aptos-node/validator.yaml

Aah, thanks Sherry 😄

**Review by bchocho — APPROVED** [review]

**Review by sionescu — APPROVED** [review]

**Comment by JoshLind** [comment]
> Is it safe to remove this override ? It will affect all environments (devnet, testnet, mainnet, ...).
@sionescu, yeah, it should be fine 😄 Eventually, we want to move to a world where we only use the default configs anyway, so having these kind of overrides isn't geat.

**Pull request merged**
