### PR TITLE
[docker] Add restart policy to auto start container(s)

### PR DESCRIPTION
**Pull request by locnh**
## Motivation

Some time the host machine need to reboot to update, apply patch... Then when it boots up again, we may forget to start the container. Then I think we may want to add restart policy to the compose file.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yes, I did.

## Test Plan

Not really need, it will work as it has been.

If we need to test, just reboot the host machine then check the container(s).

## Related PRs

https://github.com/aptos-labs/aptos-core/pull/1008

### CODE REVIEW

**Comment by davidiw** [comment]
Please submit a signed cla and re-open.

**Comment by locnh** [comment]
> Please submit a signed cla and re-open.

Sent days ago, since the 1st pr.

**Review by davidiw — APPROVED** [review]

**Comment by davidiw** [comment]
There was some weird email smashing in the CLA inbox. I found it!

/land

**Comment by davidiw** [comment]
> ❗ before this PR can be merged please make sure that you enable ["Allow edits from maintainers"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
> 
> This is needed for tooling to be able to update this PR in-place so that Github can properly recognize and mark it as merged once its merged into the upstream branch

Please note the following @locnh

**Comment by locnh** [comment]
> > ❗ before this PR can be merged please make sure that you enable ["Allow edits from maintainers"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
> > This is needed for tooling to be able to update this PR in-place so that Github can properly recognize and mark it as merged once its merged into the upstream branch
> 
> Please note the following @locnh

ah, I forked to my org account then that why there is no option to enable it. I think I better close this one and create another one on my personal account.

**Pull request closed without merging**
