### PR TITLE
Rename duplicate move-table-extension feature in aptos-move/Cargo.toml

### PR DESCRIPTION
**Pull request by movekevin**
Fix cargo build errors due to duplicate dependency/feature name (move-table-extension)

### CODE REVIEW

**Comment by areshand** [comment]
I have problem in reproducing the error. I cloned the repo to a new directory and run cargo build and didn't see the error. Could you let me know your steps to reproduce the error?

**Comment by movekevin** [comment]
> I have problem in reproducing the error. I tried to to run cargo build on my main branch and also cloned the repo to a new directory and run cargo build and didn't see the error. Could you let me know your steps to reproduce the error?

I did exactly that - Fork + clone aptos-core repo. Run cargo build on main. I consistently got that error - features and dependencies cannot have the same name: `move-table-extension`. I'm using cargo 1.59.0

**Review by areshand — APPROVED** [review]

**Comment by areshand** [comment]
I will land it after build finish

**Pull request closed without merging**
