### PR TITLE
fix: fix the txn waiting bug

### PR DESCRIPTION
**Pull request by jjleng**
### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3540)

### CODE REVIEW

**Review by gregnazario — APPROVED** [review]

**Review by kent-white — APPROVED** [review]

**Comment by kent-white** [comment]
Do we want to do this for the `waitForTransaction` function as well?

**Comment by kent-white** [comment]
Never mind, it will fix for both

**Review by InvestorJoe — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3540)* status: 1 of 4 files reviewed, all discussions resolved

**Comment by InvestorJoe** [comment]
Test Plan

**Review by InvestorJoe — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3540)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/aptos-labs/aptos-core/3540#-NBPS1kZ8uihMZKym2Xi:-NBPS1kZ8uihMZKym2Xj:bdakj4e) (no related file):*
Test Plan 

___

**Pull request merged**
