### PR TITLE
[timed_features] Clean up already enabled flags

### PR DESCRIPTION
**Pull request by runtian-zhou**
### Description

Clean up the code for already published timed features. I'll create a separate PR to clean up parts involved in the Move repo.

### Test Plan

We need to trigger a replay testing to make sure we didn't revert any changes

### CODE REVIEW

**Review by movekevin — COMMENTED** [review]
Wouldnt this break replay?

**Comment by runtian-zhou** [comment]
They wont! Because those features are already activated on mainnet and we replay overrided the flag already so we shouldn't see any behavior change.

**Review by zekun000 — APPROVED** [review]
beautiful

**Review by sherry-x — APPROVED** [review]

**Review by alinush — APPROVED** [review]
Cryptography stuff looks good to me!

**Review by alinush — APPROVED** [review]
Cryptography stuff looks good to me!

**Comment by runtian-zhou** [comment]
Triggered replay manually and succeeded: https://github.com/aptos-labs/aptos-core/actions/runs/4995643628

**Pull request merged**
