### PR TITLE
[TS SDK] Bump TS SDK version to 1.9.0

### PR DESCRIPTION
**Pull request by 0xmaayan**

### CODE REVIEW

**Review by banool — APPROVED** [review]

**Comment by banool** [comment]
Uh actually shouldn't this be 1.9.0?

**Comment by 0xjinn** [comment]
Yeah I have the same question. Should this be 1.9.0? @0xmaayan

**Comment by 0xmaayan** [comment]
@banool @0xjinn Thank you!!

**Review by 0xjinn — APPROVED** [review]
Looks good! Lets roll this out :D

**Pull request merged**
