### PR TITLE
remove ExecutionCorrectness

### PR DESCRIPTION
**Pull request by zekun000**
ExecutionCorrectness is to spawn a process running execution in a different environment and connect to storage via network for better safety. We're not going down that path anymore, remove it will open opportunities for cleaner code too. (e.g. stateless executor)

### CODE REVIEW

**Comment by sitalkedia** [comment]
@zekun000 - Can you share more context on why we are removing this? May be also update the PR motivation section?

**Comment by msmouse** [comment]
remove storage-service as well?

**Comment by zekun000** [comment]
@msmouse storage-service is useful for remote read?

**Review by msmouse — APPROVED** [review]

**Review by davidiw — APPROVED** [review]
so much beautiful code... any idea the perf impact?

**Comment by zekun000** [comment]
I don't think there's perf impact expected since it's already disabled

**Pull request merged**
