### PR TITLE
Gas costs for BLS12-381, Ed25519, secp256k1, Ristretto255 and cryptographic hash functions

### PR DESCRIPTION
**Pull request by alinush**
### Description

Adding gas cost estimates for the cryptographic Move modules, subject to be improved later on.

This PR adds benchmarks for all cryptographic primitives used in Move and shell scripts used to parse the Criterion benchmark results into `.csv` files, which are quite handy for estimating the gas costs.

The most-relevant file that changed and should be reviewed is `aptos-framework.rs`.

The rest are just benchmarks and scripts. The scripts are probably best relocated to a different directory. Not sure where.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4630)

### CODE REVIEW

**Comment by alinush** [comment]
This PR also adds a missing (non-native) `aggr_or_multi_signature_from_bytes` function to the `bls12381` Move module.

**Review by vgao1996 — APPROVED** [review]
LGTM

**Comment by alinush** [comment]
> LGTM

Don't I need to bump `LATEST_GAS_FEATURE_VERSION` btw?

**Comment by vgao1996** [comment]
No. You are not changing any (Rust) gas formula

**Review by movekevin — APPROVED** [review]

**Pull request merged**
