### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by omahs**
Fix typos

### CODE REVIEW

**Review by davidiw — CHANGES_REQUESTED** [review]
The changes need to be made in the move files, then we generate the md files. Much appreciated for the changes.

**Comment by davidiw** [comment]
Please do a quick cargo build in the root directory to generate the markdown files.

**Comment by davidiw** [comment]
https://github.com/aptos-labs/aptos-core/actions/runs/8657670585/job/23740189799?pr=12446

Can you see this?

```
+ [ -n --check ]
+ git status --porcelain -uno aptos-move
+ [ -n  M aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
 M aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs ]
+ git diff
diff --git a/aptos-move/framework/aptos-framework/doc/primary_fungible_store.md b/aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
index b1118ab..c6017f1 100644
--- a/aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
+++ b/aptos-move/framework/aptos-framework/doc/primary_fungible_store.md
@@ -15,7 +15,7 @@ recipient's primary stores exist. If either doesn't, it will be created.
 3. The fungible asset metadata object calls <code>withdraw</code> on the sender's primary store to withdraw <code>amount</code> of
 fungible asset from it. This emits a withdraw event.
 4. The fungible asset metadata object calls <code>deposit</code> on the recipient's primary store to deposit <code>amount</code> of
-fungible asset to it. This emits a deposit event.
+ echo There are unstaged changes after running 'cargo build -p aptos-cached-packages'! Are you sure aptos-cached-packages is up-to-date?
+ exit 1
+fungible asset to it. This emits an deposit event.
 
 
 -  [Resource `DeriveRefPod`](#0x1_primary_fungible_store_DeriveRefPod)
@@ -702,7 +702,7 @@ Transfer <code>amount</code> of FA from the primary store of <code>from</code> t
 <td>9</td>
 <td>Only the owner of a primary store can transfer its balance to any recipient's primary store.</td>
 <td>High</td>
-<td>The function transfer fetches sender and recipient's primary stores, if the sender's store is withdraws the assets from the sender's store and then deposits to the recipient's store. The function transfer_with_ref fetches the sender's and recipient's stores and calls the asset to the recipient with the ref.</td>
+<td>The function transfer fetches sender and recipient's primary stores, if the sender's store is withdraws the assets from the sender's store and then deposits to the recipient's store. The function transfer_with_ref fetches the sender's and recipient's stores and calls the the asset to the recipient with the ref.</td>
 <td>Audited the deposit and withdraw (transfer). Audited the deposit_with_ref and withdraw_with_ref (transfer_with_ref). Audited that the store balance of the sender is decreased by the specified amount and its added to the recipients store. (transfer, transfer_with_ref) Audited that the sender's store is not burned (transfer).</td>
 </tr>
 
diff --git a/aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs b/aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
index e0a8da3..c238a8a 100644
--- a/aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
+++ b/aptos-move/framework/cached-packages/src/aptos_framework_sdk_builder.rs
@@ -321,7 +321,7 @@ pub enum EntryFunctionCall {
     DelegationPoolEnableDelegatorsAllowlisting {},
 
     /// Enable partial governance voting on a stake pool. The voter of this stake pool will be managed by this module.
-    /// THe existing voter will be replaced. The function is permissionless.
+    /// The existing voter will be replaced. The function is permissionless.
     DelegationPoolEnablePartialGovernanceVoting {
         pool_address: AccountAddress,
     },
@@ -352,7 +352,7 @@ pub enum EntryFunctionCall {
     },
 
     /// Allows an operator to change its beneficiary. Any existing unpaid commission rewards will be paid to the new
-    /// beneficiary. To ensures payment to the current beneficiary, one should first call `synchronize_delegation_pool`
+    /// beneficiary. To ensure payment to the current beneficiary, one should first call `synchronize_delegation_pool`
     /// before switching the beneficiary. An operator can set one beneficiary for delegation pools, not a separate
     /// one for each pool.
     DelegationPoolSetBeneficiaryForOperator {
@@ -23[78](https://github.com/aptos-labs/aptos-core/actions/runs/8657670585/job/23740189799?pr=12446#step:5:79),7 +2378,7 @@ pub fn delegation_pool_enable_delegators_allowlisting() -> TransactionPayload {
 }
 
 /// Enable partial governance voting on a stake pool. The voter of this stake pool will be managed by this module.
-/// THe existing voter will be replaced. The function is permissionless.
+/// The existing voter will be replaced. The function is permissionless.
 pub fn delegation_pool_enable_partial_governance_voting(
     pool_address: AccountAddress,
 ) -> TransactionPayload {
@@ -2478,7 +2478,7 @@ pub fn delegation_pool_remove_delegator_from_allowlist(
 }
 
 /// Allows an operator to change its beneficiary. Any existing unpaid commission rewards will be paid to the new
-/// beneficiary. To ensures payment to the current beneficiary, one should first call `synchronize_delegation_pool`
+/// beneficiary. To ensure payment to the current beneficiary, one should first call `synchronize_delegation_pool`
 /// before switching the beneficiary. An operator can set one beneficiary for delegation pools, not a separate
 /// one for each pool.
 pub fn delegation_pool_set_beneficiary_for_operator(
```

**Comment by omahs** [comment]
Hi @davidiw, I'm not a dev, but I enjoy contributing to projects that interest me and helping out with documentation. Unfortunately, I don't know how to fix these checks.

**Comment by davidiw** [comment]
@omahs , I'll take a look tomorrow, fix it, share with you, and land the PR. This was great, next time will be even greater :)

**Comment by davidiw** [comment]
fyi, I just ran `cargo xclippy` locally and it made all changes.

**Review by davidiw — APPROVED** [review]
fixed on my end...

**Pull request merged**
