### PR TITLE
Revert "[forge] remove direct eks cluster scaling"

### PR DESCRIPTION
**Pull request by rustielin**
Forge runs were failing healthcheck after tests start: https://github.com/aptos-labs/aptos-core/runs/6789662419?check_suite_focus=true

This is likely due to the cluster autoscaler not being fast enough / Forge timeout not being configured correctly in the right place. We can revisit this in the future, but for now bring back the direct cluster scaling upon forge test start/end

### CODE REVIEW

**Review by geekflyer — APPROVED** [review]

**Comment by geekflyer** [comment]
kinda surprised the cluster autoscaler not being fast enough. normally the k8s autoscaler scales up "immediately" (+delay of VM coming up) to the total size of the workloads specified in k8s manifests, but it  might be due to forge doing a serial deployment of each validator node and waiting for each one to be healthy before moving on to the next one?

**Comment by rustielin** [comment]
Anyways, waiting for https://github.com/aptos-labs/aptos-core/pull/1308 before landing this

**Pull request merged**
