### PR TITLE
[TS-SDK] Undo linter change

### PR DESCRIPTION
**Pull request by CapCap**
Undoes linter changes in #1139 to match previous discussions

### CODE REVIEW

**Review by zacharydenton — APPROVED** [review]

**Comment by jjleng** [comment]
I am OK with this. But can you please clarify the reasons why favoring double quotes?
web-wallet also uses single quote cc @hariria

**Comment by CapCap** [comment]
@jjleng regardless of what we go with, we should agree together; previously we'd discussed double quotes, so bold choice @hariria :-P All TS projects should be the same haha. I'll schedule something on Monday to re-sync.

**Comment by jjleng** [comment]
Totally agree. We should be consistent. Sure, lets sync on Monday.

**Comment by davidiw** [comment]
umm... closing out.

**Pull request closed without merging**
