### PR TITLE
[Docs] Korean version of Aptos Whitepaper

### PR DESCRIPTION
**Pull request by rajkaramchedu**
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3405)

### CODE REVIEW

**Review by aching — APPROVED** [review]

**Comment by aching** [comment]
Actually please no.

**Comment by aching** [comment]
We cannot rename the whitepaper.pdf to Aptos-Whitepaper.pdf.  That will break the Twitter link.  Please keep it whitepaper.pdf and whitepaper-korean.pdf

**Comment by rajkaramchedu** [comment]
> We cannot rename the whitepaper.pdf to Aptos-Whitepaper.pdf. That will break the Twitter link. Please keep it whitepaper.pdf and whitepaper-korean.pdf

I did not touch or rename "whitepaper.pdf". That still remains untouched, name and link. We are putting the Korean version online for the first time, I thought? Or is the Korean version link already exists? If yes, to which PDF it links to?

**Comment by aching** [comment]
Ah, sorry, you are renaming the other copy of the whitepaper which is interesting.  I do not think we link that anywhere.

**Comment by aching** [comment]
I guess it's fine, although a bit orthogonal to this change.  My personal preference would to add the new whitepaper as whitepaper-korean.pdf to be consistent, but I don't feel super strongly about it.

**Comment by rajkaramchedu** [comment]
@aching Renamed it to "whitepaper-korean.pdf". Please check?

**Pull request merged**
