### PR TITLE
[index] support all statement

### PR DESCRIPTION
**Pull request by s7v7nislands**
### Description
support all statement

### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5060)

### CODE REVIEW

**Comment by bowenyang007** [comment]
Sorry didn't see this earlier. Curious why we want to support all statements? Is there a use case for supporting more than insert?

**Comment by s7v7nislands** [comment]
we need update statements in some cases in our product. and I think it may be beneficial for common use.

**Review by bowenyang007 — APPROVED** [review]

**Comment by bowenyang007** [comment]
Sorry for the late stamp. I missed the response. Thanks for generalizing the API!

**Review by davidiw — APPROVED** [review]

**Comment by gregnazario** [comment]
I restarted the compatibility test, looks like a transient test harness issue

**Pull request merged**
