### PR TITLE
add origin/upstream remotes, minor edits

### PR DESCRIPTION
**Pull request by abebeos**
trivial

(Did the most important changes, the document needs still some revisions)

### CODE REVIEW

**Review by clay-aptos — COMMENTED** [review]
Thank you for these improvements, @abebeos. I am adding our eng leads to confirm we want to encourage forking the repo. As you fixed, we already recommend it later in the README.

**Comment by abebeos** [comment]
> confirm we want to encourage forking the repo.

Note that this is standard-procedure for github.

And you even refer to `upstream` later in the doc

[[davidiw](https://github.com/davidiw)](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#responding-to-reviewer-feedback)

```
git fetch upstream
git checkout topic
git rebase -i upstream/main
```

**Comment by clay-aptos** [comment]
> > confirm we want to encourage forking the repo.
> 
> Note that this is standard-procedure for github.
> 
> And you even refer to `upstream` later in the doc
> 
> [[davidiw](https://github.com/davidiw)](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#responding-to-reviewer-feedback)
> 
> ```
> git fetch upstream
> git checkout topic
> git rebase -i upstream/main
> ```

Agreed. Approving. Thanks again for your help!

**Review by clay-aptos — APPROVED** [review]

**Comment by clay-aptos** [comment]
Noting I still want @davidiw or @gregnazario to confirm still.

**Comment by clay-aptos** [comment]
Also, @abebeos , we are working on a section to better explain how to work together here:
https://github.com/aptos-labs/aptos-core/pull/6417

I would appreciate your feedback on that. Can name drop you there too. :-)

**Comment by abebeos** [comment]
Far to big, this overloads me immediately. I'll still give it a try tomorrow.

**Comment by clay-aptos** [comment]
> Far to big, this overloads me immediately. I'll still give it a try tomorrow.

No worries. It's live now:
https://aptos.dev/community/help-index

**Comment by abebeos** [comment]
> > Far to big, this overloads me immediately. I'll still give it a try tomorrow.
> 
> No worries. It's live now: https://aptos.dev/community/help-index

Nice! Quick-nit: the headings seem a bit large (could be my personal bias/preference, don't know...)

(i'll reach this documentation "naturally" during further aptos work-in at some point, and most possibly comment/PR then)

**Review by davidiw — APPROVED** [review]
eh... it isn't too this flow has always been the bane of my existence...

**Pull request merged**
