### PR TITLE
[Aptos Framework] Allow on-chain governance proposals to trigger reconfiguration in case of on-chain config changes

### PR DESCRIPTION
**Pull request by movekevin**
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2033)

### CODE REVIEW

**Review by zekun000 — COMMENTED** [review]
I'm not sure if we want to force reconfiguration or wait for next epoch. force reconfiguration will change how rewards works which needs to be timestamp based because we may have more epochs than expected.

**Review by davidiw — APPROVED** [review]
this is exciting.

**Comment by davidiw** [comment]
Ugh, auto-merge... the comment is probably not the right thing to say... we expose it but leave it to the deployer to decide.

**Comment by movekevin** [comment]
> Ugh, auto-merge... the comment is probably not the right thing to say... we expose it but leave it to the deployer to decide.

Yeah I didn't intend to merge it either. But adding CICD:skip-sdk-integration-test just triggered the merge :( I'll think more about Zekun's point and do a follow up PR if needed

**Pull request merged**
