### PR TITLE
[AWS] Add a gp3-maxiops storage class with 16K IOPS.

### PR DESCRIPTION
**Pull request by grao1991**
### Test Plan
Tested on Alden-net.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3025)

### CODE REVIEW

**Comment by rustielin** [comment]
Are we going to be recommending this, or just for testing?

**Comment by grao1991** [comment]
> Are we going to be recommending this, or just for testing?

I need to do some testing first to get the conclusion.

**Comment by rustielin** [comment]
> I need to do some testing first to get the conclusion.

Do you need this to land then? or you can just include it in your local tests until we can create an actual storage class we can recommend

**Comment by grao1991** [comment]
> > I need to do some testing first to get the conclusion.
> 
> Do you need this to land then? or you can just include it in your local tests until we can create an actual storage class we can recommend

I prefer to land if that doesn't cause too much trouble. Otherwise it's very easy to make mistake since I have changes in both aptos-core repo and internal-ops repo, and I often forget to switch branches for both of them :)

**Review by sherry-x — CHANGES_REQUESTED** [review]
Let's not land this right before AIT3 starts, this is the deployment script everyone will use. Or at least make a variable to disable this by default

**Comment by davidiw** [comment]
closing an oldr pr.

**Pull request closed without merging**
