### PR TITLE
update pnpm-lock.yaml and remove path-to-regex

### PR DESCRIPTION
**Pull request by rustielin**
### Description

This lockfile was out of sync, which was causing grafana-sync jobs to fail: https://github.com/aptos-labs/aptos-core/actions/runs/3397890836/jobs/5650451505

```
   ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
```

Remove the unneeded `path-to-regex` dep and run `pnpm install --no-frozen-lockfile`

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5514)

### CODE REVIEW

**Comment by geekflyer** [comment]
seems like the `path-to-regex` dependency had been added by accident to the repo root in https://github.com/aptos-labs/aptos-core/commit/3629253c980345a8aa6e9a847a704a022d73fe89 . Can you just remove the dependency from the repo root instead?

**Comment by banool** [comment]
pnpm said missing peer dep, that's why I added it. Feel free to remove it if it fixes things.

**Comment by geekflyer** [comment]
@banool  in your PR you added this dependency in both the root and `developer-docs-site`. U sure this is needed in both places??

**Comment by banool** [comment]
Oh yeah not in the root, MSB

**Comment by rustielin** [comment]
ok removed it @banool @geekflyer

**Review by geekflyer — APPROVED** [review]

**Pull request merged**
