### PR TITLE
Update staking-pool-operations.md

### PR DESCRIPTION
**Pull request by michelle-aptos**
corrected CLI command to create staking_contract

previously the command created a direct pool type

### CODE REVIEW

**Review by gregnazario — COMMENTED** [review]
@movekevin this is supposed to be staking contract?

**Review by movekevin — COMMENTED** [review]
Isn't this doc for creating direct stake pools?

**Comment by michelle-aptos** [comment]
> 

why is it direct and not staking_contract?

**Comment by saharct** [comment]
@michelle-aptos are there pending changes?

**Comment by michelle-aptos** [comment]
@xindingw can you take a look? should we also add your view function for getting the stake pool address?

**Review by sherry-x — APPROVED** [review]
Could you please address Greg's comment, then we can get this one landed?

**Review by saharct — APPROVED** [review]

**Pull request merged**
