### PR TITLE
[Transaction] rename UserTransaction/SignedTransaction/RawTransaction…

### PR DESCRIPTION
**Pull request by lightmark**
… to Deprecated*

### Description

step 1 to support new txn type

### Test Plan
n/a

### CODE REVIEW

**Comment by alinush** [comment]
I presume this will be backwards compatible?

**Comment by lightmark** [comment]
> I presume this will be backwards compatible?

in what sense?

**Comment by alinush** [comment]
> > I presume this will be backwards compatible?
> 
> in what sense?

In the sense that we are keeping the old structs around. So this is not a "rename"; it's adding new V2 structs, no?

**Comment by lightmark** [comment]
> > > I presume this will be backwards compatible?
> > 
> > 
> > in what sense?
> 
> In the sense that we are keeping the old structs around. So this is not a "rename"; it's adding new V2 structs, no?

Yes.
We have to support the old format but I guess it will be wrapped into the new enum as a `V0` version.

**Pull request closed without merging**
