### PR TITLE
adding flag to adjust polling

### PR DESCRIPTION
**Pull request by igor-aptos**

### CODE REVIEW

**Review by sitalkedia — APPROVED** [review]

**Review by msmouse — APPROVED** [review]

**Comment by igor-aptos** [comment]
added code to better handle mint to root overflow

**Comment by msmouse** [comment]
@igor-aptos  you didn't push your added code it seems, but I did these https://github.com/aptos-labs/aptos-core/pull/10840/commits -- what's your approach?

**Comment by igor-aptos** [comment]
@msmouse - oops, updated. 

I am always going to mint the full amount to root, and allow things to proceed if my transaction failed, but someone else refilled the account

**Comment by msmouse** [comment]
Nice strategy, thank you!

**Pull request merged**
