### PR TITLE
change the aptos-cli install command using cargo to aptos-cli version 0.2.0

### PR DESCRIPTION
**Pull request by hadyandev**
… 0.2.0

### Test Plan

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1732)

### CODE REVIEW

**Comment by fontm2** [comment]
hi Aptos team, we need to have this soon in place. the "latest" pointing to the wrong version confuses people a lot. Thank you!

**Comment by davidiw** [comment]
@gregnazario / @geekflyer can one of you look at this?

**Review by gregnazario — APPROVED** [review]

**Comment by geekflyer** [comment]
i don't think this will work / is desirable since it points to an older tag . Btw we should probably remove this tag from git altogether since having mutable git tags is kinda bad. wdyt @gregnazario  ?
Here's the tag list https://github.com/aptos-labs/aptos-core/tags

**Comment by geekflyer** [comment]
Just removed a bunch of tags and releases that ended with `-latest`. Having mutable git tags is bad.

**Pull request merged**
