### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by AptosDev**
### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5145)

### CODE REVIEW

**Comment by SBOJISUN** [comment]
0xd1eb7a6cdfb6de2640976a548b4bf770dbcb2b1a96019c21c993e98de0061320

**Review by SBOJISUN — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidiw and @rajkaramchedu)

**Review by SBOJISUN — COMMENTED** [review]
Donations 

Please send to aptos 
0xd1eb7a6cdfb6de2640976a548b4bf770dbcb2b1a96019c21c993e98de0061320

> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5145#-:-NEit4MtBVsxqL4wLv8m:b-aofs71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidiw and @rajkaramchedu)

**Review by SBOJISUN — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidiw and @rajkaramchedu)

**Review by SBOJISUN — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidiw and @rajkaramchedu)

**Review by AptosDev — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @davidiw and @rajkaramchedu)

**Comment by AptosDev** [comment]
[https://promote.mexc.com/a/Aptos](url)

**Pull request closed without merging**
