### PR TITLE
Update workload sweep forge thresholds

### PR DESCRIPTION
**Pull request by igor-aptos**
These update thresholds based on the impact of the gas schedule and block limit changes. 

latencies are much more uniform and predictable (we can probably lower them further, I was a big conservative). on the other hand - throughput for NFT minting is lower, because it was overloading before.

### CODE REVIEW

**Comment by igor-aptos** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #11356** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11356?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/aptos-labs/aptos-core/11356?utm_source=stack-comment).

**Review by zekun000 — COMMENTED** [review]
are these numbers according to the new block limit?

**Comment by igor-aptos** [comment]
@zekun000 yes, updated the description

**Review by zekun000 — APPROVED** [review]

**Review by bchocho — APPROVED** [review]
YOLO

**Pull request merged**
