### PR TITLE
[cli] Sign now execute later, basic Cold wallet

### PR DESCRIPTION
**Pull request by gregnazario**
### Description
This lets you sign a transaction disconnected from the internet, and submit it later.  Useful if you want to have a "cold" key, and disconnected from the internet, but still want to execute transactions.

### Test Plan
Newest test:
```
$ aptos account transfer --account default --amount 0 --save-transaction-to test.txt
Do you want to submit a transaction for a range of [45500 - 68200] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
  "Result": {
    "transaction_hash": "0x0c7babc1684dcc71ecdd74d7aa554f76b0f6f82e609e524238861dd650963350",
    "saved_transaction_path": "test.txt"
  }
}
$ cat test.txt
B6DBF76636021A840C64DA0CA6AA94297B4EAD015F7398521F57347F6836489801000000000000000200000000000000000000000000000000000000000000000000000000000000010D6170746F735F6163636F756E74087472616E73666572000220B6DBF76636021A840C64DA0CA6AA94297B4EAD015F7398521F57347F68364898080000000000000000AA02000000000000640000000000000093BCAC63000000002900204C9FB933051300FABFB4515F924353D5272E5AFCAE927DE1138BFE813137F30A408D4EFA2B7E6356CCA7D608A3605651C08AE8EEB412F2E326D4680A175A5F3A8F918EE435045B1F0E4F5EA0471F563A7689FF3B04ACF76C86EA7234A084625E01%   

(waited a while ...)

$ aptos move run-signed-transaction --signed-transaction-path test.txt
{
  "Error": "API error: API error Error(VmError): Invalid transaction: Type: Validation Code: TRANSACTION_EXPIRED"
}
$ aptos account transfer --account default --amount 0 --save-transaction-to test.txt
Do you want to submit a transaction for a range of [45500 - 68200] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
  "Result": {
    "transaction_hash": "0xd3b2df426d5adfb3604ac8bd5d5aad5836121e0ab8b2bea3b23c452e7fb71a63",
    "saved_transaction_path": "test.txt"
  }
}
$ aptos move run-signed-transaction --signed-transaction-path test.txt
{
  "Result": {
    "transaction_hash": "0xd3b2df426d5adfb3604ac8bd5d5aad5836121e0ab8b2bea3b23c452e7fb71a63",
    "gas_used": 522,
    "gas_unit_price": 100,
    "sender": "b6dbf76636021a840c64da0ca6aa94297b4ead015f7398521f57347f68364898",
    "sequence_number": 1,
    "success": true,
    "timestamp_us": 1672264921055876,
    "version": 7909258,
    "vm_status": "Executed successfully"
  }
}
```

With simulation
```
$ aptos account transfer --signed-transaction-path saved_txn --account testing --amount 500 --transaction-expiration-secs 500
Do you want to submit a transaction for a range of [55200 - 82800] Octas at a gas unit price of 100 Octas? [yes/no] >
yes
{
  "Result": {
    "transaction_hash": "0x1b5eb3b3d052571f07a0feca73610055aa6dbb0ae4c12ead1ae393fc205acdd5",
    "saved_transaction_path": "saved_txn"
  }
}

$ cat saved_txn 
B6DBF76636021A840C64DA0CA6AA94297B4EAD015F7398521F57347F6836489801000000000000000200000000000000000000000000000000000000000000000000000000000000010D6170746F735F6163636F756E74087472616E7366657200022001C434E9243F7EDC17AFCBA6144CED93198CF37CBCBE574B4D2D00F756FE92B908F4010000000000003C0300000000000064000000000000002ACB4963000000002200204C9FB933051300FABFB4515F924353D5272E5AFCAE927DE1138BFE813137F30A40CE5F131E0D68FD0B9BC52A20670A155B6A9B05F50300FB9933917315384BA724BF6E088FE8ED91F6B94D17B37283914DF7253D4C16E3927E492AD389AE36AE0E

$ aptos move run-signed-transaction --signed-transaction-path saved_txn
{
  "Result": {
    "transaction_hash": "0x1b5eb3b3d052571f07a0feca73610055aa6dbb0ae4c12ead1ae393fc205acdd5",
    "gas_used": 585,
    "gas_unit_price": 100,
    "sender": "b6dbf76636021a840c64da0ca6aa94297b4ead015f7398521f57347f68364898",
    "sequence_number": 1,
    "success": true,
    "timestamp_us": 1665780501649736,
    "version": 1618454,
    "vm_status": "Executed successfully"
  }
}

```

With no simulation
```
$ aptos account transfer --signed-transaction-path saved_txn --account testing --amo
unt 500 --transaction-expiration-secs 1000 --sequence-number 2 --max-gas 30000 --gas-unit-price 100
{
  "Result": {
    "transaction_hash": "0xa495843646a83ee80267467aca7fbb2e0c0944dfd60a81a98676d9b31ed4e53c",
    "saved_transaction_path": "saved_txn"
  }
}
$ aptos 
move run-signed-transaction --signed-transaction-path saved_txn
{
  "Result": {
    "transaction_hash": "0xa495843646a83ee80267467aca7fbb2e0c0944dfd60a81a98676d9b31ed4e53c",
    "gas_used": 585,
    "gas_unit_price": 100,
    "sender": "b6dbf76636021a840c64da0ca6aa94297b4ead015f7398521f57347f68364898",
    "sequence_number": 2,
    "success": true,
    "timestamp_us": 1665780926888643,
    "version": 1625649,
    "vm_status": "Executed successfully"
  }
}

```

With no network connection
```
$ curl https://fullnode.devnet.aptoslabs.com/v1
{"chain_id":34,"epoch":"13","ledger_version":"1633806","oldest_ledger_version":"0","ledger_timestamp":"1665781417161896","node_role":"full_node","oldest_block_height":"0","block_height":"645538","git_hash":"83641d3f083762f31700060e5e95fbb1cbc28bf0"}%                                                      
$ aptos account transfer --signed-transaction-path saved_txn --account testing --amount 500 --transaction-expiration-secs 1000 --sequence-number 3 --max-gas 30000 --gas-unit-price 100 --chain-id 34
{
  "Result": {
    "transaction_hash": "0x8a2654c1827d076e69c6ec2d5b4cfa9e0e31898229f7061762565aced0452654",
    "saved_transaction_path": "saved_txn"
  }
}
$ curl https://fullnode.devnet.aptoslabs.com/v1
curl: (6) Could not resolve host: fullnode.devnet.aptoslabs.com
$ aptos account transfer --signed-transaction-path saved_txn --account testing --amount 500 --transaction-expiration-secs 1000 --sequence-number 3 --max-gas 30000 --gas-unit-price 100 --chain-id 34
{
  "Result": {
    "transaction_hash": "0x3b20c27afb28e043873290f61dc07dff43f59cfa18a5b8f8fff787deaa5ea724",
    "saved_transaction_path": "saved_txn"
  }
}
$ curl https://fullnode.devnet.aptoslabs.com/v1
{"chain_id":34,"epoch":"13","ledger_version":"1634457","oldest_ledger_version":"0","ledger_timestamp":"1665781452427486","node_role":"full_node","oldest_block_height":"0","block_height":"645802","git_hash":"83641d3f083762f31700060e5e95fbb1cbc28bf0"}%                                                      
$ aptos move run-signed-transaction --signed-transaction-path saved_txn
{
  "Result": {
    "transaction_hash": "0x3b20c27afb28e043873290f61dc07dff43f59cfa18a5b8f8fff787deaa5ea724",
    "gas_used": 585,
    "gas_unit_price": 100,
    "sender": "b6dbf76636021a840c64da0ca6aa94297b4ead015f7398521f57347f68364898",
    "sequence_number": 3,
    "success": true,
    "timestamp_us": 1665781458178844,
    "version": 1634559,
    "vm_status": "Executed successfully"
  }
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5040)

### CODE REVIEW

**Review by banool — COMMENTED** [review]
I'm not sure about the API here, I feel this might lead to some confusion. At the least I'd name the flag something like `--save-transaction-to` or something like that, the flag name now implies to me that it's referring to something that already exists. Beyond that this feels like a few of large ish changes, like you say, might be better to save this for post 1.0.0 so we can discuss some more (for example this could be something you configure in your profile).

**Comment by gregnazario** [comment]
> I'm not sure about the API here, I feel this might lead to some confusion. At the least I'd name the flag something like `--save-transaction-to` or something like that, the flag name now implies to me that it's referring to something that already exists. Beyond that this feels like a few of large ish changes, like you say, might be better to save this for post 1.0.0 so we can discuss some more (for example this could be something you configure in your profile).

Yeah, that's fair, it was pretty quick.  Will update later

**Comment by davidiw** [comment]
Seems good, needs a refresh
Some of these commits aren't super crisp, might as well be one commit.

**Comment by davidiw** [comment]
/cough/

**Comment by gregnazario** [comment]
> /cough/

This has some merge conflicts with the other CLI changes, the other ones are more important, so they will be addressed first then come back to this.

**Comment by gregnazario** [comment]
Updated to handle merge conflicts

**Comment by banool** [comment]
Will look next week.

**Pull request closed without merging**
