### PR TITLE
[Base64 + Move] add Base64 Move module

### PR DESCRIPTION
**Pull request by 99Kies**
### Description

Add Base64 Encode/Decode Support On Move

### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4574)

### CODE REVIEW

**Comment by 99Kies** [comment]
Is this a CICD problem?
image

**Comment by wrwg** [comment]
Thank you for looking into this! At this point, we have a code freeze and unfortunately can't take changes like this any longer. We are happy to reconsider this after mainnet.

Technically, there is something wrong with the way how you created this commit. There are multiple older commits and a merge to main. This is supposed to not happen. If you resubmit, please have a clean owned series of commits on top of the main branch.

**Comment by 99Kies** [comment]
@wrwg Thanks for the suggestion, I will resubmit a pr.

**Comment by vgao1996** [comment]
Yeah to me, Base64 looks like a reasonable thing to have. Let's revisit this after we get over the code freeze. (Shall we keep the issue open so we won't forget about it?)

At meanwhile I think there's one thing we may want to discuss: do we prefer having this as part of the aptos-stdlib or a package of its own?

**Pull request closed without merging**
