### PR TITLE
[Spec] Specs for `smart_table` module

### PR DESCRIPTION
**Pull request by 1nc0gn170**
### Description

Here we add specifications for smart_table. 

### Test Plan
Use the Aptos prover.

### CODE REVIEW

**Comment by 1nc0gn170** [comment]
@movekevin Could you please get this Pr reviewed?

**Review by junkil-park — APPROVED** [review]
@1nc0gn170 , are you also planning to specify those function that are disabled in verification (e.g., `verify=false`)?

**Review by rahxephon89 — APPROVED** [review]

**Comment by junkil-park** [comment]
The CI test fails due to the timeout of Prover: https://github.com/aptos-labs/aptos-core/actions/runs/4566117518/jobs/8059718256?pr=7493#step:8:5450

**Comment by 1nc0gn170** [comment]
@junkil-park  Do we have any alternative solution for the prover timeout?

**Comment by junkil-park** [comment]
@1nc0gn170 , first of all, please make sure your PR is rebased on the origin/main, and the Aptos CLI is installed from it.

There are some pragmas that you can use. One way is: https://github.com/aptos-labs/aptos-core/pull/7874
If that doesn't work out for you, put `pragma verify=false; // TODO: set to false due to timeout` and let us know. We will take a look at it after the PR lands.

**Pull request merged**
