### PR TITLE
[CP] Remove old node verifier code

### PR DESCRIPTION
**Pull request by CapCap**
### Description
Remove old node verifier code- we are solely using node health checker now

### Test Plan
Tested Manually

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1868)

### CODE REVIEW

**Comment by davidiw** [comment]
@CapCap is this PR relevant?

**Comment by CapCap** [comment]
I need to rebase, but yes :-)

**Comment by gregnazario** [comment]
Rebase @CapCap ?

**Comment by davidiw** [comment]
hmmm... is this stale?

**Pull request closed without merging**
