### PR TITLE
Crate disentangle

### PR DESCRIPTION
**Pull request by brianolson**
### Description

`network/` crate becomes `network/framework/` so that no frameworks are nested within it, other crates under `network/...` are unaffected.

### Test Plan

Unit tests and lint should catch all the compile dependencies. No code changes.

### CODE REVIEW

**Comment by JoshLind** [comment]
I have mixed feelings about this. I agree it's interesting that `network/` is a crate, but I'm not sure this PR is the right approach. Generally, things under `crates` should be self-contained and reusable. But, moving the networking code into it, feels odd.

Regarding the peer monitoring service, I'd rather we bring this up into its own directory (i.e., at the same level as state sync, mempool and consensus). Note sure where else to put the networking code though (e.g., `network-discovery`, `network-builder`, etc.)

**Comment by brianolson** [comment]
The net change is now `network/` -> `network/framework/`, and `network/{crate}` remains for everything else. All crate names in the root Cargo.toml remain the same.

**Comment by davidiw** [comment]
nice, nit though, framework -> core, thoughts?

**Comment by brianolson** [comment]
sorry, "netcore" is taken.
"framework" actually feels right to me. Kinda similar to some HTTP frameworks I've worked with they parse the protocol, do event handling, and pass structs for Headers and Body data, and handle reassembly of the outbound message.

**Review by JoshLind — APPROVED** [review]
LGTM. Unblocking 😄

**Review by bchocho — APPROVED** [review]
LGTM

**Pull request merged**
