### PR TITLE
[docs] Add dependency instructions for from source for Windows

### PR DESCRIPTION
**Pull request by gregnazario**
### Description
This updates dependency instructions for Windows, Linux, and macOS on the getting started page for downloading source.  This should be eventually replace any other place that downloads source in the instructions.

### Test Plan
I tested the manual instructions for Windows directly in a Windows VM.  The instructions for Linux have been there for a long time / the script should be good enough.

The instructions for macOS are not tested, but similar on the script.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5090)

### CODE REVIEW

**Comment by davidiw** [comment]
gotta resurrect this!

**Comment by davidiw** [comment]
@gregnazario , let's update this.

**Comment by davidiw** [comment]
Please! Give someone a Christmas gift.

**Comment by gregnazario** [comment]
I'm looking into this right now.  I had to spin up a Windows VM for it, and dealing with instructions for line endings etc.

**Review by clay-aptos — APPROVED** [review]
Hi Greg,

This generally looks good with a few small edits I made directly. I have two concerns and have included Sherry along with David for guidance:

1. Why make source use for advanced users?
2. Are the lists of packages for manual install complete? I recall the script installing more.

Thanks for the improvements!

**Comment by gregnazario** [comment]
> Hi Greg,
> 
> This generally looks good with a few small edits I made directly. I have two concerns and have included Sherry along with David for guidance:
> 
> 1. Why make source use for advanced users?
> 2. Are the lists of packages for manual install complete? I recall the script installing more.
> 
> Thanks for the improvements!

1. We could make source use for all users.  Though, it can become very confusing.  For example, one of the dependencies I had to install was LLVM.  LLVM doesn't provide packaged support for Windows, so you have to check out the source, compile it, ensure you're choosing the right options etc.  It's not that it's that bad, but the default compilation mode is slower at runtime (debug mode), and the time it takes to compile the codebase on a older machine / doesn't have the memory (if not Linux with LLD), can be very daunting & frustrating.
2. The lists of the package aren't necessarily complete, but that should support most use cases.  It's a pretty long list of mostly optional dependencies (at least for Windows).  For example, Python / typescript aren't needed unless you work with the SDKs directly

**Pull request merged**
