### PR TITLE
fix some typos.

### PR DESCRIPTION
**Pull request by hattizai**
## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [x] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by alinush — APPROVED** [review]
Thank you! 🙏

**Comment by hattizai** [comment]
@alinush Hi sir, can we get this merged?

**Comment by hattizai** [comment]
@junkil-park @davidiw @movekevin @wrwg Hi sir, could you please help me review this PR~

**Review by junkil-park — APPROVED** [review]
Thank you!

**Comment by junkil-park** [comment]
@hattizai , there is a lint test failure: https://github.com/aptos-labs/aptos-core/actions/runs/10231066521/job/28306584961?pr=13185#step:4:968

**Review by junkil-park — APPROVED** [review]

**Pull request merged**
