### PR TITLE
[SDK] Refactor and move the TypeTagParser to type_tag file

### PR DESCRIPTION
**Pull request by 0xjinn**
### Description
This is a required refactor PR that move the `TypeTagParser` to the type_tag.ts file (Which I believe should be the correct place for the parser). 

So we can use the TypeTagParser to fix issue #7575  

### Why not just reference it from builder_utils?
Primarily, We cannot import it from the `builder_utils.ts` because of **circular dependency**. `type_tag` <-> `builder_utils` we need to move the parser to type_tag, so it can be used to implement StructTag.fromString function here - https://github.com/aptos-labs/aptos-core/blob/500b349df3b495da388d85d8680494f1a01dde22/ecosystem/typescript/sdk/src/aptos_types/type_tag.ts#L192-L204

### Test Plan
pnpm run lint
pnpm test

### CODE REVIEW

**Comment by 0xmaayan** [comment]
I am a bit confused, why do you need to move the `TypeTagParser` and can't simply import it from `transaction_builder`? as for where it belongs, I would argue it can live in its own file - `type_tag_parser.ts`

**Comment by 0xjinn** [comment]
> I am a bit confused, why do you need to move the `TypeTagParser` and can't simply import it from `transaction_builder`? as for where it belongs, I would argue it can live in its own file - `type_tag_parser.ts`

@0xmaayan Yeah, that was actually my first attempt, but importing it from the builder will result in a circular dependency as I mentioned in the description. 

But yeah, i think moving to its own file works as well!

**Comment by 0xmaayan** [comment]
Placing the file in `aptos_types` can lead to a breaking change for anyone importing/using this parser. Now, they should be able to simply do `import {TypeTagParser} from aptos`, but once we move it to `aptos_types` they would need to use it as
```
import {TxnBuilderTypes} from aptos;
TxnBuilderTypes.TypeTagParser
```
We might want to think on placing it in a folder that users can keep importing/using it as they do now.

Also, could you make sure we update imports? for example, I believe `property_map_serde.ts` uses `import { TypeTagParser } from "../transaction_builder";`

**Review by gregnazario — APPROVED** [review]
Can you write some positive and negative unit tests for the typetag parser

**Comment by 0xmaayan** [comment]
can we
1. create a new file for the parser - `type_tag_parser.ts` that lives in `aptos_types` folder
2. make sure we update imports? for example, I believe `property_map_serde.ts` uses `import { TypeTagParser } from "../transaction_builder";`

**Review by 0xmaayan — APPROVED** [review]

**Comment by 0xjinn** [comment]
> Can you write some positive and negative unit tests for the typetag parser

Will add the unit test in the diff https://github.com/aptos-labs/aptos-core/pull/7660

**Comment by 0xmaayan** [comment]
could you also add this change to CHANGELOG.md

**Comment by 0xjinn** [comment]
> could you also add this change to CHANGELOG.md

@0xmaayan Ah yes! Will include that in the next PR

**Pull request merged**
