### PR TITLE
Add a governance proposal for AIP30

### PR DESCRIPTION
**Pull request by sherry-x**
### Description

AIP30 has completed testing, we propose to get it enabled across all networks. 

### Test Plan

run release builder to generate the proposal
https://github.com/aptos-foundation/mainnet-proposals/pull/43

### CODE REVIEW

**Review by movekevin — COMMENTED** [review]
This wouldn't work though. You'd have to temporarily delete all other proposals to generate precisely just this proposal

**Comment by sherry-x** [comment]
@movekevin I kinda want to preserve all other proposals we did in this release, is it not okay to re-execute other proposals we made on testnet? I imagine for Mainnet we can just take part of the script to upload. worst case I can comment them out

**Comment by movekevin** [comment]
> @movekevin I kinda want to preserve all other proposals we did in this release, is it not okay to re-execute other proposals we made on testnet? I imagine for Mainnet we can just take part of the script to upload. worst case I can comment them out

You can temporarily delete them locally, generate the proposals, then put them back and add this here I guess :)

**Comment by sherry-x** [comment]
@movekevin here is just a reference, I would upload the actual script to the governance proposal repo. I guess here also serve as a testnet testing, since I can trigger the framework upgrade for testnet through automation. but anyway, maybe let's comment out the rest

**Comment by sherry-x** [comment]
okay generated proposal files here https://github.com/aptos-foundation/mainnet-proposals/pull/43

**Pull request closed without merging**
