### PR TITLE
[dependencies] update jemalloc to tikv-jemalloc for better compatilibity

### PR DESCRIPTION
**Pull request by 0x5ea000000**
## Description
List dependencies that are required for this change:
```
jemallocator = { package = "tikv-jemallocator", version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }
jemalloc-sys = { package = "tikv-jemalloc-sys", version = "0.5.4" }
```

Jemalloc is currently being maintained by [tikv](https://github.com/tikv/jemallocator) and distributed under two names: `jemallloc` and `tikv-jemalloc`, **both do the same thing**. It's recommended to use tikv-xxx versions for better compatibility. 
I am trying to use Aptos as the settlement layer and data availability layer for [Madara Starknet stack](https://github.com/keep-starknet-strange/madara) and have conflict between 2 version of jemalloc.

```
Updating git repository `https://github.com/aptos-labs/aptos-core`
    Updating crates.io index
error: failed to select a version for `jemalloc-sys`.
    ... required by package `jemallocator v0.5.0`
    ... which satisfies dependency `jemallocator = "^0.5.0"` of package `aptos-block-partitioner v0.1.0 (https://github.com/aptos-labs/aptos-core#a270a1be)`
    ... which satisfies git dependency `aptos-block-partitioner` of package `aptos-vm v0.1.0 (https://github.com/aptos-labs/aptos-core#a270a1be)`
    ... which satisfies git dependency `aptos-vm` of package `aptos-api-types v0.0.1 (https://github.com/aptos-labs/aptos-core#a270a1be)`
    ... which satisfies git dependency `aptos-api-types` of package `aptos-sdk v0.0.3 (https://github.com/aptos-labs/aptos-core#a270a1be)`
    ... which satisfies git dependency `aptos-sdk` of package `mc-settlement v0.1.0 (/home/administrator/madara/crates/client/settlement)`
    ... which satisfies path dependency `mc-settlement` (locked to 0.1.0) of package `madara v0.7.0 (/home/administrator/madara/crates/node)`
versions that meet the requirements `^0.5.0` are: 0.5.4+5.3.0-patched, 0.5.3+5.3.0-patched, 0.5.2+5.3.0-patched, 0.5.1+5.3.0-patched, 0.5.0+5.3.0

the package `jemalloc-sys` links to the native library `jemalloc`, but it conflicts with a previous package which links to `jemalloc` as well:
package `tikv-jemalloc-sys v0.5.4+5.3.0-patched`
    ... which satisfies dependency `tikv-jemalloc-sys = "^0.5"` (locked to 0.5.4+5.3.0-patched) of package `librocksdb-sys v0.11.0+8.1.1`
    ... which satisfies dependency `librocksdb-sys = "^0.11.0"` (locked to 0.11.0+8.1.1) of package `rocksdb v0.21.0`
    ... which satisfies dependency `rocksdb = "^0.21"` (locked to 0.21.0) of package `kvdb-rocksdb v0.19.0`
    ... which satisfies dependency `kvdb-rocksdb = "^0.19.0"` (locked to 0.19.0) of package `mc-db v0.7.0 (/home/administrator/madara/crates/client/db)`
    ... which satisfies path dependency `mc-db` (locked to 0.7.0) of package `madara v0.7.0 (/home/administrator/madara/crates/node)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "jemalloc"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `jemalloc-sys` which could resolve this conflict
```

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [x] Dependency update
- [ ] Documentation update

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ ] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by msmouse** [comment]
Thank you for the contribution. Looks reasonable. Could you please rebase and let's make it through all the tests?

**Comment by haipro287** [comment]
> Thank you for the contribution. Looks reasonable. Could you please rebase and let's make it through all the tests?

Thank you for reviewing my pull request and for accepting the change! I really appreciate your feedback.
I'll get right on it and rebase my changes and ensure they pass all the tests.

**Review by JoshLind — APPROVED** [review]
LGTM. Kicked off the tests 😄

**Review by msmouse — APPROVED** [review]

**Comment by haipro287** [comment]
@msmouse Long time no see sir, I forgot this PR due to a lot of things that need to be done. Last time when you approved this PR, it had some failures in tests and I've updated it. Please kick off the test again

**Review by grao1991 — APPROVED** [review]

**Comment by msmouse** [comment]
hmm.. I'm sorry but I guess you need to rebase it again. (I copied your change and rebased it and tests pass https://github.com/aptos-labs/aptos-core/pull/13225)

**Comment by 0x5ea000000** [comment]
I rebased it

**Comment by 0x5ea000000** [comment]
@msmouse could you recheck this PR?

**Comment by benluelo** [comment]
i've hit this issue as well - can this be revived?

**Comment by 0x5ea000000** [comment]
> i've hit this issue as well - can this be revived?

Now it's more complicated that aptos-core repo and aptos-indexer-proccessor repo has cyclic dependency and both are using jemalloc.  So both should be changed to tikv version on the same time :(

**Pull request closed without merging**
