### PR TITLE
[Forge] Add basic support for large db test in forge.

### PR DESCRIPTION
**Pull request by grao1991**
### Description
Add the capability to claim an existing PV using a specified tag.

### Test Plan
Manually verified that this can successfully mount an existing EBS volume.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4348)

### CODE REVIEW

**Review by perryjrandall — APPROVED** [review]
Please include test plan command you ran + output!!!

Otherwise looking amazing :D :D :D

**Review by rustielin — APPROVED** [review]

**Comment by sitalkedia** [comment]
@grao1991 - Do you have a successful run for this test? If so, can you point to the link? Also, can you update the test plan accordingly?

**Comment by sitalkedia** [comment]
You might also want to add github workflow yaml file to let this run in continous mode?

**Comment by grao1991** [comment]
> @grao1991 - Do you have a successful run for this test? If so, can you point to the link? Also, can you update the test plan accordingly?

Not yet, some additional work are needed to make it work end to end.

**Comment by davidiw** [comment]
closing out stale PR

**Pull request closed without merging**
