### PR TITLE
[move] Update Move to 216acc8fdf1952d02f9c30fd1923647564add4a2

### PR DESCRIPTION
**Pull request by gregnazario**
This involved changing StructOpt -> clap for aptos-move. Additionally,
updated all usages of Move to the newer commit.

### CODE REVIEW

**Comment by msmouse** [comment]
The workspace hack has `clap = { version = "2.34.0", features = ["ansi_term", "atty", "color", "strsim", "suggestions", "vec_map"] }` 

how exactly does it work?

**Comment by gregnazario** [comment]
> The workspace hack has `clap = { version = "2.34.0", features = ["ansi_term", "atty", "color", "strsim", "suggestions", "vec_map"] }`
> 
> how exactly does it work?

I'm moving really fast, my computer is too slow to compile so I was hoping that the CI could give me feedback faster

**Comment by gregnazario** [comment]
Turns out all those weird functional tests in move are blocking this PR, and I'm not sure what to do to fix it.  I tried disabling them and that didn't seem to work.

**Comment by gregnazario** [comment]
@msmouse can you take a look?

**Comment by gregnazario** [comment]
Closing as we updated elsewhere

**Pull request closed without merging**
