### PR TITLE
refactor: deprecate JSON interface for txn submission

### PR DESCRIPTION
**Pull request by jjleng**
### Description
JSON txn submission interface will be removed from the following major SDK version. JSON interface requires signing messages to be prepared by the server, which is not very secure.

### Test Plan
Make sure all tests still pass.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2893)

### CODE REVIEW

**Comment by davidiw** [comment]
I feel mixed about this. On the one hand, we don't want folks to use it. At the same time, your ABI framework still isn't fully functional as it requires the source files. One could reason that you could always use the API as a middle ground. I also think it isn't horrible to show working code. Curious what Daniel and Greg think.

**Comment by jjleng** [comment]
Compared to getting ABI from https://fullnode.devnet.aptoslabs.com/accounts/0x1/modules, one advantage of using the ABI from the local compilation is that we can provide ABIs for scripts as well. Basically, Ethereum requires users to compile and provide ABIs. We want to keep people's habits unchanged.

To make you feel more confident to deprecate the JSON interface, going to support pull-down ABIs from https://fullnode.devnet.aptoslabs.com/accounts/0x1/modules for entry functions.

**Comment by jjleng** [comment]
@davidiw Now, we can do it https://github.com/aptos-labs/aptos-core/pull/3093. The limitation of remote JSON ABI is that it only supports ScriptFunction aka Entry Function payloads. Scripts are not stored on chain.

**Comment by jjleng** [comment]
Close in favor of https://github.com/aptos-labs/aptos-core/pull/3222

**Pull request closed without merging**
