### PR TITLE
Use updated docker compose command

### PR DESCRIPTION
**Pull request by dylanschultzie**
## Motivation

docker-compose is outdated, and will be updated to docker compose when updated.

### CODE REVIEW

**Review by davidiw — CHANGES_REQUESTED** [review]
interesting, on my machine `docker compose` and `docker-compose` both work. 
see https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose

the team is currently only evaluating docker-compose, so closing this out for now

**Comment by davidiw** [comment]
fyi @sherry-x ,  @rustielin for "docker compose" vs "docker-compose"

**Comment by dylanschultzie** [comment]
Hey @davidiw,

This was a question that came up a bunch on the incentivized testnet launch. If you install `docker` from latest, you only get `docker compose`. `docker-compose` appears to be no longer supported.

At the very least it'd be worth mentioning that installing the latest version of `docker` necessitates using `docker compose` to ease onboarding.

**Comment by davidiw** [comment]
If you want to adjust the pr, that'd be great.

**Comment by davidiw** [comment]
> Hey @davidiw,
> 
> This was a question that came up a bunch on the incentivized testnet launch. If you install `docker` from latest, you only get `docker compose`. `docker-compose` appears to be no longer supported.
> 
> At the very least it'd be worth mentioning that installing the latest version of `docker` necessitates using `docker compose` to ease onboarding.

@dylanschultzie  If you want to adjust the pr, that'd be great.

**Pull request closed without merging**
