### PR TITLE
Add check if collection exists

### PR DESCRIPTION
**Pull request by K-Pomian**
###Description

It is essential for a NFT marketplace to check if a creator has a collection in their collections resource to avoid a case when someone, who would like to list a collection in the marketplace, adds a not existing collection, hence creating potential huge amount of redundant and junky data.

###Test Plan

It is extracted and little modified code from create_collection function, therefore I don't expect it needs to be tested. Moreover, it doesn't write or modify any of the existing data.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2750)

### CODE REVIEW

**Comment by NorbertBodziony** [comment]
Chad work 🙏

**Review by davidiw — COMMENTED** [review]
while I have no concern about this, I do wonder if you could elaborate on the use case?

**Comment by davidiw** [comment]
> It is essential for a NFT marketplace to check if a creator has a collection in their collections resource to avoid a case when someone, who would like to list a collection in the marketplace, adds a not existing collection, hence creating potential huge amount of redundant and junky data.

Why is an NFT marketplace using move to make this query versus reading from storage (e.g., REST-based table query)?

**Comment by K-Pomian** [comment]
In my marketplace any user will be able to add any Collection being a resource under a PDA and address of the PDA is stored in a table. To avoid spamming with undesired collections, which all will be listed on the marketplace's website, I would like to check if such collection exists in the first place. To list a collection on the marketplace, a user has to provide creator address and collection name, so having those two I could have checked it if such function would exist.

**Comment by davidiw** [comment]
I don't understand what a website marketplace has to do with a move function. I added you on discord, let's chat more synchronously?

**Review by davidiw — APPROVED** [review]

**Comment by davidiw** [comment]
Good luck!

**Pull request merged**
