### PR TITLE
revert expected_tps for resource-groups-sender-multi-change1-kb

### PR DESCRIPTION
**Pull request by msmouse**
## Description

  regression has been fixed by https://github.com/aptos-labs/internal-ops/pull/3197         

and accidentally picked https://github.com/aptos-labs/aptos-core/pull/13249 up in this branch..

## Type of Change
- [x] Tests

## Which Components or Systems Does This Change Impact?
- [x] Other (specify) - test

## How Has This Been Tested?

test

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ ] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by msmouse** [comment]
* **#13283** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/13283?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @msmouse and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by igor-aptos — APPROVED** [review]

**Review by grao1991 — APPROVED** [review]

**Review by ibalajiarun — APPROVED** [review]

**Comment by msmouse** [comment]
(approved PR https://github.com/aptos-labs/aptos-core/pull/13249[)](https://github.com/aptos-labs/aptos-core/pull/13283/commits/f7ce9f4d389ba087e6081f27f6e0bbaeaf1985e6) accidentally merged into this.. would piggyback landing it instead of resending >_<)

**Comment by igor-aptos** [comment]
@msmouse go for it, just update the title/summary to reflect that both changes are included

**Comment by igor-aptos** [comment]
you can update summary, disable and then enable auto merge. shouldn't affect the test, but new title will be picked up (I think)

**Comment by msmouse** [comment]
@igor-aptos  disabled and re-initiated merge by rebase, so both titles will be kept in history

**Pull request merged**
