### PR TITLE
Node docs

### PR DESCRIPTION
**Pull request by rajkaramchedu**
@sherry-x Here is a first pass. After you add your stuff I will edit some more before we open it up for review.
A few notes:
1. The table in the Aptos Blockchain Deployments now has columns for mainnet and ll-testnet. The rows that has EDIT string are just placeholders for now. 
2. Gave a first pass at generalizing the leaderboard metrics doc.
3. Validators section is now three subsections, just like we talked.
4. The owner, operator and voter subsections are now really first pass placeholders. I worry if these pages are helpful for you to edit them or hinder you from adding anything, just because they don't have much structure. Tell me either way and I will iterate. 
5. All the flowcharts will either go away or will be reworked. 
6. Some landing page link fixes. 
7. All in all, I think we have a basic template for the node docs. Just need to iterate. 

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4572)

### CODE REVIEW

**Comment by rajkaramchedu** [comment]
Fixing broken links. Standby.

**Comment by rajkaramchedu** [comment]
Done fixing.

**Comment by rajkaramchedu** [comment]
@sherry-x See the second pass docs. Two points:
1. The validator landing page is now a placeholder. I will write up the concept level description shortly.
2. I renamed the "Additional Doc" to "Shutting down nodes". There is a "Add monitoring components" section here, and I wondering if we should move this to node liveness doc. 
~

**Comment by rajkaramchedu** [comment]
I still need to add a short section in the validator landing page describing the owner, operator and voter personas. Will do that later.

**Review by sherry-x — APPROVED** [review]

**Pull request merged**
