### PR TITLE
[Documentation] Testing Docs Structure.

### PR DESCRIPTION
**Pull request by rajkaramchedu**
I am creating this PR only to generate a developer preview. So, to help me think through how I am thinking of organizing the docs, I created the top nav bar. We do not yet have the right docs going into right categories, but I would like you to look at this from a directional point of view. Does this direction make sense? 

My goal is, by creating this test top-nav structure, it will help us identify how to:
1. Organize and refine existing docs.
2. Create new docs, 
so that we can present them for beginner, intermediate and advanced Aptos developer.
Also, 
1. The "Start Here" doc doesn't exist yet. The "mental model" doc I outlined in Notion will become this doc.
2. I want to distinguish "operator" docs (**Nodes** menu) from developer docs (everything other than **Nodes** menu). How do you feel about it?
3. I deliberately created menu items for "Dapps", "NFT" and "Wallet" figuring this will motivate us to spruce up docs in these categories. I foresee some of these being nuked into submenus as these categories grow. 
Thanks!

### CODE REVIEW

**Comment by davidiw** [comment]
Is this intended for review or just exploration still?

**Comment by rajkaramchedu** [comment]
> Is this intended for review or just exploration still?

Only exploration. I was thinking Draft would be safe enough for exploration phase? I will move it out of Draft mode only when ready for review.

**Comment by davidiw** [comment]
1. Please rebase, you're somehow pulling in a ton of commits
2. This does feel a bit busier -- maybe there are two many options on the top -- let's check with Monica and why isn't she on github 😭 
3. Per our conversation, let's try to be radically different on the top bar (Move, Applications, Nodes) -- not sure about the API
4. Start here -> getting-started

If we agree on 3, then we should then specify what we think is the story for those different identities and sort the entries per that story.

**Comment by rajkaramchedu** [comment]
Yes, somehow I managed to mess up this PR commits-wise. I will make a fresh PR and close this one. Agree with 3 and already spoke with Monica. Will follow up on the rest. Thanks!

**Pull request closed without merging**
