### PR TITLE
[aptos-move] Make parallel BlockSTM comparison testing an opt-in behavior

### PR DESCRIPTION
**Pull request by wrwg**
### Description

Until now, each Move e2e test was executed two times: one time using sequential block executor, and then a second time using the parallel BlockSTM, comparing the result.

This is a large overhead of roughly 2/3 of the execution time of each test in our growing test suite. Here is a comparsion of running times for one e2e test:

```
cargo test --release test_fee_collection_and_distribution_for_burn_percentage  

With parallel:     29.97s user 
Without parallel:  10.36s user 
```

In this PR, we make the default behavior of parallel comparsion testing dependent on an environment variable E2E_PARALLEL_EXEC: only if this set will the old behavior be maintained. This allows to run those tests still locally or in a nightly run. Also functions are added to explicitly opt-in or opt-out of parallel execution. Possibly some of the existing e2e tests should be turned on again even as CI blocker for PE.

### Test Plan

Existing stuff

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
fun, fun, agreed, running in a single thread should be sufficient for these tests -- except maybe the aggregator stuff? but if that's the case, we should probably move them to another crate.

out of curiosity is this happening in the other e2e tests?

**Comment by wrwg** [comment]
> nice find! and fun, fun, agreed, running in a single thread should be sufficient for these tests -- except maybe the aggregator stuff? but if that's the case, we should probably move them to another crate.
> 
> out of curiosity is this happening in the other e2e tests?

Every single one of our e2e tests ...

**Comment by gelash** [comment]
LGTM but @davidiw it's actually a good point regarding aggregators, since we do test within the block executor, but it also does take a different materialization path. I think @georgemitenkov had added some basic e2e tests - but to confirm if it would run just a single transaction in a block then that shouldn't matter much either. @georgemitenkov - does it make a difference for those? If yes, while we do test within the crate extensively but as far as outside of the block executor observing the right materialized value goes, maybe until we find a better place and if it's relevant, it could make sense to run parallel for those. 
@zekun000 @igor-aptos what thinks you?

**Review by zekun000 — APPROVED** [review]

**Comment by wrwg** [comment]
> LGTM but @davidiw it's actually a good point regarding aggregators, it does take a different materialization path. I think @georgemitenkov had added some basic e2e tests - but to confirm if it would run just a single transaction in a block then that shouldn't matter much either. @georgemitenkov - does it make a difference for those? If yes, while we do test within the crate extensively but as far as outside of the block executor observing the right materialized value goes, maybe until we find a better place and if it's relevant, it could make sense to run parallel for those. @zekun000 @igor-aptos what thinks you?

I added the tools for you to (a) make those tests you want to run parallel by simple adding `harness.set_parallel(()` to the test setup. I can't know which those are, so please followup with another PR (b) to run all tests in a nightly by setting env var E2E_PARALLEL_EXEC. Hope this is sufficient.

**Comment by gelash** [comment]
> > LGTM but @davidiw it's actually a good point regarding aggregators, it does take a different materialization path. I think @georgemitenkov had added some basic e2e tests - but to confirm if it would run just a single transaction in a block then that shouldn't matter much either. @georgemitenkov - does it make a difference for those? If yes, while we do test within the crate extensively but as far as outside of the block executor observing the right materialized value goes, maybe until we find a better place and if it's relevant, it could make sense to run parallel for those. @zekun000 @igor-aptos what thinks you?
> 
> I added the tools for you to (a) make those tests you want to run parallel by simple adding `harness.set_parallel(()` to the test setup. I can't know which those are, so please followup with another PR (b) to run all tests in a nightly by setting env var E2E_PARALLEL_EXEC. Hope this is sufficient.

perfect, thank you!

**Pull request merged**
