### PR TITLE
[State Sync] Add new state sync v2 dashboard.

### PR DESCRIPTION
**Pull request by JoshLind**
## Motivation

This PR adds a new (basic) metrics dashboard for state sync v2, including panels for: the state sync driver, the data streaming service, the data client and the storage service. See the screenshot below for an example: 

Screen Shot 2022-04-17 at 11 17 00 PM

Once this lands, I'll consider iterating on some things, but I wanted to get an initial version landed first.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Viewed the dashboard manually.

## Related PRs

None.

### CODE REVIEW

**Comment by JoshLind** [comment]
@sherry-x, is there anything special I need to do to get this rolled out for both validators and fullnodes? As far as I understand it, this is the only dashboard terraform we have, right? i.e., I don't need to add it to another location in our codebase?

**Comment by sherry-x** [comment]
@JoshLind fullnode symlink some of the dashboard into the different helm chart here https://github.com/aptos-labs/aptos-core/tree/main/terraform/fullnode/aws/fullnode/files/dashboards

**Comment by sherry-x** [comment]
And btw this looks so pretty! love the request latency graph!

**Comment by rustielin** [comment]
Nice work! Just the link into the other helm chart :)

Separately, @sherry-x  we should probably move all the charts to a more obvious place at a higher level directory, and just link the entire directory. Docker-compose FN monitoring is also not getting too much love https://github.com/aptos-labs/aptos-core/tree/main/docker/compose/monitoring/grafana/dashboards

**Comment by JoshLind** [comment]
@sherry-x & @rustielin, thanks! Done. Hopefully I did it right 😆 

> Separately, @sherry-x we should probably move all the charts to a more obvious place at a higher level directory, and just link the entire directory.

Agree, if this is possible it would be awesome. It'll mean we get every dashboard automatically for FN deployments (even if we don't need them). Likewise, adding a new dashboard won't require the symlink 😄

**Review by sherry-x — APPROVED** [review]

**Comment by JoshLind** [comment]
Thanks all!

/land

**Comment by rustielin** [comment]
> Agree, if this is possible it would be awesome. It'll mean we get every dashboard automatically for FN deployments (even if we don't need them). Likewise, adding a new dashboard won't require the symlink 😄

Tracking this in a new issue https://github.com/aptos-labs/aptos-core/issues/543

**Comment by maksonn4ik** [comment]
How to add new dashboard ? Open node in docker ?
Вт, 19 апр. 2022 г. в 00:28, Rustie Lin ***@***.***>:

**Pull request closed without merging**
