### PR TITLE
[Sharded-Execution] Fix a race condition while fetching the state values on a shard from a remote stateview

### PR DESCRIPTION
**Pull request by manudhundi**

### CODE REVIEW

**Comment by msmouse** [comment]
why not insert before sending the request, or remove at all?

**Comment by manudhundi** [comment]
> why not insert before sending the request, or remove at all?

(1) Not insert before sending the request because that reduces parallelism. Currently when we insert the keys, we also have job(s) making the remote requests in parallel.
(2) If we don't at all insert during send request, then we will end up making multiple remote calls during get_state_value().

Reason (2) is more critical than reason (1)

**Comment by sitalkedia** [comment]
> > why not insert before sending the request, or remove at all?
> 
> (1) Not insert before sending the request because that reduces parallelism. Currently when we insert the keys, we also have job(s) making the remote requests in parallel. (2) If we don't at all insert during send request, then we will end up making multiple remote calls during get_state_value().
> 
> Reason (2) is more critical than reason (1)

Actually @msmouse has a good point, can we insert the key before sending the fetch request asynchronously? That probably is a cleaner option?

**Comment by manudhundi** [comment]
> > > why not insert before sending the request, or remove at all?
> > 
> > 
> > (1) Not insert before sending the request because that reduces parallelism. Currently when we insert the keys, we also have job(s) making the remote requests in parallel. (2) If we don't at all insert during send request, then we will end up making multiple remote calls during get_state_value().
> > Reason (2) is more critical than reason (1)
> 
> Actually @msmouse has a good point, can we insert the key before sending the fetch request asynchronously? That probably is a cleaner option?

Yes cleaner option indeed. But we are not as parallel as before. That is, we are not leveraging the IO time to do some work like before. But, writing keys to a hashtable in memory is pretty fast, so it will not matter so much.

I will put out a commit as per Alden's proposal

**Review by sitalkedia — APPROVED** [review]

**Review by sitalkedia — APPROVED** [review]

**Review by msmouse — APPROVED** [review]

**Pull request merged**
