### PR TITLE
[move] Remove legacy type builder

### PR DESCRIPTION
**Pull request by georgemitenkov**
## Description
 
The feature to limit VM type sizes has been enabled, so this PR removes the legacy type builder implementation.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [x] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by vgao1996 — COMMENTED** [review]
Have we checked if it's safe to remove the old behavior through replay?

**Comment by georgemitenkov** [comment]
@vgao1996 Yes when we selected the limits for the type builder, but there is a chance that some transaction before that and actual release can break things. I would prefer to land it and see if replay passes on main, to save some CI money, and if not, revert. Does this sound good?

Also, maybe we can select a range for the replay (only from the last tested txn, @perryjrandall do you know how I specify that in replay action?)

**Review by vgao1996 — APPROVED** [review]
Yeah if we didn't catch anything last time then I'd be fine taking a bet.

**Comment by perryjrandall** [comment]
> @vgao1996 Yes when we selected the limits for the type builder, but there is a chance that some transaction before that and actual release can break things. I would prefer to land it and see if replay passes on main, to save some CI money, and if not, revert. Does this sound good?
> 
> Also, maybe we can select a range for the replay (only from the last tested txn, @perryjrandall do you know how I specify that in replay action?)

Currently its not really easily possible @aluon it would be great to have a job which could just run a single range instead of the full range in case someone knows which txns they want to test

**Review by runtian-zhou — APPROVED** [review]
Awesome thanks for cleaning it up!

**Pull request merged**
