### PR TITLE
Reorganize Aptos.dev navigation and page titles to match

### PR DESCRIPTION
**Pull request by clay-aptos**
### Description

Completely overhaul the navigation of Aptos.dev to be based upon critical user journeys, namely personas, their goals, and the tasks needed to achieve them.

### Test Plan

1. Local build and test.
2. Build and test in CI.
3. Have broader team review.
4. Iterate on feedback here.
5. Announce in What's New.
6. Approve and publish.
7. Collect user feedback.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5556)

### CODE REVIEW

**Review by movekevin — APPROVED** [review]

**Review by geekflyer — APPROVED** [review]

**Comment by geekflyer** [comment]
can't wait for this to land! 😄

**Comment by davidiw** [comment]
There's a lot to dig through in terms of code, so gonna leave feedback here:
* Prepare environment -> Get Started
* Integrate Aptos -> Build on Aptos
* Conduct tutorials -> (Developer) Tutorials

Good otherwise!

**Comment by clay-aptos** [comment]
> There's a lot to dig through in terms of code, so gonna leave feedback here:
> 
> * Prepare environment -> Get Started
> * Integrate Aptos -> Build on Aptos
> * Conduct tutorials -> (Developer) Tutorials
> 
> Good otherwise!

Just to be clear, that would create these paths:
Start Aptos
  Get Started
Build Apps
  Build on Aptos
  Developer Tutorials
  
The first two seem redundant and imprecise, while the Developer Tutorials breaks with the Verb > Noun action I am attempting to induce. :-) That said, I am all about compromise and so will make these changes for you to see.

**Comment by clay-aptos** [comment]
> * Conduct

@davidiw , I have made your changes. Please see:
https://deploy-preview-5556--aptos-developer-docs.netlify.app/nodes/identity-and-configuration/

**Comment by clay-aptos** [comment]
> > * Conduct
> 
> @davidiw , I have made your changes. Please see: https://deploy-preview-5556--aptos-developer-docs.netlify.app/nodes/identity-and-configuration/

Kevin gave me the go ahead to go with my heart. We can iterate.

**Comment by clay-aptos** [comment]
Screen Shot 2022-11-17 at 9 25 20 AM

Adding a before pic here for posterity.

**Pull request merged**
