### PR TITLE
Add .js file extension to imports

### PR DESCRIPTION
**Pull request by macalinao**
### Description

This makes imports work with Node's ES Module system.

### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3459)

### CODE REVIEW

**Comment by macalinao** [comment]
> @macalinao Hi Ian, we are going to bundle the SDK. see #2851

Nice-- regardless, I think this would still be a useful change to enforce that the code works with ES Modules going forward

**Comment by jjleng** [comment]
The problem is that we also have many generated files and CI will regenerate if needed. To get those files follow this would require some extra work.

With https://github.com/aptos-labs/aptos-core/pull/2851, you will get an ESM bundle. You can then do the ESM imports in Node. Does that work for you?

**Comment by macalinao** [comment]
> The problem is that we also have many generated files and CI will regenerate if needed. To get those files follow this would require some extra work.
> 
> With #2851, you will get an ESM bundle. You can then do the ESM imports in Node. Does that work for you?

The regeneration is addressed by https://github.com/aptos-labs/aptos-core/pull/3458

I'll check to see how my bundle sizes look with #2851

**Comment by macalinao** [comment]
Also I don't think this hurts-- see https://nodejs.org/api/esm.html#mandatory-file-extensions 

This should be done eventually

**Review by davidiw — APPROVED** [review]
good for me

**Comment by jjleng** [comment]
@macalinao Hi Ian, would definitely want to help here. https://github.com/aptos-labs/aptos-core/pull/3458 looks good.

But can you please share how you use the SDK? Are you using the public SDK from the npm registry? Or are you currently building the SDK from the source?  I am worried https://github.com/aptos-labs/aptos-core/pull/2851 might not be able to solve your problem.

Let me summarize the ESM and CommonJS here. And see if we can find a solution for your case.

We use the typescript transpiler. The `import X from Y` or `import X from Y.js` matters to the Typescript transpiler (to be specific, the `moduleResolution` option). The transpiled JS use either `import` or `require` which is decided by the `module` option of TS. What you do care here is the imports in transpiled JS, right? Our current SDK produces CommonJS JS files. That means, you are dealing with CommonJS package if you use the public SDK. Even we land the PR here, it doesn't do what you want it to do if you use the public SDK.

With https://github.com/aptos-labs/aptos-core/pull/2851, everything is bundled together. The `import`'s are are replaced by bundler (in our case, rollup). So these `import X from Y.js` don't matter anymore. https://github.com/aptos-labs/aptos-core/pull/2851 has two issues. By default, it is still a CommonJS module. We can make it a true dual module by leveraging the `aptos.esm.js`. However, the dependencies of `aptos.esm.js`, such as the `js-sha3`, are CommonJS modules by default. This makes `aptos.esm.js` not work as expected. 

Therefore, most likely, we will continue to ship CommonJS SDK. We are eager to help you with your case. We can land your PR, but don't know how much it can help. Let me know and we want to help.

**Comment by macalinao** [comment]
> @macalinao Hi Ian, would definitely want to help here. #3458 looks good.
> 
> But can you please share how you use the SDK? Are you using the public SDK from the npm registry? Or are you currently building the SDK from the source? I am worried #2851 might not be able to solve your problem.
> 
> Let me summarize the ESM and CommonJS here. And see if we can find a solution for your case.
> 
> We use the typescript transpiler. The `import X from Y` or `import X from Y.js` matters to the Typescript transpiler (to be specific, the `moduleResolution` option). The transpiled JS use either `import` or `require` which is decided by the `module` option of TS. What you do care here is the imports in transpiled JS, right? Our current SDK produces CommonJS JS files. That means, you are dealing with CommonJS package if you use the public SDK. Even we land the PR here, it doesn't do what you want it to do if you use the public SDK.
> 
> With #2851, everything is bundled together. The `import`'s are are replaced by bundler (in our case, rollup). So these `import X from Y.js` don't matter anymore. #2851 has two issues. By default, it is still a CommonJS module. We can make it a true dual module by leveraging the `aptos.esm.js`. However, the dependencies of `aptos.esm.js`, such as the `js-sha3`, are CommonJS modules by default. This makes `aptos.esm.js` not work as expected.
> 
> Therefore, most likely, we will continue to ship CommonJS SDK. We are eager to help you with your case. We can land your PR, but don't know how much it can help. Let me know and we want to help.

After this is merged, it'll be clearer if TSDX is sufficient: https://github.com/aptos-labs/aptos-core/pull/3840 (it probably is)

I'm currently building the SDK from source to minimize bundle size via use of ESM. Bundlers will only do this if `type: module` is present in package.json.

**Comment by jjleng** [comment]
See https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/typescript/sdk/examples/typescript-esm for how to use Aptos SDK as an ESM.

**Pull request closed without merging**
