### PR TITLE
[move errors] Adapt to new Error variant with message

### PR DESCRIPTION
**Pull request by wrwg**
Updates existing code to compile with the additional error message field now supported by the VM. This is not yet a functional change, as the new information isn't used/populated yet

### CODE REVIEW

**Comment by wrwg** [comment]
> Why not just add the messages for these instead of None? This way we wouldn’t forget these (easier to find when things don’t compile)

 Right now we are blocked to sync with the move repo. Let’s land this first. There is a lot more work to even show these messages, and most of what you see here will likely not have any. Besides there is no issue to find those places here.

**Comment by movekevin** [comment]
> > Why not just add the messages for these instead of None? This way we wouldn’t forget these (easier to find when things don’t compile)
> 
> Right now we are blocked to sync with the move repo. Let’s land this first. There is a lot more work to even show these messages, and most of what you see here will likely not have any. Besides there is no issue to find those places here.

I don’t think it’s more than half a day of work at most. Cost wise, it’s better to finish this than leaving more work left to do later

**Comment by movekevin** [comment]
> > > Why not just add the messages for these instead of None? This way we wouldn’t forget these (easier to find when things don’t compile)
> > 
> > 
> > Right now we are blocked to sync with the move repo. Let’s land this first. There is a lot more work to even show these messages, and most of what you see here will likely not have any. Besides there is no issue to find those places here.
> 
> I don’t think it’s more than half a day of work at most. Cost wise, it’s better to finish this than leaving more work left to do later (tracking, finding someone to work on). Plus, adding these messages will be very impactful

**Comment by wrwg** [comment]
> > > > Why not just add the messages for these instead of None? This way we wouldn’t forget these (easier to find when things don’t compile)
> > > 
> > > 
> > > Right now we are blocked to sync with the move repo. Let’s land this first. There is a lot more work to even show these messages, and most of what you see here will likely not have any. Besides there is no issue to find those places here.
> > 
> > 
> > I don’t think it’s more than half a day of work at most. Cost wise, it’s better to finish this than leaving more work left to do later (tracking, finding someone to work on). Plus, adding these messages will be very impactful

There will be zero impact adding this messages because we have not implemented yet how they are exposed to the various layer of the system, including how to avoid they become part of the kept state. Moreover, its a weekend and I have no plan to spend 1/2 day on this. But we must unblock syncing to the Move repo since there is other work, e.g. the prover. Or should we rollback, like you did before, the change in the Move repo?

I suggest you leave it to me in which pace this work is done instead of trying to micro-control the work here...

**Review by msmouse — APPROVED** [review]

**Review by vgao1996 — APPROVED** [review]

**Pull request merged**
