### PR TITLE
Use pnpm for the dev docs site

### PR DESCRIPTION
**Pull request by banool**
### Description
We're experimenting with moving to pnpm over yarn: https://aptos-org.slack.com/archives/C03N83P7QUC/p1667514786627619. Starting from the top with the dev docs site.

I used `pnpm import`.

### Test Plan
I tested locally, now we check to see that netlify builds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5441)

### CODE REVIEW

**Comment by banool** [comment]
@clay-aptos Interested in your thoughts on this. For context, we're trying to move from `yarn` to `pnpm`. All this means to you is you use `pnpm` instead of `yarn`, it is a drop in replacement. So `pnpm start` instead of `yarn start` for example.

**Comment by clay-aptos** [comment]
> @clay-aptos Interested in your thoughts on this. For context, we're trying to move from `yarn` to `pnpm`. All this means to you is you use `pnpm` instead of `yarn`, it is a drop in replacement. So `pnpm start` instead of `yarn start` for example.

I'm fine with this assuming we can test thoroughly. I recall when Christian enabled `pnpm` globally a few weeks ago it broke docs builds. I assume your change would address that, so please proceed and simply let me know when done. I will update our README to reflect the change:
https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/README.md

Thanks for including me!

**Comment by banool** [comment]
This should not cause the same issue as a few weeks ago, but I'll test thoroughly.

**Review by clay-aptos — APPROVED** [review]
Thanks, Daniel!

**Review by rustielin — APPROVED** [review]

**Pull request merged**
