### PR TITLE
[move] fix dumping the bytecode for smart contracts containing inline functions (#9065)

### LINKED ISSUE #9065: [Bug] Panic when dumping the bytecode for smart contracts containing inline functions
# 🐛 Bug

When executing the command `aptos move prove -f delegation_pool.move --dump` in the `aptos-framework` directory, Aptos CLI will panic:

```
thread 'tokio-runtime-worker' panicked at 'attempt to get bytecode function target for inline function', third_party/move/move-prover/bytecode/src/function_target_pipeline.rs:228:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
{
  "Error": "Unexpected error: task 11 panicked"
}
```

### PR DESCRIPTION
**Pull request by aalok-t**
### Description

Update dumping functions to ignore inline function environments. Close #9065

### CODE REVIEW

**Review by rahxephon89 — APPROVED** [review]
LGTM, thanks!

**Review by junkil-park — APPROVED** [review]
LGTM.

**Review by vineethk — APPROVED** [review]
lgtm.

**Comment by brmataptos** [comment]
Too late now, but it would be good to add a test for fixed issues to detect regressions in the future.  This one requires some manual test right now.

**Pull request merged**
