### PR TITLE
[Consensus] Configure round timeout from 1s -> 1.5s

### PR DESCRIPTION
**Pull request by sitalkedia**
### Description

We have seen 1s timeout causes many local timeouts in real-world network conditions.  Increasing the default to 1.5s instead. 

### Test Plan

Have been tested in AIT2 and helped reduced the local timeout by 50%.

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2078)

### CODE REVIEW

**Comment by zekun000** [comment]
I don't think we should change the default value, it's a network by network thing. we probably should increase the leader timeout by 1.5

**Comment by sitalkedia** [comment]
@zekun000 - Given we have 300 ms network latency and 500 ms broadcast latency, the 1s threshold seems pretty tight for a real-world network. For example for main-net, we will see similar latency I believe. Making this default will ensure all of our tests are using the same configuration as production as possible. We can separately have a change to increase the leader timeout to 2s. LMK your thoughts on it.

**Comment by zekun000** [comment]
I think it's too early to say that 300/500 number is real-network network, they both seem on the higher end to me. Setting higher timeout value has implications on performance, when there's indeed bad leaders, it'll delay the latency significantly.

**Comment by grao1991** [comment]
> I think it's too early to say that 300/500 number is real-network network, they both seem on the higher end to me. Setting higher timeout value has implications on performance, when there's indeed bad leaders, it'll increase the latency significantly.

Should we use AIT as an opportunity to get a better understanding on how this timeout affects the performance? By setting this to a larger threshold we can probably know "given threshold X, the probability p(X) of having a bad leader when we observe timeout".

**Comment by sitalkedia** [comment]
>> I think it's too early to say that 300/500 number is real-network network, they both seem on the higher end to me.

5 seconds is definitely a very high number but how do you suggest we get the real-world network latency to tune this value?

**Comment by zekun000** [comment]
there's two things we can try before bumping the default value.
- bump the timeout for leaders
- investigate the 300/500ms numbers, we can compare health check rpc to estimate the latency and need some tracing to understand the broadcast overhead

**Comment by sitalkedia** [comment]
@zekun000 - As discussed offline, I would like to increase this default for AIT3 and we can reevaluate this for `mainnet` - thoughts?

**Review by zekun000 — APPROVED** [review]

**Pull request merged**
