### PR TITLE
Print detailed fee statement for gov proposal simulation

### PR DESCRIPTION
**Pull request by vineethk**
## Description

When simulating gov. proposals, it is often useful to see detailed fee statement instead of just the total gas used. This PR prints that information.

Here is a sample output of a gov. proposal simulation after this PR:

```
Executing governance scripts...
    0-gas-schedule.move
        Fee statement: FeeStatement {
            total_charge_gas_units: 229,
            execution_gas_units: 39,
            io_gas_units: 57,
            storage_fee_octas: 13360,
            storage_fee_refund_octas: 0,
        }
        Success
    1-move-stdlib.move
        Fee statement: FeeStatement {
            total_charge_gas_units: 1161,
            execution_gas_units: 77,
            io_gas_units: 105,
            storage_fee_octas: 97880,
            storage_fee_refund_octas: 0,
        }
        Success
    2-aptos-stdlib.move
        Fee statement: FeeStatement {
            total_charge_gas_units: 1670,
            execution_gas_units: 1498,
            io_gas_units: 123,
            storage_fee_octas: 4960,
            storage_fee_refund_octas: 0,
        }
        Success
    3-aptos-framework.move
        Fee statement: FeeStatement {
            total_charge_gas_units: 4401,
            execution_gas_units: 3860,
            io_gas_units: 163,
            storage_fee_octas: 37800,
            storage_fee_refund_octas: 0,
        }
        Success
    4-aptos-token.move
        Fee statement: FeeStatement {
            total_charge_gas_units: 144,
            execution_gas_units: 68,
            io_gas_units: 76,
            storage_fee_octas: 0,
            storage_fee_refund_octas: 0,
        }
        Success
    5-aptos-token-objects.move
        Fee statement: FeeStatement {
            total_charge_gas_units: 151,
            execution_gas_units: 74,
            io_gas_units: 77,
            storage_fee_octas: 0,
            storage_fee_refund_octas: 0,
        }
        Success
All scripts succeeded!
All proposals succeeded!
```

## How Has This Been Tested?

Manually ran the scripts with a couple of options. The output of one of them is posted above.

## Type of Change
- [x] Refactoring

## Which Components or Systems Does This Change Impact?
- [x] Governance proposal simulation

### CODE REVIEW

**Comment by vineethk** [comment]
* **#15363** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15363?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15363?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by vgao1996 — APPROVED** [review]
Wondering if it's still clearer to keep the indentation but I guess it's more of a personal preference.

In the future we should probably introduce some sort of structural logging and make that the standard practice.

**Review by rahxephon89 — APPROVED** [review]

**Comment by vineethk** [comment]
> Wondering if it's still clearer to keep the indentation but I guess it's more of a personal preference.

When printing the fee statement, keeping the indentation might have required custom implementations (instead of the `format!("{:#?}")`) to add the leading padding - did not seem worth the complication.

> In the future we should probably introduce some sort of structural logging and make that the standard practice.

Agree.

**Comment by vgao1996** [comment]
@vineethk agreed on the downsides. Although for this particular case I've found it easier to just add the indents at the string level.

**Comment by vineethk** [comment]
> @vineethk agreed on the downsides. Although for this particular case I've found it easier to just add the indents at the string level.

Can you add indent padding to each line of a struct debug display (note that `{:#?}` prints each field on a new line)?

**Comment by vgao1996** [comment]
@vineethk yeah, I did this already in the code a few lines below
```
                    format!("{:#?}", txn_status)
                        .lines()
                        .map(|line| format!("        {}", line))
                        .collect::<Vec<_>>()
.join("\n")
```
Far from being efficient, but it works

**Comment by vineethk** [comment]
@vgao1996 

> Far from being efficient, but it works

Fair enough. I looked at things like `println!("{:>8}!", "m")` etc to see if there was someway to add padding more declaratively, but did not find anything. I have adopted your solution, especially because we already do this.

I've reverted the changes that removed padding elsewhere.

**Pull request merged**
