### PR TITLE
[fullnode] add gcp folder for fullnode terraform

### PR DESCRIPTION
**Pull request by sherry-x**
Restructure our fullnode terraform folder a bit to split aws implementation and other cloud implementation.
```
|_terraform
    |_fullnode
        |_aws
        |_gcp
```

### CODE REVIEW

**Review by rustielin — APPROVED** [review]

**Comment by rustielin** [comment]
The `gcp` folder won't get committed since it's empty, but at least this handles the rename to `fullnode/aws`.

Also was it your intention to move the helm chart under `aws` as well?

**Comment by sherry-x** [comment]
@rustielin yes, that helm chart is pretty specific with aws things for now. will need to cleanup later

**Pull request merged**
