### PR TITLE
[SDK][API] Remove event key endpoint / client code

### PR DESCRIPTION
**Pull request by banool**
### Description
This PR follows up on the previously announced deprecation to remove the event key.

Remaining work:
- ~Update the TS SDK.~
- ~Migrate / redo from scratch the indexer DB schema. I've already done the code (including PK) side.~ I spoke with Bowen and he updated the base schema.
- ~Update changelogs.~
- Ensure this won't cause issues with compat testing, a la https://www.notion.so/aptoslabs/Release-and-Compatibility-5f6fc1fe90164e9ba53e7a0637c90e6e (see the link at the end there). We're probably still (erroneously in my opinion, as described in that doc) trying to use client tooling / CI built from main against testnet.

### Test Plan
In the TS SDK directory:
```
yarn test
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4338)

### CODE REVIEW

**Review by gregnazario — APPROVED** [review]
Please only push after the next SDK release I think?

**Review by bowenyang007 — APPROVED** [review]

**Comment by banool** [comment]
Originally we decided to do it this release @gregnazario, but given timelines I think we can afford to wait another week 👍

**Comment by banool** [comment]
Spoke with Bowen offline, he'll split out the indexer side of the changes here into a separate PR which we can land now.

**Comment by banool** [comment]
See https://github.com/aptos-labs/aptos-core/pull/4353.

**Review by davidiw — APPROVED** [review]
good bye you awful creature...

**Pull request merged**
