### PR TITLE
Incorporate How Base Gas Works doc into dev site

### PR DESCRIPTION
**Pull request by clay-aptos**
### Description

Incorporate docs from:
https://github.com/aptos-labs/aptos-core/pull/4680

### Test Plan

Manual review and testing

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4720)

### CODE REVIEW

**Review by rajkaramchedu — APPROVED** [review]
Awesome, thanks!

**Comment by alnoki** [comment]
For reference, the [Aptos Concepts](https://aptos.dev/concepts/aptos-concepts) page includes the "How Base Gas Works" link which is not in the sidebar, and excludes the "Coin and Token" sidebar item. Also I assume the sidebar modifications address the sidebar not showing up on the [How Base Gas Works](https://aptos.dev/concepts/base-gas) page, but I figured I'd mention here for reference that presently there is no navigation sidebar on the left.

**Comment by rajkaramchedu** [comment]
> For reference, the [Aptos Concepts](https://aptos.dev/concepts/aptos-concepts) page includes the "How Base Gas Works" link which is not in the sidebar, and excludes the "Coin and Token" sidebar item. Also I assume the sidebar modifications address the sidebar not showing up on the [How Base Gas Works](https://aptos.dev/concepts/base-gas) page, but I figured I'd mention here for reference that presently there is no navigation sidebar on the left.

Yes, thanks, @alnoki Clay is fixing that in this PR.

**Comment by alnoki** [comment]
> 

Got it, thanks. @clay-aptos also it looks like the `OR` operators in the [Boolean](https://aptos.dev/concepts/base-gas#boolean) and [Bitwise](https://aptos.dev/concepts/base-gas#bitwise) don't escape the same way on Docusaurus as they do in pure markdown, but I don't see a problem with any of the other monospace.

**Comment by clay-aptos** [comment]
> > 
> 
> Got it, thanks. @clay-aptos also it looks like the `OR` operators in the [Boolean](https://aptos.dev/concepts/base-gas#boolean) and [Bitwise](https://aptos.dev/concepts/base-gas#bitwise) don't escape the same way on Docusaurus as they do in pure markdown, but I don't see a problem with any of the other monospace.

I am trying to address the `OR` operator formatting in:
https://github.com/aptos-labs/aptos-core/pull/4736

> 
> ... and unfortunately none of the LaTeX in the [Storage gas](https://aptos.dev/concepts/base-gas#storage-gas) is showing up on Docusaurus either. @rajkaramchedu Can this be turned on via a site-wide configuration or similar?

**Comment by clay-aptos** [comment]
@alnoki as an FYI

**Pull request merged**
