### PR TITLE
[tf][testnet] custom grafana datasources

### PR DESCRIPTION
**Pull request by rustielin**
Custom datasources for testnet grafana, other than the local one that uses federation.

```
# do something like
        datasources = [
          {
            name = "Remote Prometheus"
            config = {
              type   = "prometheus"
              access = "proxy"
              url    = "<URL>"
            }
            jsonData = {
              ...
            }
          }
        ]
```

### CODE REVIEW

**Comment by davidiw** [comment]
looks good, what's the application?

**Comment by rustielin** [comment]
> looks good, what's the application?

@davidiw looking to replace the monitoring stack for Forge. This just adds the ability to add an alternative, along with the the previous ability to have validators' prometheus do `remote_write`

**Review by sherry-x — APPROVED** [review]

**Pull request merged**
