### PR TITLE
[doc] data-retention.md

### PR DESCRIPTION
**Pull request by msmouse**
### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4957)

### CODE REVIEW

**Review by JoshLind — COMMENTED** [review]
Awesome, thanks @msmouse! 😄 @rajkaramchedu, how do you feel about taking this PR over and prettifying it? AFAICT, all the information is there. We just need to make the language consistent with the rest of the site. Alternatively, we could approve and you could follow up with some tweaks? Thoughts?

**Comment by rajkaramchedu** [comment]
> Awesome, thanks @msmouse! 😄 @rajkaramchedu, how do you feel about taking this PR over and prettifying it? AFAICT, all the information is there. We just need to make the language consistent with the rest of the site. Alternatively, we could approve and you could follow up with some tweaks? Thoughts?

I will do it in a few minutes, thanks, @msmouse! I will move this doc from concepts category to guides category. Will push updates in an hour.

**Comment by rajkaramchedu** [comment]
Doc preview: https://deploy-preview-4957--aptos-developer-docs.netlify.app/guides/data-retention

**Review by JoshLind — APPROVED** [review]
LGTM. There's a couple typos, but I can send out a follow up if @rajkaramchedu isn't able to 😄

**Pull request merged**
