### PR TITLE
[docker] add indexer image

### PR DESCRIPTION
**Pull request by rustielin**
Build and copy `aptos-indexer` binary. Install `libpq-dev` and build as before

Unblock indexer TF module https://github.com/aptos-labs/aptos-core/pull/475

### CODE REVIEW

**Review by CapCap — APPROVED** [review]

**Comment by sherry-x** [comment]
The two consecutive docker build failure looks suspicious, is there any log we can see why the build failed?

**Comment by rustielin** [comment]
> The two consecutive docker build failure looks suspicious, is there any log we can see why the build failed?

Yea there's links to the Codebuild in the job logs. Looks like it's because of libpq since we're building `aptos-indexer` in all our images now via `docker/build-common.sh` ://

**Comment by rustielin** [comment]
forgot to include `libpq-dev` in the production image :p 

/land

**Pull request merged**
