### PR TITLE
[compiler] Restore aptos-move/aptos-transactional-test-harness

### PR DESCRIPTION
**Pull request by brmataptos**
### Description

Resurrect aptos-move/aptos-transactional-test-harness, addressing Issue #11154.
- Revert "[move] remove aptos transactional test (#9835)"
- Remove the CLI feature, keeping the testing infrastructure
- fix build issues found upon revert

### Test Plan
- added an diamond_clicker test (based on Issue #8614) to try to test it
- ran existing tests in dir

### CODE REVIEW

**Review by gregnazario — COMMENTED** [review]
Is someone going to maintain the transactional test harness?  Does it need to be in the Aptos CLI?

**Comment by brmataptos** [comment]
> Is someone going to maintain the transactional test harness? Does it need to be in the Aptos CLI?

What do you mean by "Aptos CLI"?

From my perspective, this directory is an internal dev facing resource, a place to put functionality tests in Move that need to be run in the Aptos world.  (Similar to third_party/move/move-compiler/transactional-tests/, but with aptos_stdlib and aptos-specialized VM.)  e2e-tests sounds nice but requires too much boilerplate when all you want is to test/debug Move language issues that show up when built/run with Aptos Libs+VM but not vanilla Move Libs+VM.

**Review by gregnazario — APPROVED** [review]
Doesn't add to the Aptos CLI, but adds it elsewhere, as long as tests pass let's ship it!

**Review by vgao1996 — APPROVED** [review]
The PR looks good but please double check the failed tests. It seems like there are some build errors now?
```
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/1.72.1-x86_64-unknown-linux-gnu/bin/cargo metadata --format-version=1 --manifest-path /runner/_work/aptos-core/aptos-core/Cargo.toml` (exit status: 101)
--- stderr
error: failed to load manifest for workspace member `/runner/_work/aptos-core/aptos-core/aptos-move/aptos-transactional-test-harness`

Caused by:
  failed to parse manifest at `/runner/_work/aptos-core/aptos-core/aptos-move/aptos-transactional-test-harness/Cargo.toml`

Caused by:
  error inheriting `aptos-state-view` from workspace root manifest's `workspace.dependencies.aptos-state-view`

Caused by:
  `dependency.aptos-state-view` was not found in `workspace.dependencies`
```

**Pull request merged**
