### PR TITLE
gitignore VSCode

### PR DESCRIPTION
**Pull request by jjleng**
## Motivation

Exclude .vscode files from git checkins

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

No

### CODE REVIEW

**Review by msmouse — APPROVED** [review]

**Comment by movekevin** [comment]
I think this should be added to individual global gitignore file and not to the repo since people might be using different IDEs.

See https://gist.github.com/subfuzion/db7f57fff2fb6998a16c for more details

**Comment by jjleng** [comment]
I am afraid I don't agree with https://gist.github.com/subfuzion/db7f57fff2fb6998a16c. It mentioned it's a bad practice to include editor and OS specific files, but it didn't tell why. Following the guide would introduce more inconveniences than benefits.

Most .gitignore are < 100 lines. Trying to optimize them is an overkill. The guide's practices introduce more troubles than benefits. The guide dictates every developer to do this on their local environment. A human error (someone forgets to config locally) would lead to unwanted files get checked in. Switching a work ing device would also require another config, which is unnecessary troubles. 

Content of .gitignore is not meant to fit itself into a project's context. It's meant to exclude any files that you don't want to checkin. I would say the guide probably violated the practices of 90% existing .gitignore files. Most of .gitignore files have ".idea/" (IDE), .DS_Store (OS) entries. Our repo's .gitgnore has many IDE and OS entires.

**Pull request closed without merging**
