### PR TITLE
[replay-verify] update ranges

### PR DESCRIPTION
**Pull request by sausagee**
## Description
Update the ranges of replay-verify

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [x] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [x] Other (specify): CI

## How Has This Been Tested?
Canaries passed
mainnet https://github.com/aptos-labs/aptos-core/actions/runs/10731961176
testnet https://github.com/aptos-labs/aptos-core/actions/runs/10782729026

## Key Areas to Review
CI config

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [n/a] I tested both happy and unhappy path of the functionality
- [n/a] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by msmouse — APPROVED** [review]
Let's test in action how long a run with this setup would take 😂

**Review by perryjrandall — APPROVED** [review]

**Comment by perryjrandall** [comment]
Nice test plan boss

**Comment by perryjrandall** [comment]
Mainnet shard 8 looks very big 7h41m very close to timeout

Can we prune that range a bit?

https://github.com/aptos-labs/aptos-core/actions/runs/10731961176/job/29762875710

**Comment by sausagee** [comment]
Yep, i pruned it this morning. Here is the new canary, testnet only, https://github.com/aptos-labs/aptos-core/actions/runs/10740359924

**Review by areshand — APPROVED** [review]

**Pull request merged**
