### PR TITLE
Add Indexer Localnet setup doc, move Develop Locally to Nodes section

### PR DESCRIPTION
**Pull request by clay-aptos**

### CODE REVIEW

**Review by davidiw — COMMENTED** [review]
considering that we're deprecating this, does it make sense to further support it? I'm also kinda curious if we want so many top level items?

on a related note, I don't actually see indexer from the top nav bar


the content here looks great


cc @bowenyang007

**Comment by clay-aptos** [comment]
> considering that we're deprecating this, does it make sense to further support it? I'm also kinda curious if we want so many top level items?
> 
> on a related note, I don't actually see indexer from the top nav bar

Thanks, @davidiw . We have the indexer under the fullnode docs:
https://aptos.dev/nodes/indexer-fullnode

And the top nav is just the first layer of docs. We can easily expose indexer directly though. Please just let me know if that's what you want.

> 
> the content here looks great

All credit goes to @bowenyang007 .

> 
> cc @bowenyang007

**Comment by clay-aptos** [comment]
> > considering that we're deprecating this, does it make sense to further support it? I'm also kinda curious if we want so many top level items?
> > on a related note, I don't actually see indexer from the top nav bar
> 
> Thanks, @davidiw . We have the indexer under the fullnode docs: https://aptos.dev/nodes/indexer-fullnode
> 
> And the top nav is just the first layer of docs. We can easily expose indexer directly though. Please just let me know if that's what you want.
> 
> > the content here looks great
> 
> All credit goes to @bowenyang007 .
> 
> > cc @bowenyang007

Note, I have now placed this doc at the top level of the Nodes section:
https://aptos.dev/nodes/indexer-fullnode

**Comment by clay-aptos** [comment]
Hi @bowenyang007 , can you take a look at the TODOs in this PR and let me know what you think? Thanks!

**Comment by clay-aptos** [comment]
@bowenyang007 and @davidiw , should I simply close this PR out? Thanks.

**Comment by gregnazario** [comment]
Closing in favor of indexer v2

**Pull request closed without merging**
