### PR TITLE
cherry-pick: remove usage of normalized types and improve module complexity check (main)

### PR DESCRIPTION
**Pull request by vgao1996**

### CODE REVIEW

**Review by runtian-zhou — COMMENTED** [review]
Was wondering if we can remove the timed feature flag in the main branch to make code a bit cleaner. I'm fine landing it as is but feels like a bit of extra clean up might be better.

**Comment by vgao1996** [comment]
@runtian-zhou was thinking about the same thing. IMO it's better to clean up the timed feature flag later since
1. We'll need to run replay to confirm the removal is safe
2. This is blocking the 1.16 release

**Comment by runtian-zhou** [comment]
I'm suggesting for 1.16 cherry pick we just land as is. We should probably clean it up on main branch PR.

**Comment by vgao1996** [comment]
@runtian-zhou I think it's better we get all the cherry-picks landed for easy tracking and consistency. 

The presence of the timed feature flag is a minor code cleanness issue and we can take time with it. The 1.17 branch cut may also happen soon. We don't want to make this a blocker.

**Comment by runtian-zhou** [comment]
Would be concerned if we never get time to clean up those code but I agree that blocking release is not good either. I'll stamp it for now.

**Review by runtian-zhou — APPROVED** [review]

**Comment by vgao1996** [comment]
I see your concern. I'll start a replay task today.

**Review by ziaptos — APPROVED** [review]

**Pull request merged**
