### PR TITLE
[gas] revert the default gas numbers back

### PR DESCRIPTION
**Pull request by vgao1996**
### Description
Previously these numbers were bumped up due to the gas scaling factor not working. Now since that has been fixed, it's time to revert these back to avoid confusion at client side.

### Test Plan
CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2771)

### CODE REVIEW

**Comment by wrwg** [comment]
Can't review on the road

**Review by wrwg — APPROVED** [review]

**Review by movekevin — APPROVED** [review]
Are these counts the "internal gas units"?

**Comment by vgao1996** [comment]
@movekevin no, external. Rule of thumb: these are client inputs and external gas units are for clients

**Comment by davidiw** [comment]
Do we need to cherry-pick this into devnet @gregnazario @sherry-x

**Comment by gregnazario** [comment]
Yes likely

**Comment by wrwg** [comment]
Why is that not in? On the chat in the testnet channel it appeared that Sherry waited for this. If its not then definitely.

**Comment by gregnazario** [comment]
I'm handling this @wrwg

**Pull request merged**
