### PR TITLE
[Docs] fix consensus/README.md interface name

### PR DESCRIPTION
**Pull request by nkysg**
### Description
fix consensus/README.md technical_report link and Implementation Details interface name

### CODE REVIEW

**Comment by nkysg** [comment]
> Thank you! This looks correct to me. I am adding a member of the Consensus team to confirm.

Thanks for your review. I want to learn from your project.

**Comment by saharct** [comment]
@davidiw and @zekun000, it looks like `TxnManager` was changed to `PayloadClient` but is still referred to as `TxnManager` in the code comments. I created [PR 7437](https://github.com/aptos-labs/aptos-core/pull/7437) to address this.

**Review by saharct — APPROVED** [review]

**Review by zekun000 — COMMENTED** [review]
cc: @bchocho

**Comment by clay-aptos** [comment]
Thanks for the most recent update here, as well. Setting to auto-merge.

**Pull request merged**
