### PR TITLE
[gas] storage_gas initial value fix

### PR DESCRIPTION
**Pull request by lightmark**
### Description
match the curve.

### Test Plan
ut

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4658)

### CODE REVIEW

**Review by movekevin — COMMENTED** [review]
Can you add a description for how these values change the curve?

**Comment by lightmark** [comment]
> Can you add a description for how these values change the curve?

they don't change the curve. Their initial values should match with the curve initial value. Otherwise, they will be changed to new values dramatically after the first reconfig.

**Review by movekevin — APPROVED** [review]

**Review by msmouse — APPROVED** [review]

**Comment by lightmark** [comment]
@areshand test failed.. I spent 1 hour without any solution yet.

**Comment by davidiw** [comment]
Please update ASAP

**Comment by lightmark** [comment]
@davidiw before 11AM

**Pull request merged**
