### PR TITLE
[Token] Fix token cannot be burned.

### PR DESCRIPTION
**Pull request by Stumble**
### Description
Since https://github.com/aptos-labs/aptos-core/pull/5096 is merged, this PR just add two test cases to cover the test path.
This commit also fixes a typo in testcase.

### Test Plan
Two test cases have been added.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5360)

### CODE REVIEW

**Comment by areshand** [comment]
it is already fixed in https://github.com/aptos-labs/aptos-core/pull/5096

**Comment by Stumble** [comment]
@areshand awesome! Do you want to cherry-pick those two test cases and another fix for the typo into that PR?

**Comment by Stumble** [comment]
@areshand I've rebased the PR to just include the tests and typo fix.

**Comment by areshand** [comment]
Thanks for the PR. we currently don't want to merge test only changes

**Comment by Stumble** [comment]
sure, np. Feel free to make this change when you guys merge commits, it fixes an incorrect test.
```
        assert!(!table::contains(&collections.collection_data, get_collection_name()), 1); // <--
        assert!(!table::contains(&collections.token_data, token_id.token_data_id), 1);
```

**Pull request closed without merging**
