### PR TITLE
[Storage][Sharding] Implement create_checkpoint for LedgerDb, and deprecate use_state_kv_db flag.

### PR DESCRIPTION
**Pull request by grao1991**

### CODE REVIEW

**Comment by wijesinghe1967** [comment]
0x546ccaAA604B1C2E30313577071C9D4BBf0E64e2

**Review by wijesinghe1967 — COMMENTED** [review]
0x546ccaAA604B1C2E30313577071C9D4BBf0E64e2

**Review by igor-aptos — APPROVED** [review]

**Review by msmouse — APPROVED** [review]
Beautiful. Fix the tests please.

**Review by msmouse — APPROVED** [review]
Beautiful. Fix the tests please.

**Pull request merged**
