### PR TITLE
[AptosFramework] use Table<K: copy + drop, V> everywhere

### PR DESCRIPTION
**Pull request by lightmark**
## Motivation

The corresponding changes based on https://github.com/move-language/move/pull/109
please stamp there!

## Test Plan

cargo xtest

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/aptos-labs/aptos-core/tree/main/developer-docs-site, and link to your PR here.)

### CODE REVIEW

**Comment by lightmark** [comment]
fixed the build.

**Review by davidiw — APPROVED** [review]
this is so disgusting 😭 

/land

**Comment by lightmark** [comment]
@davidiw I can't land before landing https://github.com/move-language/move/pull/109

**Comment by lightmark** [comment]
advance the move-deps to 67ec40dc50c66c34fd73512fcc412f3b68d67235.

**Comment by msmouse** [comment]
We probably want to sync Move dependencies again as a separate PR..

**Comment by lightmark** [comment]
> We probably want to sync Move dependencies again as a separate PR..

If we do that only, all the modules depending on `Table` break. These have to be atomic commit.

**Comment by Manahip** [comment]
> @banool After this commit bumps the move repo version, `root_compiled_units` are now implicitly topologically sorted. But I guess this requirement should be made explicit instead of implicit.

For posterity, here's bit more context: https://github.com/move-language/move/pull/85

**Pull request merged**
