### PR TITLE
[Docs] Indexing initial doc

### PR DESCRIPTION
**Pull request by rajkaramchedu**
Ready to merge ~(Wait. I need to check why data-retention doc is in this PR).~ DONE

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4760)

### CODE REVIEW

**Review by clay-aptos — COMMENTED** [review]
Hi Raj,

I made some small edits inline.

**Comment by clay-aptos** [comment]
Raj, shall I link to these new docs in?
https://github.com/aptos-labs/aptos-core/pull/4646

It looks like that page has the only indexer refs:

```
claymurphy@MacBook-Air developer-docs-site % grep -r -i indexer docs
docs/guides/system-integrators-guide.md:Events and transactions pruning can be disabled via setting the [`enable_ledger_pruner`](https://github.com/aptos-labs/aptos-core/blob/cf0bc2e4031a843cdc0c04e70b3f7cd92666afcf/config/src/config/storage_config.rs#L141)) to `false`. This will be default behavior in Mainnet. In the near future, Aptos will provide indexers that mitigate the need to directly query from a node.
docs/guides/system-integrators-guide.md:Each event in `events` is differentiated by an `key`. The `key` is derived from the `guid` from `changes`. Specifically, the `key` is a 40-byte hex string where the first 8-bytes (or 16 characters) are the little endian representation of the `creation_num` in the `guid` of the `changes` event and the remaining characters are the account address. As events do not dictate what emitted them, it is imperative to track the path in `changes` to determine the source of an event. In particular, each `CoinStore<T>` has both a `WithdrawEvent` and a `DepositEvent`, based upon the type of coin. In order to determine which coin based upon a transaction, an indexer can compare the `guid::creation_num` in a `changes` event combined with the address to the `key` for events in `events`.
claymurphy@MacBook-Air developer-docs-site % 
```

**Comment by rajkaramchedu** [comment]
This doc is in very early stage. Let's do all these changes when I am done done with it. Probably not until the weekend is over, looking at where we are feature-wise.

**Comment by rajkaramchedu** [comment]
Docs deploy preview link: https://deploy-preview-4760--aptos-developer-docs.netlify.app/guides/indexing

**Review by bowenyang007 — APPROVED** [review]

**Review by gregnazario — APPROVED** [review]

**Pull request merged**
