### PR TITLE
feat: serialize/deserialize PackageMetadata

### PR DESCRIPTION
**Pull request by zouguangxian**
### Description
This feat can be used to parse package-metadata.bcs, so that developer can publish parts of packages to chain.

### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4148)

### CODE REVIEW

**Comment by jjleng** [comment]
Thanks for contributing!
1) Make the PR target the `main` branch, not the dev branch.
2) There are circular dependency issues
3) Would like to see some tests

Unlike other txn builder types, package metadata is on-chain data. You can actually retrieve the schema from https://fullnode.devnet.aptoslabs.com/v1/accounts/0x1/modules. Most likely, we wouldn't need to create these classes manually. We can either provide a tool to generate these classes based on the schema or just parse `package-metadata.bcs` on the fly by utilizing the schema at https://fullnode.devnet.aptoslabs.com/v1/accounts/0x1/modules. 

Would like to hear your use case. What do you want to achieve?

**Comment by wrwg** [comment]
I'm wondering what the purpose of this PR is. Package metadata should only be constructed by the compiler (after `aptos move compile`, you find it in `build/<pack>/package-metdata.bcs`). It should never be build manually. Indeed, people can do that if they like, but we should not support this by our APIs.

**Comment by zouguangxian** [comment]
If multiple modules are in one package, but part of these modules should be published with different accounts, then the user can not directly execute `aptos move publish` to deploy modules. I also agree that the modules should be put in separate packages in this situation.

**Comment by wrwg** [comment]
> If multiple modules are in one package, but part of these modules should be published with different accounts, then the user can not directly execute `aptos move publish` to deploy modules. I also agree that the modules should be put in separate packages in this situation.

Yes, in fact all modules in a given package must have the same account. If they don't then publishing will fail at the transaction level.

**Comment by rajkaramchedu** [comment]
> f multiple modules are in one package, but part of these modules should be published with different accounts

Fyi, added a note to this effect in https://github.com/aptos-labs/aptos-core/pull/4296.

**Pull request closed without merging**
