### PR TITLE
[ts-sdk] Remove V1 SDK

### PR DESCRIPTION
**Pull request by gregnazario**
## Description
SDK V1 is deprecated, we're removing the code associated, and any tests associated.

I suspect I will need to remove other pieces in CI

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [x] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [x] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

This package was deprecated on NPM. https://www.npmjs.com/package/aptos

## Checklist
- [x] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I identified and added all stakeholders and component owners affected by this change as reviewers
- [x] I tested both happy and unhappy path of the functionality
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by 0xmaayan — COMMENTED** [review]
Huge milestone! 

Might worth keeping the code for reference, but maybe rename the folder name.

For CI we should defiantly remove it

**Comment by gregnazario** [comment]
> Huge milestone!
> 
> Might worth keeping the code for reference, but maybe rename the folder name.
> 
> For CI we should defiantly remove it

I figured, it's still in git, so let's just remove it entirely.

**Comment by 0xmaayan** [comment]
> > Huge milestone!
> > Might worth keeping the code for reference, but maybe rename the folder name.
> > For CI we should defiantly remove it
> 
> I figured, it's still in git, so let's just remove it entirely.
> 
> I can make a git tag back to the last commit with it, if that is helpful

Lets do it! full deprecation 🚀

**Review by 0xmaayan — APPROVED** [review]

**Review by larry-aptos — APPROVED** [review]
LGTM for tests + CI part.

**Pull request merged**
