### PR TITLE
[smoke-tests] fix flakiness in error-report

### PR DESCRIPTION
**Pull request by bchocho**
### Description

The tests run sequentially, on the same chain. So they cannot make assumptions on the state of the chain when they start.

### Test Plan

Running: `% cargo x test -p smoke-test -- --nocapture`

Previously failed:
```
thread 'main' panicked at 'expected = INVALID_AUTH_KEY, err = Request failed: RestError { code: 400, message: "invalid transaction: SEQUENCE_NUMBER_TOO_OLD", aptos_ledger_version: None }', testsuite/smoke-test/src/aptos/error_report.rs:34:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test smoke-test::aptos::error-report ... FAILED
```

Now passes.

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2140)

### CODE REVIEW

**Comment by perryjrandall** [comment]
Can you please include the command you're running / some output in the test plan?

That would make it super ez for others to learn from this test plan

**Review by perryjrandall — APPROVED** [review]

**Review by wrwg — COMMENTED** [review]
There is perhaps a better solution than merging these both tests, and that is use a different module directory for each.

**Comment by bchocho** [comment]
I’ll land with just my changes in error_report (not move related) for now.

**Comment by bchocho** [comment]
Superseded by #2143

**Pull request closed without merging**
