### PR TITLE
[documentation] adding ANS UI library documentation

### PR DESCRIPTION
**Pull request by angieyth**
### Description
Adding  the documentation for ANS UI package. 

### Test Plan
follow the [instruction](https://aptos.dev/community/site-updates/), and go to http://localhost:3000 to check the result. 

Screen Shot 2023-03-16 at 1 44 06 PM
Screen Shot 2023-03-16 at 1 44 15 PM
Screen Shot 2023-03-16 at 1 44 26 PM

### CODE REVIEW

**Comment by clay-aptos** [comment]
Hi @saharct , please help Angie with editing and when ready getting the file in navigation. The latter can happen in a distinct PR. Thank you both!

**Review by saharct — APPROVED** [review]
The process works for me after changing some things. Thanks, @angieyth!

**Comment by saharct** [comment]
I tested it with yarn and npm. I added a prerequisites section, yarn commands, and some more details to the instructions portion. Thanks!

**Comment by angieyth** [comment]
thank you @saharct for helping out. should I merge now?

**Comment by saharct** [comment]
You're welcome, @angieyth! We still need 1 more reviewer to approve the PR. Perhaps @0xmaayan or @banool can take a look at it.

**Review by 0xmaayan — APPROVED** [review]
LGTM!

**Pull request merged**
