### PR TITLE
[Framework] Publicize `account::create_account_if_does_not_exist()`

### PR DESCRIPTION
**Pull request by alnoki**
@davidiw introduced `account::create_account_if_does_not_exist()` here  ( https://github.com/aptos-labs/aptos-core/commit/507791c#diff-ef8a70cd4b03dc7b8b6dfd8306886d480c155211d8c472b59585471e4c60c427 ), but it is private and no other functions depend on it

Publicize the function, a useful helper

### CODE REVIEW

**Review by movekevin — APPROVED** [review]

**Review by alinush — APPROVED** [review]

**Review by davidiw — CHANGES_REQUESTED** [review]
Would like a discussion here before sign off

**Comment by alnoki** [comment]
> we open up a new set of behaviors that isn't well studied.

@davidiw The main behavior that this enables is creating an account without erroring out

There are as yet no other short-circuit methods for simply creating an account if it doesn't exist, and I've noticed in conversations/code review with plenty other devs the difficulties of having all the other happy paths in the repo abort if an account exists

This just makes it easier to ensure someone has an account

**Comment by davidiw** [comment]
> > we open up a new set of behaviors that isn't well studied.
> 
> @davidiw The main behavior that this enables is creating an account without erroring out
> 
> There are as yet no other short-circuit methods for simply creating an account if it doesn't exist, and I've noticed in conversations/code review with plenty other devs the difficulties of having all the other happy paths in the repo abort if an account exists
> 
> This just makes it easier to ensure someone has an account

Examples, please?

Why do people want these accounts to exist?

This becomes even a lesser issue once we get to fungible assets.

**Comment by alnoki** [comment]
> Examples, please?
> 
> Why do people want these accounts to exist?

@davidiw 

`account::Account` is required for GUID, txn submission, and auth key rotation

**Comment by davidiw** [comment]
> > Examples, please?
> > Why do people want these accounts to exist?
> 
> @davidiw
> 
> `account::Account` is required for GUID, txn submission, and auth key rotation

What operation are you trying to perform and in which context?
* txn submission -> sponsored transaction? you need apt
* auth key rotation -> who is rotating it?
* GUID -> when? we're moving away from using GUIDs for events in the next couple of releases

**Comment by alinush** [comment]
> > we open up a new set of behaviors that isn't well studied.
> 
> @davidiw The main behavior that this enables is creating an account without erroring out
> 
> There are as yet no other short-circuit methods for simply creating an account if it doesn't exist, and I've noticed in conversations/code review with plenty other devs the difficulties of having all the other happy paths in the repo abort if an account exists
> 
> This just makes it easier to ensure someone has an account

Can't people currently call:
1. `account::exists_at(addr)`
2. `aptos_account::create_account(addr)`

The problem is it creates a `CoinStore<AptosCoin>`

**Comment by davidiw** [comment]
well I'll be damned... you win... @movekevin already exposed the function...

**Pull request merged**
