### PR TITLE
Remove CLA

### LINKED ISSUE #1317: Remove CLA
As a follow up to #1263 and our internal discussion we should remove the CLA and its requirement from other parts of the repo.

### PR DESCRIPTION
**Pull request by geekflyer**
- Remove CLA Fixes #1317

Good bye CLA! Won't miss ya 😄

### CODE REVIEW

**Comment by rajkaramchedu** [comment]
I will defer to @davidiw on this one.

**Review by JoshLind — APPROVED** [review]
WOOO! (@rajkaramchedu, I can also confirm this requirement has been removed 😄)

**Comment by hoangphii** [comment]
I registered from 7/10. but now i am not getting mail from you . help me with mail : [lucianphi@gmail.com](mailto:lucianphi@gmail.com) discord : Hoang Phi#1381

**Pull request merged**
