### PR TITLE
[Storage][Pruner] Do not error out in get_account_transaction_version_iter for pruned transactions

### PR DESCRIPTION
**Pull request by sitalkedia**
The API throws an error in case the queried sequence number has been pruned, instead of erroring out, we just return the available transactions in the account.

### CODE REVIEW

**Comment by lightmark** [comment]
Why do we want this change?

**Comment by sitalkedia** [comment]
@lightmark - This is currently used by the Rest API `get_account_transactions`, where the user passes a minimum sequence number. Since the txns are pruned, there is no easy way for user to specify the min sequence number - they just pass 0 if they don't care. The idea is to return the minimum available txns for the account in that case.

**Review by lightmark — APPROVED** [review]

**Review by grao1991 — APPROVED** [review]

**Pull request closed without merging**
