### PR TITLE
[Consensus] Add monitoring for main loops

### PR DESCRIPTION
**Pull request by sitalkedia**
### Description

This will help us understand if any single threaded task is getting choked.

### CODE REVIEW

**Review by igor-aptos — APPROVED** [review]

**Review by zekun000 — COMMENTED** [review]
in order to understand the loop utilization, we need to instrument the main polling as well. this is what I did back in the days https://github.com/diem/diem/blob/latest/consensus/src/epoch_manager.rs#L610

**Comment by sitalkedia** [comment]
> in order to understand the loop utilization, we need to instrument the main polling as well. this is what I did back in the days https://github.com/diem/diem/blob/latest/consensus/src/epoch_manager.rs#L610

@zekun000 - Correct me if I am missing something but above instrumentation always will be close to 1 because  either the task is sleeping in the future::select or doing some work and some of them would always be equal to the total time. What we are interested in capturing is time spent in doing real work / total time - which will give us the loop utilization.

**Comment by zekun000** [comment]
we want to measure the work time/(work time + sleep time) as loop utilization, the higher it is, the busier the loop is. the main_loop basically measures the (work time + sleep time) part

**Comment by sitalkedia** [comment]
loop utilization is work time / (work time + sleep time). In 1 second window, the work time + sleep time is always 1 second because either the task is working or sleeping - there is no other state. We need the work time, which is what this PR does. Does it make sense?

**Review by zekun000 — APPROVED** [review]
i see, so we use the fixed time window, now I remember we did the same for execution/commit

**Pull request merged**
