### PR TITLE
[Docs] Add Use-Remix-IDE-plugin page

### PR DESCRIPTION
**Pull request by 0xhsy**
### Description

Added a tutorial about a plugin that can develop Aptos Move module in Remix IDE.

### CODE REVIEW

**Comment by clay-aptos** [comment]
This looks useful. May I ask why you closed it?

**Comment by 0xhsy** [comment]
> This looks useful. May I ask why you closed it?

I've closed this for a while to make some corrections. I'll reopen it for your interest and keep updating the document.

**Comment by clay-aptos** [comment]
> > This looks useful. May I ask why you closed it?
> 
> I've closed this for a while to make some corrections. I'll reopen it for your interest and keep updating the document.

Yes, please! Thank you!

**Comment by 0xhsy** [comment]
> 

Could you please review this guide now?

**Comment by 0xhsy** [comment]
>

**Comment by 0xhsy** [comment]
> > > This looks useful. May I ask why you closed it?
> > 
> > 
> > I've closed this for a while to make some corrections. I'll reopen it for your interest and keep updating the document.
> 
> Yes, please! Thank you!

Could you please review this guide now?

**Comment by clay-aptos** [comment]
Hi Jeju, I am writing to let you know we plan to publish this material in a forthcoming Contribute > Highlights section of Aptos.dev forming in:
https://github.com/aptos-labs/aptos-core/pull/6417

Please stand by while I finish that up. I will then work with you in this PR to edit and move those contents there. Thanks!

**Comment by 0xhsy** [comment]
> 

That's a great idea. Thank you for letting me know!

**Review by gregnazario — APPROVED** [review]
lgtm, @clay-aptos mind doing a quick grammar / English check over it?

**Comment by clay-aptos** [comment]
> lgtm, @clay-aptos mind doing a quick grammar / English check over it?

Will do, @gregnazario . In fact, I have big plans for editing and shifting this into the forthcoming Contribute > Community Highlights section:
https://github.com/aptos-labs/aptos-core/pull/6417
https://deploy-preview-6417--aptos-developer-docs.netlify.app/contribute/community-highlights

Tracking in:
https://github.com/aptos-labs/aptos-core/issues/6311#issuecomment-1446843958

More coming soon!

**Review by clay-aptos — APPROVED** [review]
Thanks again for the contribution. Let's get this in so I may edit it and add to the new Community Highlights section:
https://aptos.dev/community/contributions/community-highlights

**Pull request merged**
