### PR TITLE
[Aptos Framework] Rename TestCoin to AptosCoin

### PR DESCRIPTION
**Pull request by movekevin**
It's not easy to support different network coins, e.g. AptosCoin for mainnet and TestCoin for devnet/testnet so we should rename everything to AptosCoin.

Will update symbol + decimals for AptosCoin later once those details are finalized.

This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1658)

### CODE REVIEW

**Review by davidiw — CHANGES_REQUESTED** [review]
Let's wait on this until code freeze 🙏

**Comment by movekevin** [comment]
> Let's wait on this until code freeze 🙏

Ideally we should do this before the long-lived testnet launch. Otherwise, we wouldn't be able to change it after, and would end up with confusing differences in documentation.

**Review by rajkaramchedu — APPROVED** [review]
Docs-wise it looks good.

**Review by davidiw — APPROVED** [review]
Please wait to land these :)

**Comment by wrwg** [comment]
Looks like this is ready to land after some (hopefully harmless) rebase? I see it already is adapted to the casing change ;-)

**Pull request merged**
