### PR TITLE
[gha] build on merge sha

### PR DESCRIPTION
**Pull request by rustielin**
### Description

build on merged git sha rather than tip of PR branch

### Test Plan

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2204)

### CODE REVIEW

**Comment by rustielin** [comment]
Hrm it looks like it's not getting the rest of the Forge comment correctly now. Probably these lines: https://github.com/aptos-labs/aptos-core/blob/main/.github/workflows/run-forge.yaml#L89-L95

**Review by geekflyer — APPROVED** [review]

**Comment by rustielin** [comment]
Think it's still using `main` @ `aeb45b7cbc4fef24e42e00fc8c76dce1bba252a5` https://github.com/aptos-labs/aptos-core/runs/7509945366?check_suite_focus=true

**Comment by geekflyer** [comment]
> Think it's still using `main` @ `aeb45b7cbc4fef24e42e00fc8c76dce1bba252a5` [aptos-labs/aptos-core/runs/7509945366?check_suite_focus=true](https://github.com/aptos-labs/aptos-core/runs/7509945366?check_suite_focus=true)

I don't think `aeb...` is a commit on main, so this looks alright to me.

**Comment by geekflyer** [comment]
> Think it's still using `main` @ `aeb45b7cbc4fef24e42e00fc8c76dce1bba252a5` [aptos-labs/aptos-core/runs/7509945366?check_suite_focus=true](https://github.com/aptos-labs/aptos-core/runs/7509945366?check_suite_focus=true)

I think this just because I switched the event back to `pull_request_target` so this PR is still running on the workflow definition from main. Once this is merged the new logic should kick in.

**Comment by rustielin** [comment]
hrm it ran on `0daade4f734d1ba29a896b00d7ddde2249e87970`, which is `main` still. I thinkwe should revert the merge stuff

**Pull request merged**
