### PR TITLE
Add API spec explorer to dev docs site

### PR DESCRIPTION
**Pull request by banool**
### Description
In this PR I add the API spec explorer directly to the docs site. I use the Stoplight elements packages directly to do this. This isn't ready to land, we still need to figure out a few things:

I have tabs for each of the 3 major networks. Do we like this, or do we just want to show mainnet?

I show the stacked view for mainnet and the sidebar view for testnet so we can see which we prefer. On its own I prefer the sidebar view, but inside the docs site, perhaps stacked is cleaner. I think it'd be nice to have a switch so users can choose on their own, that shouldn't be hard. The sidebar view does look a little squished though, it seems like it wastes some space on the right side.

To make this work, I added a bunch of packages that this depended on. Normally this shouldn't be necessary I thought, and yarn should do this on its own. I followed some of the recommendations here to get this to work: https://github.com/stoplightio/elements/discussions/1777. We probably need the help from a frontend export (@zacharydenton) here.

I don't have a custom index.module.css, I just use the css from `@stoplight/elements/styles.min.css`. We should consider applying our own changes to this perhaps for branding purposes / making it fit better.

A small thing but I think the dark mode view is sort of busy looking. Light mode looks good though.

I suspect we want to put this somewhere else, probably not under the "nodes" tab.

The server for the "try it" feature is wrong.

### Test Plan
Check it out on the Netlify preview, you want to visit `/nodes/aptos-api-spec#/`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5345)

### CODE REVIEW

**Comment by clay-aptos** [comment]
> ### Description
> In this PR I add the API spec explorer directly to the docs site. I use the Stoplight elements packages directly to do this. This isn't ready to land, we still need to figure out a few things:
> 
> I have tabs for each of the 3 major networks. Do we like this, or do we just want to show mainnet?

Thanks so much, Daniel! I prefer we show all if there will indeed be deltas between them. Looks like it:
https://discord.com/channels/945856774056083548/1034215378299133974/1037095816147509249
> 
> I show the stacked view for mainnet and the sidebar view for testnet so we can see which we prefer. On its own I prefer the sidebar view, but inside the docs site, perhaps stacked is cleaner. I think it'd be nice to have a switch so users can choose on their own, that shouldn't be hard. The sidebar view does look a little squished though, it seems like it wastes some space on the right side.

I prefer stacked view given the embedding in Aptos.dev. The sidebar view is busy indeed embedded. My two cents.

> 
> To make this work, I added a bunch of packages that this depended on. Normally this shouldn't be necessary I thought, and yarn should do this on its own. I followed some of the recommendations here to get this to work: [stoplightio/elements#1777](https://github.com/stoplightio/elements/discussions/1777). We probably need the help from a frontend export (@zacharydenton) here.
> 
> I don't have a custom index.module.css, I just use the css from `@stoplight/elements/styles.min.css`. We should consider applying our own changes to this perhaps for branding purposes / making it fit better.
> 
> A small thing but I think the dark mode view is sort of busy looking. Light mode looks good though.
> 
> I suspect we want to put this somewhere else, probably not under the "nodes" tab.

I am suggesting we create a top-level Reference section where this will reside. In the meantime we can swap out the existing REST API link in the top bar of aptos.dev.

> 
> The server for the "try it" feature is wrong.
> 
> ### Test Plan
> Check it out on the Netlify preview, you want to visit `/nodes/aptos-api-spec#/`.
> 
> This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5345)

**Review by clay-aptos — APPROVED** [review]

**Comment by banool** [comment]
Let me see if I can fix the server thing for the try it feature, I'd say that's the main blocker. As well as the API in the top bar. Let me try that.

**Comment by clay-aptos** [comment]
Let me know how I can help. Thank you Daniel.

**Review by bowenyang007 — APPROVED** [review]

**Comment by banool** [comment]
See https://github.com/stoplightio/elements/issues/new?assignees=&labels=t%2Fchange&template=CHANGE_TEMPLATE.md for the server problem with the "try it" feature.

**Pull request merged**
