### PR TITLE
Fixing a small typo

### PR DESCRIPTION
**Pull request by jaredcosulich**
Fixing a small typo in the documentation

### CODE REVIEW

**Comment by davidiw** [comment]
Thanks for the submission. Before we can accept it, we require a CLA.

**Comment by jaredcosulich** [comment]
Apologies, didn't think it would matter for this small of a PR. Feel free to close this PR and fix this typo separately. I'll look to submit the CLA for any future PRs.

**Comment by davidiw** [comment]
> Apologies, didn't think it would matter for this small of a PR. Feel free to close this PR and fix this typo separately. I'll look to submit the CLA for any future PRs.

Thanks, and apologies. We only have the CLA process for now.

**Review by davidiw — APPROVED** [review]
We've been informed that CLAs are no longer required :)

/land

**Pull request merged**
