### PR TITLE
[docs] Update GCP to 1.3.6 Terraform

### PR DESCRIPTION
**Pull request by gregnazario**
Terraform 1.3.6 is needed to run through steps now, so it might as well be updated.

I was running through this tutorial directly, and it wouldn't let me use a version less than this for devnet

### CODE REVIEW

**Review by clay-aptos — APPROVED** [review]
Thanks, Greg. What about on these pages, which still list the version as 1.2.4?

https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-aws/

https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-azure/

**Comment by gregnazario** [comment]
> Thanks, Greg. What about on these pages, which still list the version as 1.2.4?
> 
> https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-aws/
> 
> https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-azure/

These need to be updated as well.  I just did this through the github UI, let me fix the rest.

**Comment by gregnazario** [comment]
I need to do some checking here on the terraform version to ensure this is correct.

**Comment by clay-aptos** [comment]
> > Thanks, Greg. What about on these pages, which still list the version as 1.2.4?
> > https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-aws/
> > https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-azure/
> 
> These need to be updated as well. I just did this through the github UI, let me fix the rest.

Thanks so much, Greg!

**Review by rustielin — APPROVED** [review]
LGTM, thanks for fixing this! 

I'd do ~>1.3.6 since that's what we've tested (e.g. in https://github.com/aptos-labs/aptos-core/commit/df56c7f0de8c82d6ac95fbe0aa32151bc8196d95), but 1.3.9 should work as well.

**Comment by clay-aptos** [comment]
Thanks, Greg. Let me know if you think this is worthy of a See what's new entry.

**Pull request merged**
