### PR TITLE
[cargo] remove all unused dependencies

### PR DESCRIPTION
**Pull request by AlexiaChen**
### Description

Remove all unused dependencies 

### Test Plan
 
build success locally

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3930)

### CODE REVIEW

**Comment by AlexiaChen** [comment]
@davidiw   Hey， I tried to fix   CI/CD tests, please retrigger the Github action. Thanks!

**Comment by davidiw** [comment]
this pr doesn't do anything.

**Comment by davidiw** [comment]
feel free to re-open if it contains something besides deleting an empty new line

**Comment by AlexiaChen** [comment]
> feel free to re-open if it contains something besides deleting an empty new line

@davidiw   I use https://github.com/est31/cargo-udeps  to scan the unused dependencies, I tell me does not do anything?  maybe the tool I used could produce false positive( im trying to fix the CI errors), but you cannot think that `feel free to re-open if it contains something besides deleting an empty new line`

**Comment by AlexiaChen** [comment]
@davidiw  cargo udeps results：

```txt
unused dependencies:
`aptos v0.3.3 (/home/mathxh/Project/aptos-core/crates/aptos)`
└─── dependencies
     └─── "parse_duration"
`aptos-faucet v0.1.0 (/home/mathxh/Project/aptos-core/crates/aptos-faucet)`
└─── dependencies
     ├─── "aptos-keygen"
     └─── "aptos-warp-webserver"
`aptos-fh-stream v0.1.0 (/home/mathxh/Project/aptos-core/ecosystem/sf-indexer/firehose-stream)`
└─── dependencies
     └─── "warp"
`aptos-genesis v0.1.0 (/home/mathxh/Project/aptos-core/crates/aptos-genesis)`
└─── dependencies
     └─── "structopt"
`aptos-jellyfish-merkle v0.1.0 (/home/mathxh/Project/aptos-core/storage/jellyfish-merkle)`
└─── dependencies
     └─── "storage-interface"
`aptos-logger v0.1.0 (/home/mathxh/Project/aptos-core/crates/aptos-logger)`
└─── dependencies
     └─── "tokio"
`aptos-network-checker v0.0.1 (/home/mathxh/Project/aptos-core/crates/aptos-network-checker)`
└─── dependencies
     ├─── "aptos-api-types"
     └─── "fallible"
`aptos-parallel-executor v0.1.0 (/home/mathxh/Project/aptos-core/aptos-move/parallel-executor)`
└─── dependencies
     └─── "claims"
`aptos-sdk-builder v0.1.0 (/home/mathxh/Project/aptos-core/aptos-move/aptos-sdk-builder)`
└─── dependencies
     └─── "structopt"
`aptos-telemetry v0.1.0 (/home/mathxh/Project/aptos-core/crates/aptos-telemetry)`
└─── dependencies
     └─── "const_format"
`aptos-telemetry-service v0.1.0 (/home/mathxh/Project/aptos-core/crates/aptos-telemetry-service)`
└─── dependencies
     ├─── "serde_with"
     └─── "tokio_schedule"
`aptosdb-indexer v0.1.0 (/home/mathxh/Project/aptos-core/storage/indexer)`
└─── dependencies
     ├─── "accumulator"
     ├─── "aptos-jellyfish-merkle"
     └─── "executor-types"
`consensus v0.1.0 (/home/mathxh/Project/aptos-core/consensus)`
└─── dependencies
     └─── "aptos-keygen"
`framework v0.1.0 (/home/mathxh/Project/aptos-core/aptos-move/framework)`
└─── dependencies
     ├─── "claims"
     └─── "structopt"
`language-e2e-tests v0.1.0 (/home/mathxh/Project/aptos-core/aptos-move/e2e-tests)`
└─── dependencies
     ├─── "aptos-config"
     ├─── "aptos-writeset-generator"
     └─── "project-root"
`safety-rules v0.1.0 (/home/mathxh/Project/aptos-core/consensus/safety-rules)`
└─── dependencies
     └─── "crash-handler"
`scratchpad v0.1.0 (/home/mathxh/Project/aptos-core/storage/scratchpad)`
└─── dependencies
     └─── "aptos-state-view"
`storage-interface v0.1.0 (/home/mathxh/Project/aptos-core/storage/storage-interface)`
└─── dependencies
     └─── "assert_unordered"
`transaction-emitter-lib v0.0.0 (/home/mathxh/Project/aptos-core/crates/transaction-emitter-lib)`
└─── dependencies
     └─── "termion"
`vm-genesis v0.1.0 (/home/mathxh/Project/aptos-core/aptos-move/vm-genesis)`
└─── dependencies
     └─── "aptos-config"
`vm-validator v0.1.0 (/home/mathxh/Project/aptos-core/vm-validator)`
└─── dependencies
     ├─── "cached-packages"
     ├─── "executor"
     └─── "executor-types"
Note: These dependencies might be used by other targets.
      To find dependencies that are not used by any target, enable `--all-targets`.
Note: They might be false-positive.
      For example, `cargo-udeps` cannot detect usage of crates that are only used in doc-tests.
      To ignore some dependencies, write `package.metadata.cargo-udeps.ignore` in Cargo.toml.
```

**Pull request closed without merging**
