### PR TITLE
[helm] add remote write option for testnet monitoring

### PR DESCRIPTION
**Pull request by sherry-x**
Add option for testnet prometheus to do remote write too

### CODE REVIEW

**Review by rustielin — COMMENTED** [review]
will this result in duplicates from the remote_write from validator prometheus? or is the idea to just use one or the other

**Comment by sherry-x** [comment]
@rustielin should be one or the other. for validator-lite we don't have prometheus on validator deployment

**Review by rustielin — APPROVED** [review]

**Pull request merged**
