### PR TITLE
Zjma/generic algebra feature flags

### PR DESCRIPTION
**Pull request by zjma**
### Description

**Note:** _We are breaking up https://github.com/aptos-labs/aptos-core/pull/6550 into smaller PRs. This is one of the pieces._

In this change, a feature flag is added for the incoming generic algebra Move module to enable BLS12381 group/field operations.

Supported BLS12381 structures include Fq12, G1, G2, Gt, Fr.

Operations include element (de)serialization, field/group arithmetic, pairing, hash-to-structure, casting, etc.

### CODE REVIEW

**Review by vgao1996 — APPROVED** [review]

**Review by movekevin — COMMENTED** [review]
Why not do this in https://github.com/aptos-labs/aptos-core/pull/6550?

**Comment by alinush** [comment]
> Why not do this in #6550?

We are breaking that PR up into smaller PRs.

@zjma, I think there are other places in Rust where the flag might need to be added too though, no? Otherwise, how are you gonna read it in the natives?

**Comment by zjma** [comment]
@alinush true, there are a few enums in rust and I just updated the PR to include them.

**Comment by alinush** [comment]
Great, I think you also need to enable the flags for devnet (see [here](https://github.com/aptos-labs/aptos-core/pull/6241/files) for an example) and maybe check w/ @perryjrandall?

**Review by alinush — APPROVED** [review]
LGTM!

**Pull request merged**
