### PR TITLE
[AptosFramework] remove total_value for now to enable parallel gas burn

### PR DESCRIPTION
**Pull request by zekun000**
Gas burn needs to update the total value stored in CoinInfo which forces sequential execution
of all transactions under parallel execution.

Ideally we should put them into different buckets but lack of a sharding strategy for transactions now,
we can add it back when we have such a thing.

### CODE REVIEW

**Comment by gelash** [comment]
you are the hero @zekun000.
Can you check that execution benchmark gives increased throughput with this change without any more commenting in modules? :-) (you may have to set concurrency properly in yaml or benchmark setup though).

**Comment by gelash** [comment]
Oh, I just scrolled to concurrency level setup.
Is it okay to set it to 4 by default here? It will assert and crash if somehow some setup has less cpus.

**Comment by zekun000** [comment]
lol so forge doesn't seem having 4 cpus

**Comment by zekun000** [comment]
ran a forge test manually: all up : 2456 TPS, 1746 ms latency, 2600 ms p99 latency,no expired txns

**Review by msmouse — APPROVED** [review]

**Comment by sitalkedia** [comment]
@zekun000 - Can you clarify what is the downside of removing tracking of total value?

**Comment by zekun000** [comment]
@sitalkedia so we don't have a total supply recording on-chain?

**Pull request closed without merging**
