### PR TITLE
[CP] Add account address to IT profiles

### PR DESCRIPTION
**Pull request by CapCap**
### Description
This makes life significantly easier in our data warehouse, as we can connect user accounts to on-chain data much more easily

### Test Plan
tested (and migrated) manually 

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2367)

### CODE REVIEW

**Review by davidiw — COMMENTED** [review]
shall we be more explicit about which account address this is?

**Comment by CapCap** [comment]
@davidiw it's fair, but this follows the existing (potentially poor) convention of validator being implicit, fullnode being explicit

**Review by davidiw — APPROVED** [review]
no way to persuade you to add "owner_account_address"?

**Comment by CapCap** [comment]
@davidiw it auto merged, but not unless we also change the names in the YAML the CLI generates, otherwise it's a bit confusing switching between the two :-(

**Pull request merged**
