### PR TITLE
[forge] implement keep and cleanup flags

### PR DESCRIPTION
**Pull request by rustielin**
Stacked on #1780 , only review latest commit.

# Overview

Implements the `--keep` flag for `forge test k8s-swarm` command, which keeps the Forge testnet around so devs can manually inspect the network. If not set, the Forge testnet will be cleaned up:
* at test completion (via `K8sSwarm::drop` destructor)
* or by a `forge-management` CronJob that executes `forge operator clean-up` command to clean up old Forge namespaces, in cases where Forge test runners crash (e.g. GHA outage) and the destructor above is not called. By default -- the CronJob runs every 15 min and kills namespaces older than 30 min

Also:
* clean up forge test pods over a day old

Note: Since Forge is essentially a wrapper around k8s testnets, with an option to do e2e test, it's possible to use Forge to orchestrate developer testnets. cc @perryjrandall 

## k8s implementation

On the backend, each Forge run's lifecycle is managed by a ConfigMap named `forge-management-${NAMESPACE}`, which exists in the same k8s namespace as the Forge net itself. This ConfigMap contains data such as whether the Forge net should be kept `keep: bool` and the starting timestamp `start: u64`.

# Test

## Keep forge testnet

Run `forge test k8s-swarm --keep ...` to run a Forge test and keep the network around:

```
$ cargo run -p forge-cli -- test k8s-swarm --image-tag $GIT_SHA --namespace forge-rustie --port-forward --keep
```

Run `forge operator clean-up` and see that the namespace I want to keep is ignored:

```
$ cargo run -p forge-cli -- operator clean-up
    Finished dev [unoptimized + debuginfo] target(s) in 1.02s
     Running `target/debug/forge operator clean-up`
...
2022-07-07T02:01:35.876722Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:631 Got configmap forge-management-forge-rustie with data: {"keep": "true", "start": "1657159281"}
2022-07-07T02:01:35.876823Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:636 Namespace forge-rustie has lived for 14/1800 seconds
2022-07-07T02:01:35.876849Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:641 Explicitly keeping namespace forge-rustie
```

We must then remember to cleanup the namespace manually after experimentation:

```
$ cargo run -p forge-cli -- operator clean-up --namespace forge-rustie
2022-07-07T02:02:04.085681Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:209 Deleting namespace forge-rustie: Some(NamespaceStatus { phase: Some("Terminating") })
2022-07-07T02:02:04.085879Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:315 aptos-node resources for Forge removed in namespace: forge-rustie
```

## Do not keep forge testnet

Run `forge test k8s-swarm ...` without `--keep` to run a Forge test ephemerally and clean up the namespace after we're done:

```
$ cargo run -p forge-cli -- test k8s-swarm --image-tag $GIT_SHA --namespace forge-rustie --port-forward 
...
2022-07-07T01:07:29.207174Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:184 Deleting namespace: Some(NamespaceStatus { phase: Some("Terminating") })
2022-07-07T01:07:29.207407Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:290 aptos-node resources for Forge removed in namespace: forge-rustie
```

### Test runner interruption

To test test runner interruption, ctrl-c out of a running Forge test, skipping all destructor calls to clean up the running namespace. `forge-management` CronJob then kicks in to execute:

```
# threshold not reached yet
$ cargo run -p forge-cli -- operator clean-up
2022-07-07T00:52:27.376838Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:512 Pod forge-rustie-1657144706 has lived for 10441/86400 seconds

# threshold reached
$ cargo run -p forge-cli -- operator clean-up
2022-07-07T01:07:28.704115Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:581 Got configmap forge-management-forge-rustie with data: {"keep": "false", "start": "1257155963"}
2022-07-07T01:07:28.704236Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:586 Namespace forge-rustie has lived for 400000085/1800 seconds
2022-07-07T01:07:29.207174Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:184 Deleting namespace: Some(NamespaceStatus { phase: Some("Terminating") })
2022-07-07T01:07:29.207407Z [main] INFO testsuite/forge/src/backend/k8s/cluster_helper.rs:290 aptos-node resources for Forge removed in namespace: forge-rustie
```

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1785)

### CODE REVIEW

**Review by geekflyer — CHANGES_REQUESTED** [review]
ok, so it took me a bit to understand what's going on here.
I think it'd be good if you'd outline the approach a bit more in the PR or the code itself fyi, but the way I understand it so far:
You're creating a management configmap in the default namespace for each net that has been spun up and in that management configmap you're keeping some metadata like when the net has been spun up and whether it should be "kept".

Some high level feedback:
- let's not use the `default` namespace - there's rarely a reason to use the default namespace for anything (also it's the only namespace that can't be deleted which is kinda annoying). Rather introduce a separate `aptos-testnet-operator` namespace and run the cronjob + create the configmaps there.

**Comment by rustielin** [comment]
Added some more of the k8s implementation details to the above PR description @geekflyer -- can also iterate offline if you have more feedback. You pretty much got it, minus the fact that the ConfigMaps are created in the `forge-*` namespaces rather than the `default` namespace. You're correct that the CronJobs are being created in the default `namespace` though. 

In general, I'm using the `default` namespace as the Forge test "control plane", as it's easier for operators to use with `kubectl` directly without specifying an additional `-n` flag which might get quite verbose or confusing to our users. I'm generally of the opinion that we can keep things in `default` namespace as long as it's relevant to most users

Also, I don't expect the `default` namespace to be used for Forge testing itself. In fact, we should discourage folks from using it. It's only supported because (1) we still need it to share some of the helm values between releases and (2) it's the namespace that TF does the initial deploy in. In practice, I'm using the `default` namespace to do initial validation only and then immediately cleaning it up with `forge` CLI.

**Comment by geekflyer** [comment]
> Added some more of the k8s implementation details to the above PR description @geekflyer -- can also iterate offline if you have more feedback. You pretty much got it, minus the fact that the ConfigMaps are created in the `forge-*` namespaces rather than the `default` namespace. You're correct that the CronJobs are being created in the `default` namespace though.
> 
> In general, I'm using the `default` namespace as the Forge test "control plane", as it's easier for operators to use with `kubectl` directly without specifying an additional `-n` flag which might get quite verbose or confusing. I'm generally of the opinion that we can keep things in `default` namespace as long as it's relevant to most users
> 
> Also, I don't expect the `default` namespace to be used for Forge testing itself. In fact, we should discourage folks from using it. It's only supported because (1) we still need it to share some of the helm values between releases and (2) it's the namespace that TF does the initial deploy in. In practice, I'm using the `default` namespace to do initial validation only and then immediately cleaning it up with `forge` CLI.

Hmm. I still think we shouldn't use the default namespace for any of these things to be honest. You can also share helm values via another namespace and we can change terraform to not deploy into the default namespace. In general it's just not a great practice. In most of my previous jobs where we used k8s at bigger scale we didn't use the default namespace for anything.

For kubectl the recommended approach is to simply set your context to a different namespace whenever you have to do some work instead of repeatedly specifying it for one-off commands. I personally use https://github.com/ahmetb/kubectx for this (this is also https://github.com/kubernetes-sigs/krew/ plugin for it) and simply switch the namespace via `kubens <target_namespace>`.

Anyways. I don't want to block your PR on this but let's not use the namespace for anything further in future.

**Review by geekflyer — APPROVED** [review]

**Comment by geekflyer** [comment]
fyi technically our current forge implementation is sort of like a "poor mans" kubernetes operator - https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ .  It's pretty common to install these operators into their own namespace instead of default.

**Comment by rustielin** [comment]
Thanks for unblocking @geekflyer

I also use `kubectx`, but hadn't heard of `kubens` -- let me look into it. But yea I have a lot to learn on the k8s side too wrt Operator. I'll land this for now, but there is definitely a lot of room for improvement -- not only in Forge but also how we use k8s across all deployments too. Most of everything is installed in the default namespace in our TF reference deployments for instance :)

**Pull request merged**
