### PR TITLE
[aptos-node] do not use move-deps in the dependency tree

### PR DESCRIPTION
**Pull request by vgao1996**
Some Move crates use feature flags to control certain behaviors, with `move-stdlib` being the most notable one -- the "testing" feature controls whether testing natives (with ability to forge random signers) are included and whether the debug natives are no-ops.

`move-deps` includes all move packages in its dependency tree, forcing [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification). This means, as long as one package enables the "testing" feature, then it's always on for all client crates depending on `move-deps` and there is no way to turn it off. This also creates a somewhat hard-to-manage coupling between all clients -- one client may want to modify `move-deps` and that could accidentally cause wrong feature flags to be set for other clients, especially the validator software.

This PR replaces `move-deps` with direct references to Move crates and ensures that `aptos-node` and `aptos-vm` does not have `move-stdlib`'s "testing" feature flag enabled. Tests have been added to ensure this is indeed the case.

Nonetheless, this should not be seen as a total dismissal of `move-deps` and the dev experience problem it tries to solve: most (internal) Aptos developers don't necessarily want/need to manage Move dependencies precisely and it's error prone to have the git hashes of the Move crates scattered all around the repo. Sometimes folks also have a (somewhat reasonable) desire to have a unified set of feature flags throughout the repo in order to reduce surprises. It's just that this view is not compatible with the way feature flags are currently used within the Move repo, and it would not be wise to redesign them at the moment. We should revisit the problem at a later time and decide what would be a better way to deal with feature flags.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4639)

### CODE REVIEW

**Review by wrwg — COMMENTED** [review]
I do not understand why we need this massive change on the way how we importing Move. It looks to me like a regression. Why can't we just declare the relevant difference in feature usage by parameterizing the Cargo.toml of move-deps with a fleature flag and pass that through? The only difference ever should be whether you use move-deps in testing mode or not.

**Comment by vgao1996** [comment]
> Why can't we just declare the relevant difference in feature usage by parameterizing the Cargo.toml of move-deps with a fleature flag and pass that through?

The problem is exactly that we cannot. Some Move crates (e.g. `move-cli` & `move-unit-test`) always have the "testing" feature flag set, so if you include them in `move-deps`, then "testing" is set for all clients and there is no way you can turn them off. This is what I've been describing as "forced feature unification". This makes the `move-deps` pattern inherently fragile due to the (unnecessary) coupling it creates, unless we change the way we use feature flags within the Move repo, which I think will actually require some more systematic analysis and redesign.

I understand your frustration that now we have to maintain all of those git hashes everywhere, but I think that problem can be solved using the new dependency inheritance feature introduced in Rust 1.64: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace.  Josh & Alex have already started experimenting this.

**Comment by vgao1996** [comment]
Okay, so even with my fix, cargo finds another way to screw us up. 

It turns out 
1. When you run `cargo build` at workspace root, cargo does a feature unification for ALL CRATES within the workspace
2. If you run `cargo build` for individual packages however, cargo does not unify the crate with others in the workspace for features

This inconsistency is discussed in https://github.com/rust-lang/cargo/issues/4463. Personally, I have to say that (1) is a terrible, terrible design choice and I also think that requiring crate features to be strictly additive but not having any means to enforce them is simply asking for trouble. 

Here's the proposed workaround:
1. Gate `test_aptos_vm_does_not_have_test_natives` by a feature flag
2. Create a special CI task that runs this test individually
3. Make sure when we compile and deploy a new validator binary, we run it from the aptos-node crate 
  - @davidiw @sherry-x can we make sure we're on the same page regarding this?

**Comment by wrwg** [comment]
> Okay, so even with my fix, cargo finds another way to screw us up.
> 
> It turns out
> 
> 1. When you run `cargo build` at workspace root, cargo does a feature unification for ALL CRATES within the workspace
> 2. If you run `cargo build` for individual packages however, cargo does not unify the crate with others in the workspace for features
> 
> This inconsistency has been discussed in [rust-lang/cargo#4463](https://github.com/rust-lang/cargo/issues/4463). Personally, I have to say that (1) is a terrible, terrible design choice and that requiring crate features to be strictly additive but not having a well defined definition of "additive" nor any means to enforce them is simply asking for trouble.
> 
> Here's my proposed workaround:
> 
> 1. Gate `test_aptos_vm_does_not_have_test_natives` by a feature flag
> 2. Create a special CI task that runs this test individually
> 3. Make sure when we compile and deploy a new validator binary, we run it from the aptos-node crate
>    a. @davidiw @sherry-x can we make sure we're on the same page regarding this?

What you describe is known since long and the way how Rust features work. (Workspace hack was dealing with this, but in a way such that build at root is the same as in any subdir -- all features). It appears the `testing` feature is just not very well suited to _prevent_ something dangerous hits production given this setup.

What again is the problem we are solving? Inclusion of `debug` and `create_signer_for_test`? Could we add our own dedicated flag for this which influences how we build up the aptos_natives list?

**Comment by vgao1996** [comment]
The "testing" feature controls two things:
1. Whether `create_signer_for_test` is included in the list of native functions.
  a. We can get away with this by filtering out the native function, but only partially since the feature flag also affects gas parameters
2. Whether the debug functions are no-ops.
  a. This one has `#cfg(feature = "testing")` in the native function implementations. One workaround is to filter out the impl from move-stdlib and supply it with an alternative implementation, but this isn't particularly clean either...

**Comment by vgao1996** [comment]
> It appears the testing feature is just not very well suited to prevent something dangerous hits production given this setup.

Fully agreed.

**Comment by vgao1996** [comment]
Please continue the discussion in https://github.com/aptos-labs/aptos-core/pull/4660.

**Pull request closed without merging**
