### PR TITLE
[Token] Deprecate Token Coin Swap Module

### PR DESCRIPTION
**Pull request by areshand**
### Description
we restrict buyer cannot buy token while the lock time hasn't expire. This adds unnecessary restriction
### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/4545)

### CODE REVIEW

**Review by movekevin — APPROVED** [review]

**Review by chloeqjz — APPROVED** [review]

**Review by movekevin — CHANGES_REQUESTED** [review]
This changed since last review. Although I somewhat agree that this module is not necessary, completely deprecating it last minute is still very scary. What are the implications here?

**Comment by areshand** [comment]
> This PR has drastically changed since last review. Although I somewhat agree that this module is not necessary, completely deprecating it last minute is still very scary. What are the implications here?

Offline discussed with @davidiw that we don't want to maintain this module to reduce our burden.
already reached out to biggest user souffl and they are ok with maintain their own version

**Review by davidiw — COMMENTED** [review]
Good for me, let's bring this up in the GK slack channel just for the sake of sharing with folks.

**Comment by movekevin** [comment]
> > This PR has drastically changed since last review. Although I somewhat agree that this module is not necessary, completely deprecating it last minute is still very scary. What are the implications here?
> 
> Offline discussed with @davidiw that we don't want to maintain this module to reduce our burden. already reached out to biggest user souffl and they are ok with maintain their own version

Alright makes sense. Thanks for the clarification.

**Review by movekevin — APPROVED** [review]

**Pull request merged**
