### PR TITLE
[docs] Make API page an index into multiple spec pages

### PR DESCRIPTION
**Pull request by banool**
## Description
Showing any one spec on the docs site is likely going to lead to confusion. Different devs will look at the spec expecting it to match their development target, be it devnet, latest, AIT, etc. To avoid this, we should instead make the index a landing page to point to the different specs. This PR does that.

We will need to fix up the copy, I just wrote whatever, it could read better for sure.

## Test Plan
```
cd developer-docs-site
yarn start
```
Visit http://localhost:3000/api/api-index and see the different spec pages linked there.

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2422)

### CODE REVIEW

**Comment by banool** [comment]
Spoke offline with @rajkaramchedu, one thing that would be great is to fix the URLs used for the "try it" feature. For some spec types, we might instead disable the feature, since there is no node to talk to (e.g. the spec from the head of main).

**Comment by banool** [comment]
So if we're going to support the tryit feature, we shouldn't pull the spec from GitHub, we should just link to the node. So summarizing:

- For latest, for which we have no node running, use `spec.html` like we do now in this PR, where we pass in the URL of the spec file. We should have hideTryIt enabled for this case.
- For devnet and other spec options where we have a node running, we should just link straight to the spec hosted there, e.g. https://ait2.aptosdev.com/spec.html.

The main reason not to do it this way is if we're worried about the load it will introduce on the node. If that's too much of a worry, we just do the first approach for every spec type.

One other thing, for the tryit feature, we need to figure out a way to change the URL it is targeting, it just defaults to the URL the page is being served from. 

For now I've updated the PR to disable the tryIt feature, in which case everything else is correct.

**Review by davidiw — APPROVED** [review]

**Comment by rajkaramchedu** [comment]
I want to spend some time figuring out the URL thing before we merge this. As the docs appear now, there is no information about the URL anywhere, just the info on the end points. For the devnet, the API url they should use for their curl command, for example for the transactions endpoint, is this, right? `https://fullnode.devnet.aptoslabs.com/transactions`? If yes, then I will mention it in the index page. For the latest, would it something like localhost on the index page?

**Comment by rajkaramchedu** [comment]
Wait. Didn't mean to include the yaml file. Fixing now.

**Review by rajkaramchedu — APPROVED** [review]

**Comment by rajkaramchedu** [comment]
@banool take a look. We can merge this for now if you are okay with it.

**Comment by banool** [comment]
Okay landing. Note, when we cut devnet again, we'll likely have to update the URL for the devnet spec.

**Pull request merged**
