### PR TITLE
[Dev Docs] Add a quick start tip for fullnode syncing.

### PR DESCRIPTION
**Pull request by JoshLind**
### Description

This PR provides a quick start tip for state sync configuration. Some users in discord have asked for a cheat sheet like this. It also provides a step a forward for https://github.com/aptos-labs/aptos-core/issues/6308, but doesn't address all use cases 😄 

Screen Shot 2023-02-16 at 5 10 47 PM

### Test Plan
Manual verification.

### CODE REVIEW

**Review by clay-aptos — APPROVED** [review]
Thanks, Josh! This LGTM with some link mods I made directly. Please let me know if this is something we should note in See what's new.

**Comment by JoshLind** [comment]
> Thanks, Josh! This LGTM with some link mods I made directly. Please let me know if this is something we should note in See what's new.

Thanks @clay-aptos -- probably no need, it's a tiny change 😄

**Comment by 0xhiro** [comment]
Thanks a lot for this! Very helpful tip!

**Comment by 0xhiro** [comment]
Ahh! Thanks!

**Pull request merged**
