### PR TITLE
Clean up wallet docs

### PR DESCRIPTION
**Pull request by kent-white**
### Description
There was confusion on some wallet docs that got out of date.
1. building-wallet-extension was very old and no longer is needed with the contents of the other docs
2. "Building your own wallet" was confusing David on what the wallet standard was. This is now "Wallet Standard"

### Test Plan
yarn start

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5525)

### CODE REVIEW

**Comment by davidiw** [comment]
let's not add yarn.lock?

**Comment by davidiw** [comment]
done!

**Review by davidiw — APPROVED** [review]
now that's a good pr

**Comment by kent-white** [comment]
ahh right, y'all use npm here

**Comment by kent-white** [comment]
@davidiw couldnt have done it without you

**Comment by davidiw** [comment]
I just follow the beat from my own :drum:

**Comment by clay-aptos** [comment]
Thank you, @kent-white !

**Pull request merged**
