### PR TITLE
[dashboards] configurable datasource and chain_name

### PR DESCRIPTION
**Pull request by rustielin**
Generalize the dashboards with more templates! Addresses https://github.com/aptos-labs/aptos-core/issues/543

This makes it so that we can unify all our dashboards, regardless of the underlying deployment. We can also ship metrics to a remote prometheus server responsible for holding metrics for many chains if we'd like.

For each existing dashboard:
* Variable for `datasource`, so we can use remote prometheus as well as the onboard one for testnets for backup. Include it in each panel's default
* Variable for `chain_name`, so we can distinguish metrics from different chains that share the same remote prometheus.

# Test

Tested on standalone remote grafana, as well as existing devnet grafana for backwards compatibility

### CODE REVIEW

**Review by gregnazario — APPROVED** [review]
Maybe rename the datasources to be shorter but otherwise, let's ship it.  It works well at selection

**Comment by rustielin** [comment]
thanks @gregnazario! 

/land

**Comment by sherry-x** [comment]
This will break the validator-lite dashboard again, could you please add the chain_name there too?

**Comment by rustielin** [comment]
ok edited, lmk what you think @sherry-x . We'll likely have to revisit all our prometheus configs. For example, we're not currently doing remote_write from central prometheus (so we don't have backup of the metrics from validator-lite deployments), but we should

**Review by sherry-x — APPROVED** [review]

**Pull request closed without merging**
