### PR TITLE
[cli] add aptos-db-tool cli to integration all commands about db

### PR DESCRIPTION
**Pull request by ccbond**
#2836 

### Description
1. Make a new crate that merges all 3 of these tools into one tool, named aptos-db-tool and have subcommands.
2. Change the build to only build and use this new tool.
3. Change all usages and references to these original tools to the new tool.

### Test Plan

The same as origin cmds about aptos db.

### CODE REVIEW

**Review by msmouse — CHANGES_REQUESTED** [review]
I understand where you are coming from, but this is way too big a change at once. We need to plan and design the interface properly if a super db tool is indeed needed. This PR in its current state doesn't cut it. for example, the bootstrap command is one of the `aptos` cli sub commands which is a duplication of the `db-restore auto` subcommand. Now the same functionality exists twice in this proposed cli tool.

**Comment by ccbond** [comment]
> I understand where you are coming from, but this is way too big a change at once. We need to plan and design the interface properly if a super db tool is indeed needed. This PR in its current state doesn't cut it. for example, the bootstrap command is one of the `aptos` cli sub commands which is a duplication of the `db-restore auto` subcommand. Now the same functionality exists twice in this proposed cli tool.

Thank you for your comment. We really need to plan and design the interface well first. I would appreciate it if you would take the time to help me and guide me through the planning and design process.

**Comment by msmouse** [comment]
https://github.com/aptos-labs/aptos-core/pull/6509
@ccbond: @areshand is trying to attack this in a less intrusive way without copying large chunk of code.

**Comment by ccbond** [comment]
> @ccbond: @areshand is trying to attack this in a less intrusive way without copying large chunk of code. see #6509
yeh i see. thanks.

**Pull request closed without merging**
