### PR TITLE
Make Rust first-transaction example in dev docs site use the Rust SDK

### PR DESCRIPTION
**Pull request by banool**
## Description
In this PR I update the first-transaction example in Rust to use the SDK instead of implementing everything itself. I also make it a proper example in the cargo sense, meaning it lives under `examples/` in the sdk directory.

I add a CoinClient like with the TS SDK, but I see our regular rest client already has some coin stuff there. I think we should probably remove that at some point and just use CoinClient. Whether CoinClient should just live in the SDK or in its own crate is another question (probably the latter down the line). If there are no objections I'll land this as is and open an issue to clean this up.

This depends on these PRs landing first:
- https://github.com/aptos-labs/aptos-core/pull/2866
- https://github.com/aptos-labs/aptos-core/pull/2869

## Test Plan
Run a local testnet (only necessary right now bc devnet is old):
```
cargo run -p aptos -- node run-local-testnet --with-faucet --faucet-port 8081 --force-restart --assume-yes
```

Set necessary env vars:
```
export APTOS_NODE_URL="http://127.0.0.1:8080"
export APTOS_FAUCET_URL="http://127.0.0.1:8081"
```

Run the example in the SDK:
```
cd sdk
cargo run --example transfer-coin
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2870)

### CODE REVIEW

**Review by davidiw — COMMENTED** [review]
cool stuff!! let's figure out the right way to present these. I'm not a big fan of adding in the ugly markup for importing... and these should be actually in the sdk, whatever that means....

**Comment by rajkaramchedu** [comment]
Docs deploy preview isn't built for this, I wonder why.

**Comment by rajkaramchedu** [comment]
Approving in the interest of landing this. But I am curious, why docs build isn't happening for this? I do like to see the built docs while reviewing a docs PR.

**Review by rajkaramchedu — APPROVED** [review]

**Comment by banool** [comment]
It's because it's stacked on another PR I believe. I'll just land both though, we can tweak again later.

**Pull request merged**
