### PR TITLE
[compiler-v2][decompiler] Pulling fat-loop algorithm out of the prover

### PR DESCRIPTION
**Pull request by wrwg**
## Description

The prover actually has a full-fledged loop analysis for stackless bytecode for loop invariant instrumentation and unrolling. This loop analysis is a major part of the logic for decompilation. This PR pulls out this functionality in a new general purpose module, `fat_loop`. Its mostly a refactoring of existing code.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [x] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [x] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

Existing prover tests

### CODE REVIEW

**Comment by wrwg** [comment]
* **#14488** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14488?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wrwg and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by wrwg — COMMENTED** [review]
@gedigi FYI regards ongoing discussion

@meng-xu-cs nice piece of code!

**Review by vineethk — APPROVED** [review]

**Review by rahxephon89 — APPROVED** [review]

**Review by brmataptos — COMMENTED** [review]
Why do you call this a "fat loop"?

**Review by brmataptos — APPROVED** [review]
Oh, I see "fat loop" was in the old code.  I suppose it is intended to mean a loop with possibly multiple back-edges to the header.  Looks good.

**Pull request merged**
