### PR TITLE
[Token] use flat map to replace the nested table

### PR DESCRIPTION
**Pull request by areshand**
### Description
to remove the nested table from token transfer

### Test Plan
updated unit test

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3506)

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
this is amazing!

are there no goldens?

**Comment by davidiw** [comment]
This is one of those unfortunate PRs that we would really benefit to have in Mainnet to mitigate the proliferation of tables and wasted slots. This defines the safe method for performing "unilateral sends". Without it, assuming we send 1 NFT to N individuals, we create 2*N storage slots.

I'll dig up the old formatting for making these type of PR requests now that we're frozen, but I know we want to stabilize for longevity testnet asap.

I didn't realize how quickly @areshand would be at writing this, but I also wanted to flag this one to @sherry-x since I believe it is the last storage layout changing PR that I'm aware of -- knock on wood.

**Comment by areshand** [comment]
> I didn't realize how quickly @areshand would be at writing this, but I also wanted to flag this one to @sherry-x since I believe it is the last storage layout changing PR that I'm awa

no golden required. only failed tests are the example test which is irrelevant to this PR

**Comment by areshand** [comment]
need one more signer to land @msmouse take a look from storage side?

**Review by chloeqjz — APPROVED** [review]

**Pull request merged**
