### PR TITLE
[vm][trivial] Fix dyn traits with associated types

### PR DESCRIPTION
**Pull request by georgemitenkov**
### Description

`dyn` traits need to know their associated types in Rust.

### Test Plan

CLion complains otherwise.

### CODE REVIEW

**Review by gelash — APPROVED** [review]

**Comment by gerben-stavenga** [comment]
@vgao1996 Is this true. I think this is just a bug in CLion. I'm pretty sure rustc is the authority about rust language and not clion rust plugin

**Review by vgao1996 — APPROVED** [review]

**Comment by vgao1996** [comment]
Yeah actually @georgemitenkov can you attach a screen shot of the errors CLion is complaining about?

**Review by vgao1996 — CHANGES_REQUESTED** [review]
Yeah actually @georgemitenkov can you attach a screen shot of the errors CLion is complaining about? @gerben-stavenga had a point and if there's an actual error, then it should have been caught by the CI. Let's understand what's really happening before moving forward. Although sometimes you do have to add annotations to work-around extension-specific issues or otherwise it's gonna hurt your own productivity.

**Comment by gerben-stavenga** [comment]
> Yeah actually @georgemitenkov can you attach a screen shot of the errors CLion is complaining about? @gerben-stavenga had a point and if there's an actual error, then it should have been caught by CI. Let's understand what's really happening before moving forward. (Although I understand that sometimes you do have to add annotations to work-around extension-specific issues or otherwise it's gonna hurt your own productivity.)

If there is a productivity problem, I have the strong feeling that Key of TStateView is never anything else then Vec<u8> and TStateView another useless boilerplate concept. So removing it in lieu of just StateView seems to me the proper fix.

**Comment by vgao1996** [comment]
> Although I understand that sometimes you do have to add annotations to work-around extension-specific issues or otherwise it's gonna hurt your own productivity.

Well I was more talking about bugs in extensions that distracts you with false alarms. We had a lot of these in the early days with RLS, but I think things have improved a lot with rust-analyzer. Particularly it has been dealing with associated types pretty well for a while, so I'd be curious to find out what exactly is wrong in this case.

I've also been curious why we introduced `TStateView`. Maybe @zekun000 or @msmouse have some insights to share?

**Comment by gelash** [comment]
> > Although I understand that sometimes you do have to add annotations to work-around extension-specific issues or otherwise it's gonna hurt your own productivity.
> 
> Well I was more talking about bugs in extensions that distracts you with false alarms. We had a lot of these in the early days with RLS, but I think things have improved a lot with rust-analyzer. Particularly it has been dealing with associated types pretty well for a while, so I'd be curious to find out what exactly is wrong in this case.
> 
> I've also been curious why we introduced `TStateView`. Maybe @zekun000 or @msmouse have some insights to share?

not being snarky but if you did git blame you could answer the last question, or find the culprit to ask, which would be me :-)
Here is where TStateView was introduced:
https://github.com/aptos-labs/aptos-core/commit/2bab2aa6064ad2d89ca660d484b563e494d426d1#diff-0850703147c60987676b705c379025021736bd3b8ec75596dbcba6281caa8fc0
It allowed us to remove tons of crap from aptos_vm and block executor wrapper, unify the view handling for the crate, merge the flows for sequential and parallel execution, unify testing, then remove unnecessary sync traits. there was a lot. Not that generic StateView is necessarily needed, just from the way code was structured and given the generic nature of MVHashMap and BlockExecutor (which does help with testing a ton), it made sense to also have it generic.

**Comment by gerben-stavenga** [comment]
Yes if the associated type is unspecified you have to specify it you can
not make functions that still need monomorphization dynamic. But stateview
definition specifies the key completely

**Comment by davidiw** [comment]
So we're adding some attribution to satisfy a lint in an ide?
`vim` doesn't have these issues :grinning:

**Comment by gelash** [comment]
> So we're adding some attribution to satisfy a lint in an ide? `vim` doesn't have these issues 😀

You should see emacs! Doesn't have these issues even more :D

**Comment by vgao1996** [comment]
Not familiar with CLion and its Rust plugin. Does it use rust-analyzer?

**Comment by georgemitenkov** [comment]
Quoting JetBrains: 
> The plugin’s language analysis is implemented from scratch, leveraging the [IntelliJ Platform](https://www.jetbrains.com/opensource/idea/) infrastructure for incremental analysis and indexing. However, IntelliJ Rust shares some code for procedural macros expansion with [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer).

**Comment by msmouse** [comment]
Moving TStateView to the VM realm (And use it exclusively in the VM) seems the right thing to do.. @gelash ?

**Pull request closed without merging**
