### PR TITLE
github action summary for rust unit tests

### PR DESCRIPTION
**Pull request by brianolson**
## Description
Add script to end of Rust Unit Tests github action to create markdown summary of run

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [X] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [X] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?
Local development against the output of `cargo nextest`

## Key Areas to Review
This should do nothing bad if the script fails due to changing environment or data. CICD should proceed or not based on the unit tests passing.

## Checklist
- [X] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I identified and added all stakeholders and component owners affected by this change as reviewers
- [X] I tested both happy and unhappy path of the functionality
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ibalajiarun** [comment]
The summary is verbose too. It's just at the end. Would it be better to just print failing tests and a count summary?

**Comment by brianolson** [comment]
I tweaked it for better HTML output for the Job Summary, nicer table and only the first 20 failing test names.
I also have it echo all the failed test names to stdout so that they're easier to find right at the end of the log.

**Comment by brianolson** [comment]
sample output `https://github.com/aptos-labs/aptos-core/actions/runs/8526514325?pr=12767#summary-23355940219`

**Comment by brianolson** [comment]
I copied a previous version of this into another PR that has weirdly failing tests (probably unrelated? probably just flakey?) and I think this is a useful summary: `https://github.com/aptos-labs/aptos-core/actions/runs/8540104243?pr=12730`

**Review by sionescu — APPROVED** [review]

**Review by aluon — APPROVED** [review]

**Pull request merged**
