### PR TITLE
[CircleCI] Remove duplicated circleci test

### PR DESCRIPTION
**Pull request by areshand**
## Motivation

The two tests are duplicate and are also flaky as well. 
While they are running the same test, usually only one of them will succeed

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?
Yes

(You must have submitted a [signed CLA](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#contributor-license-agreement) that includes your GitHub handle prior to us accepting and landing your work. Write your answer here.)

## Test Plan
Remove duplicated test

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/aptos-labs/aptos-core/tree/main/developer-docs-site, and link to your PR here.)

### CODE REVIEW

**Comment by rustielin** [comment]
@areshand you need to replace usage of `docker-compose-test` and `sdk-typescript-test` in the workflow definition as well

**Comment by areshand** [comment]
could I land this one since there is known flaky tests?  this one is to reduce the some flaky issues @rustielin

**Review by rustielin — APPROVED** [review]
yea let's land this

**Pull request merged**
