### PR TITLE
[CLI] Add `ed25519` vanity account generator, docs

### PR DESCRIPTION
**Pull request by alnoki**
@gregnazario @clay-aptos

This PR adds to the `aptos` CLI a `--vanity-prefix` option for `ed25519` key generation.

A user can supply a vanity prefix like `0xace` or `d00d` (with or without a leading `0x`), then the CLI generates private keys until finding one with an account address that begins with the specified prefix. An example is provided in the updated documentation.

@clay-aptos note that the failing docs lint pass is due to spellchecks on content *not* from this PR.

### CODE REVIEW

**Comment by alnoki** [comment]
@gregnazario this is my first Rust PR so I wasn't quite sure of all the commands I needed to run before submission, but I've pinned it down to:

* From inside `aptos-core`:
```bash
/scripts/rust_lint.sh
```

* From inside `aptos-core/crates-aptos`:
```bash
cargo test
```

I am not sure why the testnet check failed, but since the devnet one is fine I do not think the tesnet check failure is a result of this PR.

**Comment by clay-aptos** [comment]
> @gregnazario @clay-aptos
> 
> This PR adds to the `aptos` CLI a `--vanity-prefix` option for `ed25519` key generation.
> 
> A user can supply a vanity prefix like `0xace` or `d00d` (with or without a leading `0x`), then the CLI generates private keys until finding one with an account address that begins with the specified prefix. An example is provided in the updated documentation.
> 
> @clay-aptos note that the failing docs lint pass is due to spellchecks on content _not_ from this PR.

Thanks, @alnoki . Taking care of the spellcheck terms in:
https://github.com/aptos-labs/aptos-core/pull/7526

**Review by alinush — APPROVED** [review]
LGTM: correctly picks a new random SK until the address has the desired prefix

**Review by movekevin — APPROVED** [review]

**Comment by alnoki** [comment]
@movekevin @alinush it looks like your two reviews make these changes approved. I merged in `main` so this PR should be ready to land!

@davidiw

**Pull request merged**
