### PR TITLE
[helm] add extraInitContainers to all aptos-node pods

### PR DESCRIPTION
**Pull request by rustielin**
### Description

Adds the ability to customize `initContainers` for validator, VFN, and PFN k8s pods.

Then use it in the TF/k8s testnet setup to unblock 500+ validator-scale tests by:
* Dump genesis data into s3 bucket
* Validators + VFNs fetch it from s3, rather than k8s ConfigMap/Secret, which do not work at that scale due to 1MiB etcd limit

Additional changes:
* New vars for TF testnet setup: `genesis_initcontainer_image` and `genesis_s3_retention_days`. These will likely be the last TF testnet changes before we start re-architecting it. For now, it's necessary to unblock testing
* Lifecycle policy on the s3 bucket at the `genesis/` path prevents pollution in environments with high churn, for example in Forge
* The default genesis initcontainer image uses a public ECR repository, which has the benefit of going through a pull-through cache on AWS

### Testnet genesis migration

For k8s testnets, the following must be executed in order for an in-place migration to be successful. The below example uses my personal testnet rustienet. Note the `era` stays the same:
1. `terraform apply` -- creating the bucket
2. `kubectl get secret  rustie-aptos-node-1-genesis-e125  -o json | jq -r '.data."waypoint.txt"' | base64 -d > rustienet-waypoint.txt` -- extract the existing waypoint
3. `kubectl get secret  rustie-aptos-node-1-genesis-e125  -o json | jq -r '.data."genesis.blob"' | base64 -d > rustienet-genesis.blob` -- extract the existing genesis
4. `aws s3 cp rustienet-waypoint.txt s3://$S3_BUCKET/genesis/e125-waypoint.txt` -- copy waypoint to s3
5. `aws s3 cp rustienet-genesis.blob s3://$S3_BUCKET/genesis/e125-genesis.blob` -- copy genesis to s3

### Test Plan

Testnet genesis works. Terraform apply

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5497)

### CODE REVIEW

**Review by perryjrandall — APPROVED** [review]

**Comment by rustielin** [comment]
Converting back to draft for now. After spending some time to think about the various k8s deployments that depend on this helm change, (e.g. existing validator deployments), the migration is a bit painful. This change is only useful for (1) testing purposes and (2) if you ever want to start a network again with large size genesis. (1) is likely going to be re-architected and (2) is likely not going to happen outside of incentivized testnets.

I'll hold off on landing this for now unless there's an urgent need, in which case k8s deployments would need a migration guide.

**Comment by davidiw** [comment]
if we're not moving forward with this, can we close the PR?

**Comment by rustielin** [comment]
Yea I'll close it. For now I've merged this in a separate branch which I'm using for forge called "forge-deployment".

**Comment by davidiw** [comment]
Thanks Rustie!

**Pull request closed without merging**
