### PR TITLE
[wallet]: fix signAndSubmitTransaction

### PR DESCRIPTION
**Pull request by Manahip**
### Description

We're actually trying to use the official wallet to submit user transaction. TypeScript would have called it out.

### Test Plan
Tested by using the wallet extension in our dex dapp (successful in sending user transactions after the fix).

---
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1665)

### CODE REVIEW

**Comment by Manahip** [comment]
@kent-white

**Comment by kent-white** [comment]
This looks good to me, thanks for the fix. 

FYI, we moved the wallet code to a separate repo and have been updating it there, so if you check out the latest release https://github.com/aptos-labs/aptos-core/releases/tag/wallet-v0.1.1 there are a-lot of updates/fixes.

Also see https://aptos.dev/guides/building-wallet-extension for the latest dapp documentation. We will be making a more official release soon hopefully. I was holding off on deleting it from apto-core just in case people wanted to use it as inspiration.

**Comment by Manahip** [comment]
I was wondering if I used the right wallet... is the new one open source somewhere? @kent-white

**Comment by kent-white** [comment]
@Manahip not yet!

**Pull request merged**
