### PR TITLE
[ecosystem] Revert to using puma without nginx.

### PR DESCRIPTION
**Pull request by zacharydenton**
### Description

Reverts to puma without nginx to avoid an issue with TCP connections not closing in GCP.

### Test Plan
Tested manually with `docker run --env-file .env -p 3000:3000`

### CODE REVIEW

**Comment by geekflyer** [comment]
do we actually still leverage passenger after this change at all?

**Comment by zacharydenton** [comment]
No, puma is used as the app server. We do still benefit from the preinstalled dependencies in the phusion/passenger-full base image however.

**Review by geekflyer — APPROVED** [review]
ok, can you just add a quick comment next to the FROM explaining why we're using passenger as base image and that we're not actually using passenger as webserver?

**Pull request merged**
