### PR TITLE
[WIP] [Executor] Getting rid of metadata cache

### PR DESCRIPTION
**Pull request by gelash**
### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/5183)

### CODE REVIEW

**Review by wrwg — CHANGES_REQUESTED** [review]
We do not want to get rid of it but instead synchronize flushing with the loader cache. We need a change in the Move repo for this first. So can we close this?

**Comment by gelash** [comment]
I don't believe that is what we want. The whole loader cache architecture must and will change, so adding dependencies between these caches in the interim is completely useless. Less caches, less bugs, before we do the right thing.

**Comment by wrwg** [comment]
> I don't believe that is what we want. The whole loader cache architecture must and will change, so adding dependencies between these caches in the interim is completely useless. Less caches, less bugs, before we do the right thing.

Diasgreed. We are working around the loader cache since quite a while (and without the workarounds I added here, PE would not work at all). This is another workaround we need to add. It can cost us 5-10% of execution time for transactions which abort if we don't. The new loader will not come before next year.

**Comment by gelash** [comment]
@wrwg and how many transactions abort? and what are the odds that the fixes cause further problems? let's discuss. This "working around" hack on top of hack causing problems every week has to stop.

**Comment by wrwg** [comment]
> @wrwg and how many transactions abort? and what are the odds that the fixes cause further problems? let's discuss. This "working around" hack on top of hack causing problems every week has to stop.

Not sure what you are talking about. There was not any problem around this corner since ~ 2 months.

**Pull request closed without merging**
