### PR TITLE
Extend multisig tutorial/SDK with automation tool

### PR DESCRIPTION
**Pull request by alnoki**
# Overview

This PR adds a multisig tool for multi-ed25519 account operations, and an associated tutorial walkthrough. See the developer docs site preview under the "Your first multisig" tutorial for more.

The tool enables authentication key rotation (adding/removing signatories, vanity address usage), module publication, and script invocation from a multisig account. Operations involving Move packages/scripts automatically download code from GitHub and compile locally, according to a provided repo and commit hash: this empowers signers to review code on GitHub before invoking the signing operation.

Compared with the v2 multisig schema per #5894 , operations achieved via the tool in this PR reduce the number of transactions required for consensus (the v2 multisig schema requires up to n + 2 transactions, where n is the number of signers). Hence this tool reduces overall gas required for multisig operations, and moreover, pays gas from the multisig account itself rather than from the accounts of signatories (as in the v2 schema). Per the tool in the PR, signatories do not even have to have on-chain accounts to participate in multisig consensus: an off-chain private/public keypair is sufficient.

This PR represents the second installment of content from #6356 (the first installment was #6788), per @davidiw 's [request to separate content accordingly](https://github.com/aptos-labs/aptos-core/pull/6356#issuecomment-1445483042).

# Housekeeping

The following commands were run in below paths:

aptos-core/:

```
pre-commit run --all-files
```

aptos-core/developer-docs-site/:
```
prettier '**/*.(tsx|ts|js)'
pnpm spellcheck
pnpm lint
```

aptos-core/ecosystem/python/sdk:
```
make fmt
make test
```

### CODE REVIEW

**Comment by alnoki** [comment]
@saharct @clay-aptos I notice that the recent text edits from 7348a79 remove subsection header numbers like 8.2 but preserve section header numbers like 8, which is not consistent across other tutorials: "Your First Dapp" does not number subsection headers, but "Your First Coin" does.

Are the edits from the recent commit a new stylistic rule to be applied across the repo? 

If you're still deciding between the two styles I'll indicate my preference for preserving subsection header numbers, a schema that makes it easier to refer to subsections in written/spoken speech (e.g. "Check out the Python snippet from section 8.2")

**Comment by clay-aptos** [comment]
> @saharct @clay-aptos I notice that the recent text edits from [7348a79](https://github.com/aptos-labs/aptos-core/commit/7348a79ab7b587f5834951c8564b8fef90e7aeef) remove subsection header numbers like 8.2 but preserve section header numbers like 8, which is not consistent across other tutorials: "Your First Dapp" does not number subsection headers, but "Your First Coin" does.
> 
> Are the edits from the recent commit a new stylistic rule to be applied across the repo?
> 
> If you're still deciding between the two styles I'll indicate my preference for preserving subsection header numbers, a schema that makes it easier to refer to subsections in written/spoken speech (e.g. "Check out the Python snippet from section 8.2")

Ack and agreed. They can make maintenance a little harder yet are worth it from a navigational standpoint. What do you think, @saharct ? Thank you both.

**Comment by saharct** [comment]
@alnoki, while I agree that numbering sub-steps can make it clearer when referring to them in spoken language, it can also make the instructions less flexible and harder to maintain, as @clay-aptos pointed out. We usually avoid referring to sub-step numbers and frequently hyperlink the necessary content within the instructions, so that users can go directly to the relevant section. In my personal opinion, using primary step numbers is sufficient and adding sub-steps can sometimes make a tutorial appear more overwhelming than it actually is. This style is followed in most of our docs, and I would move to bring the non-conforming ones in line with this approach.

**Comment by clay-aptos** [comment]
> @alnoki, while I agree that numbering sub-steps can make it clearer when referring to them in spoken language, it can also make the instructions less flexible and harder to maintain, as @clay-aptos pointed out. We usually avoid referring to sub-step numbers and frequently hyperlink the necessary content within the instructions, so that users can go directly to the relevant section. I believe using primary step numbers is sufficient and adding sub-steps can sometimes make a tutorial appear more overwhelming than it actually is. This style is followed in most of our docs, and I would move to bring the non-conforming ones in line with this approach.

Let's make sure we optimize for the user. I am adding some of our tutorial contributors to offer their:
@gregnazario , @0xchloe and @0xmaayan , should we number sub-sections of tutorials, as well as primary sections? Thanks, all.

**Comment by davidiw** [comment]
Thanks for the contribution @alnoki, maybe we should have began the conversation earlier, but this is a large contribution. Considering that we are not bullish on multi-ed25519 and instead are heading down the path of Multi-Account... I'd like to get your take.

Also I am planning on migrating Python SDK to Async because ... it works a lot better for any application that demands throughput.

Ultimately anything we publish here, the team has to take the responsibility for supporting it.

Another thing to contemplate is that @clay-aptos has kicked off a contributors section, so we could consider linking to that and the guide.

**Comment by alnoki** [comment]
> Thanks for the contribution @alnoki, maybe we should have began the conversation earlier, but this is a large contribution. Considering that we are not bullish on multi-ed25519 and instead are heading down the path of Multi-Account... I'd like to get your take.

@davidiw I'm assuming here that by Multi-Account you are referring to the functionality from #5894, which certainly expands upon multisig tooling available to the developer. I agree that plenty of devs will migrate over to this new model, especially with support from MSafe, but still there are some disadvantages to the model that are solved by this PR. I mentioned a few in the PR header at the top, but for more detail:

* For $n$ signers, the Multi-Account model requires up to $n + 2$ transactions, whereas the tool in this PR requires only 1
* The Multi-Account model requires signatories to sign off on a transaction payload or the hash of a payload, without offering a human-readable interface for verifying transaction content. This contrasts with the tool in this PR, which provides detailed metadata on authentication key rotation, a GitHub repo and commit hash of a module to publish or script to invoke, etc.
* The Multi-Account model immutably records in ongoing history a proposer, who is thus conferred with an additional status that has potentially adverse social consequences, whereas the tool in this PR simply crafts a transaction with all signatories in the same stature. Essentially the tool in this PR submits the transaction at runtime in a context that is more of a concerted effort from all signatories, and this structure provides a potentially advantageous form of ambiguity. In contrast, being the proposer on a transaction may carry additional liability depending on the context.
* The tool in this PR includes support for vanity address generation, which is not supported by the Multi-Account model.
* The Multi-Account model requires that all signatories have on-chain accounts, whereas the tool in this PR only requires an off-chain private/public keypair. This isolation reduces security risk, especially as there is not yet official Ledger support.

I do not mention all of these drawbacks to disparage the Multi-Account model: it is an outstanding improvement to the framework, and the motivation for this PR is simply to include in official Aptos tooling a means for other developers to accomplish what can is not necessarily supported by the Multi-Account model. In particular, vanity address generation, module publication, and script invocation. Perhaps @movekevin can provide additional commentary on this front.

> Also I am planning on migrating Python SDK to Async because ... it works a lot better for any application that demands throughput.
> Ultimately anything we publish here, the team has to take the responsibility for supporting it.

As for Async, I don't believe that concurrency support necessarily affects the tool in this PR: everything is handled serially from a CLI context anyways, so unless there are massive sweeping changes to the Python SDK coming down the pipeline nothing should require upgrade support.

> Another thing to contemplate is that @clay-aptos has kicked off a contributors section, so we could consider linking to that and the guide.

This is already in the works with #7308 !

**Comment by davidiw** [comment]
@alnoki , I spoke with the teams that manage our SDKs and support the ecosystem efforts and while we greatly appreciate the contribution, we're just not in the position to manage and support this effort at this point in time:
* When people discover content directly on aptos.dev, they expect the team that manages that to support that content
* We tend to lead major features in Rust or TypeScript and leave Python for external contributors (thank you so much) and for my own personal exploration -- you'll notice the recent investigation on performance with async and http2.
* we're very happy to point to this contribution on say Econia's github and what not from our dev site, but want to be very clear that it isn't maintained or supported by those that manage aptos.dev



On to your points about multi-ed25519, there are some interesting points. Let's chat more about that in another thread... we will eventually have to get and support these types of initiatives :)

**Comment by alnoki** [comment]
> @alnoki , I spoke with the teams that manage our SDKs and support the ecosystem efforts and while we greatly appreciate the contribution, we're just not in the position to manage and support this effort at this point in time:
> 
> * When people discover content directly on aptos.dev, they expect the team that manages that to support that content
> * We tend to lead major features in Rust or TypeScript and leave Python for external contributors (thank you so much) and for my own personal exploration -- you'll notice the recent investigation on performance with async and http2.
> * we're very happy to point to this contribution on say Econia's github and what not from our dev site, but want to be very clear that it isn't maintained or supported by those that manage aptos.dev
> 
> On to your points about multi-ed25519, there are some interesting points. Let's chat more about that in another thread... we will eventually have to get and support these types of initiatives :)

@davidiw Since Python is not considered a primary feature pipeline, would there be an opportunity to incorporate similar functionality into the Rust SDK or even the `aptos` CLI? This could be done in a coordinated manner with more granularity on implementation PRs, based on the Multi-Account model,

> Considering that we are not bullish on multi-ed25519 and instead are heading down the path of Multi-Account... 

Basically the motivation behind this PR is to provide a module deployment and governance solution that is not possible with existing tools, generalized in a manner that allows for devs across the ecosystem to deploy and govern through standard methods. As I mentioned above the tool in this PR has some unique advantages that would be lost by building around the Multi-Account model, but they are not total dealbreakers.

For a Multi-Account based solution in Rust, for example, the following SDK features would be useful:

* Password protection on private keyfiles
  * The PR tool uses fernet encryption, for example 
* Support for vanity address generation
  * Mining a forum account until the derived Multi-Account resource account matches a vanity prefix
* Module publication and upgrading
  * Specified by an input file(s), or by a GitHub repo/file location and commit hash (as in the PR tool)
* Move script invocation support
  * Specified by an input file, or by a GitHub repo/file location and commit hash (as in the PR tool)

**Comment by clay-aptos** [comment]
@alnoki can we compromise and keep the tutorial on Aptos.dev and listed on the Community Highlights page and publish the tool to the Econia site (or your GH location of choice) and link to it from the External Resources list?
https://aptos.dev/community/external-resources

Thank you for your work on this!

**Comment by alnoki** [comment]
> @alnoki can we compromise and keep the tutorial on Aptos.dev and listed on the Community Highlights page and publish the tool to the Econia site (or your GH location of choice) and link to it from the External Resources list? https://aptos.dev/community/external-resources
> 
> Thank you for your work on this!

@clay-aptos we are discussing internally how to handle this moving forward: ideally there will be an official solution (e.g. potentially one that involves Rust per above discussions with @davidiw), and if that is the case then we will end up just endorsing the official solution

**Comment by davidiw** [comment]
> @clay-aptos we are discussing internally how to handle this moving forward: ideally there will be an official solution (e.g. potentially one that involves Rust per above discussions with @davidiw), and if that is the case then we will end up just endorsing the official solution

Thanks for the heads up, will bring it up with the platform team :)

**Comment by alnoki** [comment]
> @alnoki , I spoke with the teams that manage our SDKs and support the ecosystem efforts and while we greatly appreciate the contribution, we're just not in the position to manage and support this effort at this point in time:
> 
> * When people discover content directly on aptos.dev, they expect the team that manages that to support that content
> * We tend to lead major features in Rust or TypeScript and leave Python for external contributors (thank you so much) and for my own personal exploration -- you'll notice the recent investigation on performance with async and http2.
> * we're very happy to point to this contribution on say Econia's github and what not from our dev site, but want to be very clear that it isn't maintained or supported by those that manage aptos.dev
> 
> On to your points about multi-ed25519, there are some interesting points. Let's chat more about that in another thread... we will eventually have to get and support these types of initiatives :)

@davidiw I believe I have provided comparable functionality in Rust/Multisig v2 per #7521,  #7693, #7694, #7709, #7776, #7790, #7916, #8321, and #8346

**Comment by davidiw** [comment]
hit me up on a DM to discuss how to proceed.

**Pull request closed without merging**
