### PR TITLE
Refactor object deployment CLI commands

### PR DESCRIPTION
**Pull request by JohnChangUK**
## Description
Refactor the CLI commands for deploying and upgrading code objects.
Currently, the commands for deploying and upgrading are:
- `aptos move create-object-and-publish-package --address-name my_module --named-addresses my_module=<my_module_addr>`
- `aptos move upgrade-object-package --object-address <code_object_addr> --named-addresses my_module=<my_module_addr>`

These commands are too long and hard to remember, giving a bad user experience. This PR shortens these commands to a single command. Shown below:

### Example commands
Deploy code to object - `deploy-object`
`aptos move deploy-object --address-name my_module`

Upgrade code object - `upgrade-object`
`aptos move upgrade-object --address-name my_module --object-address <code_object_addr>`

## Additional feature:
- Add CLI commands for shorter object deployment commands

## Notes
This is a stripped down version of this PR: https://github.com/aptos-labs/aptos-core/pull/13617
The attached PR includes CLI commands to transfer ownership of the code object. To be added after this PR lands.

### Notes
Have not removed the old commands `create-object-and-publish-package` and `upgrade-object-package` due to risk of people still using the commands.

## Type of Change
- [] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [X] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [X] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?
Tests added in `e2e-move-tests` and manually tested and verified by compiling the CLI locally.

## Checklist
- [X] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I identified and added all stakeholders and component owners affected by this change as reviewers
- [X] I tested both happy and unhappy path of the functionality
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by JohnChangUK** [comment]
This is a stripped down version of this PR: https://github.com/aptos-labs/aptos-core/pull/13617
The attached PR includes CLI commands to transfer ownership of the code object. To be added after this PR lands.

**Review by davidiw — COMMENTED** [review]
No tests?

**Comment by JohnChangUK** [comment]
> No tests?

Tests already exist here: https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/e2e-move-tests/src/tests/object_code_deployment.rs

There are none for CLI commands, manual testing was done however

**Comment by 0xjunha** [comment]
LGTM! Are we going to keep both (CreateObjectAndPublishPackage, UpgradeObjectPackage) and (DeployObject, UpgradeObject)?

**Review by 0xjunha — APPROVED** [review]

**Comment by JohnChangUK** [comment]
> LGTM! Are we going to keep both (CreateObjectAndPublishPackage, UpgradeObjectPackage) and (DeployObject, UpgradeObject)?

For now yes, this is to not break backwards compatibility, (if people are already using these commands programatically etc)

**Review by davidiw — APPROVED** [review]

**Pull request merged**
