### PR TITLE
[token] cherry pick token changes for mainnet release

### PR DESCRIPTION
**Pull request by areshand**

### CODE REVIEW

**Review by movekevin — DISMISSED** [review]

**Comment by areshand** [comment]
@perryjrandall  @runtian-zhou  and @sherry-x  could you please take a look?

**Comment by wrwg** [comment]
Are you sure you are merging against the correct branch? IIRC the next mainnet and current testnet is `mainnet-20221115`

**Comment by areshand** [comment]
> IIRC the next mainnet and current testnet is `mainnet-20221115`
@movekevin  what is the right branch I should merge into ?

**Comment by davidiw** [comment]
Per Wolfgang, the correct destination is mainnet-20221115

**Pull request merged**
