### PR TITLE
[codeowners] update CODEOWNERS

### PR DESCRIPTION
**Pull request by alinush**
### Description

Adding myself as a code owner for the TypeScript implementation of an Aptos account, due to the cryptographic operations there.

...and for other crypto-related things.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3589)

### CODE REVIEW

**Review by davidiw — CHANGES_REQUESTED** [review]
This file is already becoming untenable. I might recommend that you just list out crates and we re-evaluate this at a future date?

**Comment by alinush** [comment]
> This file is already becoming untenable. I might recommend that you just list out crates and we re-evaluate this at a future date?

What do you mean? If there's a problem is that folks are not sorting the entries... but that's easily fixable with a lint check or something.

I need to be codeowner on these things to catch potential cryptographic flaws...

**Comment by davidiw** [comment]
I'd argue that this is not going to be a very reasonable way to help this scale:
* You as an individual are trying to track cryptographic changes
* Cryptographic features can randomly appear in new code
I think we need a better system for this. At Facebook, we could subscribe to regular expression matches. We should explore something like that. I do wonder if GitHub has something more powerful.

**Comment by davidiw** [comment]
I'd like for us to at least know that there's no trivial way to get what we want before we land this. @alinush wants to follow crypto usage. He will undoubtedly not using this approach.

**Comment by gregnazario** [comment]
I think it will be hard to be adding yourself as a crypto owner on every single package basically.

If you want to be added to all crypto related things, we should just inform the team to keep you in the loop

**Comment by alinush** [comment]
> I think it will be hard to be adding yourself as a crypto owner on every single package basically.
> 
> If you want to be added to all crypto related things, we should just inform the team to keep you in the loop

Let's just move forward with these 3 changes to CODEOWNERS for now.

**Review by davidiw — APPROVED** [review]

**Pull request merged**
