### PR TITLE
[Documentation] Update run-a-fullnode.md

### PR DESCRIPTION
**Pull request by WlanKasper**
Incorrect path in first step in the guide

## Motivation

Incorrect path in second line in guide (https://aptos.dev/tutorials/run-a-fullnode/#hardware-requirements):
git clone https://github.com/aptos-labs/aptos-core.git
cd aptos
./scripts/dev_setup.sh
source ~/.cargo/env

It must be:
cd aptos-core

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

This is a README change, it does not affect the algorithm

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/aptos-labs/aptos-core/tree/main/developer-docs-site, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for the release.
 * What workarounds and alternative we have if we do not push the PR.

### CODE REVIEW

**Comment by sherry-x** [comment]
Thank you for putting up the fix! Could you please sign the CLA doc here? https://github.com/aptos-labs/aptos-core/blob/main/documentation/contributing/individual-cla.pdf

**Comment by WlanKasper** [comment]
Done!

**Review by sherry-x — APPROVED** [review]
Thank you so much!

**Pull request merged**
