### PR TITLE
added included artifacts options in compilation and publishing of mod…

### PR DESCRIPTION
**Pull request by butabara**
Made test crate publish + compile functions take included_artifacts as an optional parameter.

### Test Plan

- - -
This change is [Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/3768)

### CODE REVIEW

**Review by davidiw — COMMENTED** [review]
PR looks fine, but why add this?

**Comment by butabara** [comment]
> PR looks fine, but why add this?

I am trying to run a node locally through my integration tests, and to do this I used the CLI Test Framework. However I noticed my program is bigger than the size limit if all artifacts were included which is what the CLI Test Framework was doing by default. So I decided to make it an optional parameter for users that are also trying to do the same thing.

**Review by davidiw — CHANGES_REQUESTED** [review]
the code that you're modifying is for tests only, I don't see how it helps you.

the cli already exposes this via: https://github.com/aptos-labs/aptos-core/blob/0582c623cc46a348428fcca2ef61d25712739db8/crates/aptos/src/move_tool/mod.rs#L413

**Review by davidiw — APPROVED** [review]
oh, I misread... you said ... integration tests :slightly_smiling_face:

**Review by gregnazario — APPROVED** [review]

**Comment by butabara** [comment]
> the code that you're modifying is for tests only, I don't see how it helps you.
> 
> the cli already exposes this via: https://github.com/aptos-labs/aptos-core/blob/0582c623cc46a348428fcca2ef61d25712739db8/crates/aptos/src/move_tool/mod.rs#L413

That's pub(crate) it can't be modified from my own code. I want to spin up a node, compile move code and publish all in one integration test. So the only way to do this is use the cli test framework from what I can see?

**Pull request merged**
