### PR TITLE
[dashboard] update dashboard for new testnets

### PR DESCRIPTION
**Pull request by sherry-x**
### Description

`owner` cannot be easily passed over to the new testnet monitoring helm, so use the pod name instead, this should fix most of the graphs, but would need a followup to fine tune some of them
### Test Plan

applied locally and checked that most of graphs would load

### CODE REVIEW

**Comment by rustielin** [comment]
Shall we get rid of all reference to `owner` in the `prometheus.yaml` config as well?

**Comment by sherry-x** [comment]
@rustielin 

> Shall we get rid of all reference to owner in the prometheus.yaml config as well?

Alerts still has owner things for single node setup, will clean that up in a different PR. This one just updates dashboard

**Review by rustielin — APPROVED** [review]
LGTM

**Comment by rustielin** [comment]
Actually -- one more question. Is there any way to make the dashboards not tightly coupled with k8s environment? Will grafana still render the dashboards if that label is not present? Previously it worked with `owner` if that var was set in the scrape config

**Comment by sherry-x** [comment]
> Actually -- one more question. Is there any way to make the dashboards not tightly coupled with k8s environment? Will grafana still render the dashboards if that label is not present? Previously it worked with owner if that var was set in the scrape config

Do you have a specific case in mind? currently the scrapping job is targets on pod level, so `kubernetes_pod_name` should always exist for testnets/aptos-node

**Comment by rustielin** [comment]
> Do you have a specific case in mind? 

Like if we were to run grafana binary directly, or use the docker-compose: https://github.com/aptos-labs/aptos-core/tree/main/docker/compose/monitoring

**Pull request merged**
